youzan/vant

- build/webpack.build.js
- build/webpack.components.js
- docs/examples-dist/waterfall.vue
- docs/examples-docs/waterfall.md
补充waterfall文档，依赖vue改为Vue
- waterfall 文档补充
- 依赖vue改为Vue
> 补充waterfall文档，依赖vue改为Vue

- build/webpack.config.js
- docs/examples-dist/button.vue
- docs/examples-dist/loading.vue
- docs/examples-dist/swipe.vue
- docs/examples-dist/waterfall.vue
- docs/examples-docs/button.md
- docs/examples-docs/loading.md
- docs/examples-docs/swipe.md
- docs/examples-docs/waterfall.md
- docs/src/ExamplesApp.vue
- docs/src/components/demo-list.vue
- docs/src/components/mobile-computed.js
- docs/src/components/mobile-nav.vue
- docs/src/examples.js
- docs/src/index.js
- package.json
- packages/loading/src/loading.vue
- packages/swipe/src/scroll.js
- packages/vant-css/src/actionsheet.css
- packages/vant-css/src/dialog.css
- packages/vant-css/src/loading.css
- packages/vant-css/src/search.css
- packages/vant-css/src/switch.css
- 文档细节优化
- search、loading和dialog组件样式修复
> 文档细节优化，search、咯阿丁和dialog组件样式修复

- test/unit/specs/uploader.spec.js
> test uploader

- docs/examples-docs/picker.md
- packages/picker/src/picker-column.vue
- packages/picker/src/picker.vue
- packages/vant-css/src/picker.css
- test/unit/specs/picker.spec.js
> picker 增加 title 显示

- docs/examples-docs/card.md
- packages/card/src/card.vue
- packages/vant-css/src/card.css
Card 组件不再根据是否有 footer slot 而居中，而是通过 centered 属性控制。
> Card 组件增加 centered 属性

- packages/vant-css/yarn.lock
- src/mixins/popup/popup-manager.js
- yarn.lock
- 修复：popup多层级van-modal未插入到正确的位置
> 修复：popup多层级van-modal未插入到正确的位置

- docs/examples-docs/datetime-picker.md
- packages/datetime-picker/src/datetime-picker.vue
For [#45](https://github.com/youzan/vant/issues/45)
> fix: datetimepicker cancel event not work

- README.md
- README.zh-CN.md
- packages/vant-css/yarn.lock
- yarn.lock
> README.md使用英文文档

- package.json
> fix: utils 修复babel编译

- packages/swipe/src/swipe.vue
fixed: one page swiper broken problem
> fix: one page swiper broken

- packages/swipe/src/scroll.js
- packages/swipe/src/swipe-item.vue
- packages/swipe/src/swipe.vue
Fixed: one page Swipe components error
> Fixed: one page Swipe components error

- packages/field/src/field.vue
- packages/mixins/popup/index.js
1. fix: popup will not preventScroll by default
2. fix: field textarea height calc wrong
> fix: popup will not preventScroll by default

- build/bin/init.js
- build/webpack.config.dev.js
- docs/examples-docs/deep-select.md
- docs/src/doc.config.js
- packages/deep-select/index.vue
- packages/index.js
- packages/mixins/popup/popup-context.js
- packages/vant-css/src/deep-select.css
- packages/vant-css/src/index.css
- test/unit/specs/deep-select.spec.js
- Add deep-select component
- Fix a bug of popup mixin (about modal z-index)
> Add deep-select component and fix a popup bug.

- docs/examples-docs/sku.md
- packages/sku/components/SkuMessages.vue
- packages/sku/containers/SkuContainer.vue
- test/unit/specs/sku.spec.js
- 修复不同商品，sku留言完全相同时，不会重新渲染留言内容的问题
> fix: sku message key

- docs/examples-docs/waterfall.md
- packages/waterfall/directive.js
- 优化 waterfall 文档
- 修复 waterfall 自身绑定元素为可滚动时，触底计算错误
> 优化：waterfall 文档和组件优化

- packages/vant-css/src/button.css
> fix button actived had 1px blank

- docs/src/examples.js
- docs/src/index.js
> doc router use hash mode

- packages/waterfall/directive.js
- packages/waterfall/index.js
- test/unit/components/waterfall/waterfall-hide.vue
- test/unit/get-webpack-conf.js
- test/unit/specs/waterfall.spec.js
- prevent loadMore after hide
- remove waterfall auto install
> Fix waterfall hide bug

- docs/examples-docs/swipe.md
- add import SwipeItem in doc of Swipe component
> Docs: modify doc of Swipe component 补 Swipe 文档中缺少引入的 SwipeItem

- docs/examples-docs/sku.md
- docs/mock/sku.js
- packages/sku/components/SkuHeader.vue
- test/unit/mock/sku.js
- 去掉zan-utils依赖
- 去掉组件内部对sku图片的处理
> 去掉zan-utils依赖，去掉组件内部对sku图片的处理

- .github/PULL_REQUEST_TEMPLATE.md
- docs/examples-docs/zh-CN/waterfall.md
- docs/src/doc.config.js
> [new feature] Docs: waterfall 文档优化

- packages/search/index.vue
- packages/vant-css/src/search.css
> [bug fix] Search: 优化显示

- docs/examples-docs/zh-CN/search.md
- packages/search/index.vue
- packages/vant-css/src/search.css
- test/unit/specs/search.spec.js
- 增加 v-model 控制搜索内容
- 增加 showAction 控制是否展示右侧行动按钮（默认为取消），background 控制背景色
- 增加 action 的 slot，用于自定义右侧行动按钮
- 移除 type 属性
> [breaking change] Search: 修改原有结构

- docs/examples-docs/zh-CN/search.md
- packages/search/index.vue
> [bug fix] Search: 修复无 reset 下展示

- docs/examples-docs/en-US/cell-swipe.md
- docs/examples-docs/en-US/switch-cell.md
- docs/examples-docs/en-US/tree-select.md
- CellSwipe doc-en
- SwitchCell doc-en
- TreeSelect doc-en
> [Doc] add Advanced components english document

- docs/examples-docs/zh-CN/waterfall.md
> [bug fix] Doc: Update waterfall.md 

- packages/mixins/popup/index.js
- packages/mixins/popup/popup-manager.js
给mixins里popup增加了两个props，overlayClass和overlayStyle，并赋值到创建的dom里，以便自定义遮罩层的样式。
> [new feature]Popup: 增加遮罩层overlayClass和overlayStyle属性，以提供遮罩层自定义样式 

- packages/checkbox/index.vue
- test/unit/components/checkbox.vue
- test/unit/specs/checkbox.spec.js
Fixes #424 
- fix `disabled` property in checkbox component
> [bugfix] disabled property in checkbox

- docs/demos/views/coupon.vue
- test/unit/specs/coupon.spec.js
> [improvement] fix typo

- docs/demos/views/sku.vue
- docs/markdown/en-US/sku.md
- docs/markdown/zh-CN/sku.md
- packages/sku/Sku.vue
- packages/sku/components/SkuStepper.vue
- packages/sku/constants.js
- packages/sku/index.js
- test/unit/specs/sku.spec.js
> [new feature] sku组件增加步进器相关自定义配置

- packages/sku/components/SkuMessages.vue
- test/unit/specs/sku.spec.js
- 修复sku数据改变后skuMessages没有更新的bug
> [bugfix] 修复sku数据改变后skuMessages没有更新的bug

- docs/demos/views/checkbox.vue
- docs/markdown/en-US/checkbox.md
- docs/markdown/zh-CN/checkbox.md
- packages/checkbox-group/index.vue
- packages/checkbox/index.vue
- test/unit/components/checkbox.vue
- test/unit/specs/checkbox.spec.js
New feature
Made in this pull request:
- support config the maximum amount of checked options
- add markdown and test
> [new feature] Checkbox: support config the maximum amount of checked options

- docs/demos/views/sku.vue
- docs/markdown/en-US/sku.md
- docs/markdown/zh-CN/sku.md
- packages/sku/Sku.vue
-  add close-on-click-overlay config for sku popup (default false)
> [new feature] add close-on-click-overlay config for sku popup

- packages/sku/Sku.vue
- packages/sku/components/SkuRowItem.vue
- packages/sku/constants.js
- packages/sku/utils/skuHelper.js
- 修复sku库存为0时也默认选中的bug
- 修复sku value id为0时选中状态判断错误的bug
> [bugfix] 修复sku默认选中逻辑与sku是否选中的判断逻辑

- docs/markdown/en-US/icon.md
- docs/markdown/zh-CN/icon.md
> [Doc] add custom Icon directions

- docs/markdown/en-US/picker.md
- docs/markdown/zh-CN/picker.md
> [Doc] fix picker demo

- docs/markdown/en-US/i18n.md
- docs/markdown/zh-CN/i18n.md
- package-lock.json
- packages/locale/lang/zh-HK.js
> [locate] add zh-HK

- package.json
- packages/datetime-picker/index.vue
使用husky配合lint-staged对暂存区的待提交文件进行 eslint 检查，存在报错则拦截 commit
> [Improvement] add git hook, optimize dev process

- packages/mixins/popup/index.js
- yarn.lock
Fixes #833 
之前新增 touch.js 时，没有正确绑定 touchStart 事件以初始化滚动位置记录的变量，导致判断逻辑出错。
> [bugfix] Popup: fix lock scroll

- docs/markdown/en-US/radio.md
- docs/markdown/zh-CN/radio.md
> [Doc] fix Radio document

- packages/list/index.vue
Fixes #947 
- 修复List组件不支持loading-text属性
> [bugfix] List: loading-text support

- packages/datetime-picker/index.vue
Fixes #1072 
- fix datetime-picker initial value error
> [bugfix] DatetimePicker: initial value error (#1072)

- packages/dialog/en-US.md
- packages/dialog/zh-CN.md
> [Doc] fix dialog document

- docs/markdown/theme.zh-CN.md
> docs(doc): postcss tips

- docs/markdown/theme.zh-CN.md
> [Doc] Update document format

- packages/datetime-picker/index.vue
这里应该是传入picker的visible-item-count
> [bugfix]Datetime-picker:fix typo

- types/component.d.ts
> [ bug fix ] fix error when use Vue.use in typescript

- packages/swipe-item/index.vue
- packages/swipe/demo/index.vue
- packages/swipe/en-US.md
- packages/swipe/index.vue
- packages/swipe/test/__snapshots__/demo.spec.js.snap
- packages/swipe/zh-CN.md
> [new feature] Swipe: support custom item width & height

- packages/tab/demo/index.vue
- packages/tab/en-US.md
- packages/tab/zh-CN.md
- packages/tabs/index.vue
> [new feature] Tab: add scroll event

- packages/datetime-picker/index.vue
> [Improvement] DatetimePicker: refactor getMonthEndDay function

- packages/sku/demo/index.vue
> [bugfix]: demo of miswriting

- packages/radio/zh-CN.md
修改radio API文档 diabled -> disabled
> [Doc] update radio/zh-CN

- packages/swipe/demo/index.vue
- packages/swipe/en-US.md
- packages/swipe/index.vue
- packages/swipe/test/__snapshots__/demo.spec.js.snap
- packages/swipe/zh-CN.md
修改：
- 添加名称为indicator的slot
- 默认值之前的指示器的样式
- 添加了符合vant风的demo
> [improvement] Swipe: add indicator slot

- packages/toast/index.js
> [bugfix] Toast: fix instance when SSR

- packages/locale/lang/tr-TR
2. If you've added code that should be tested, add tests!
5. Make sure your code lints (`npm run lint`).
6. Describe your pull request.
[bug fix / breaking change / new feature] 组件名字：修改内容描述
说明：
* 前面方括号用来区分 Issue / PR 的 类型：bug fix - 改 bug；breaking change: 不兼容的改动；new feature：新功能
* 修改内容尽可能言简意赅，总结 PR 的改动或者描述 Issue
* 描述请用中文
* 组件名字请用英文，首字母大写
示例：
* [bug fix] Button: 修改颜色
* [breaking change] Loading: 删除  `static` 属性
* [new feature] Form: 增加 `FormSelection` 支持
* [new feature] 新增 Abc 组件
Fixes #xx(issue number here), remove …
> Turkish lang. support

- packages/locale/lang/zh-TW.js
> [new feature] Add zh-TW

- packages/step/index.less
Fixes #2067
- packages/step/index.less
> 修复Step 组件在按需引用时，垂直方向 icon-checked 样式错乱

- packages/sku/components/SkuMessages.vue
> 补齐mobile类型留言的placeholder

- yarn.lock
Fixes https://github.com/youzan/vant/issues/2250
- 升级watchpack 版本
> [bug fix] yarn.lock: 升级watchpack 版本，避免 node v10+报错

- packages/tree-select/demo/index.vue
- packages/tree-select/index.less
- packages/tree-select/index.vue
- packages/tree-select/test/__snapshots__/demo.spec.js.snap
> [new feature] TreeSelect: update style、support disable nav item

- packages/coupon-list/demo/index.vue
- packages/coupon-list/en-US.md
- packages/coupon-list/zh-CN.md
- packages/coupon/index.js
- packages/coupon/index.less
- 增加新属性 condition，originCondition将在下个大版本废除
> [new feature] Coupon: add new prop condition

- packages/field/index.less
- Field: 修复ios下input type为datetime-local时的高度问题
> [bugfix] Field: 修复ios下input type为datetime-local时的高度问题

- packages/sku/components/SkuMessages.js
- packages/utils/index.ts
- [bugfix] Sku: 修复ios12留言点击错位问题
> [bugfix] Sku: 修复ios12留言点击错位问题

- packages/search/demo/index.vue
- packages/search/en-US.md
- packages/search/index.js
- packages/search/index.less
- packages/search/test/__snapshots__/demo.spec.js.snap
- packages/search/zh-CN.md
- packages/style/var.less
- update style
- add new prop shape
- add new prop label
> [new feature] Search: update style, add new prop shape、label

- packages/button/en-US.md
- packages/button/zh-CN.md
- packages/cell/en-US.md
- packages/cell/zh-CN.md
- packages/checkbox/en-US.md
- packages/checkbox/zh-CN.md
- packages/goods-action/en-US.md
- packages/goods-action/zh-CN.md
- packages/notice-bar/en-US.md
- packages/notice-bar/zh-CN.md
- packages/tabbar/en-US.md
- packages/tabbar/zh-CN.md
Fix erroneous and missing content in the document
> [doc]Fix erroneous and missing content in the document

- packages/swipe/index.js
> [bug fix] swipe: 修改swipe字体模糊问题

- packages/rate/index.tsx
2. If you've added code that should be tested, add tests!
5. Make sure your code lints (`npm run lint`).
6. Describe your pull request.
[bug fix / breaking change / new feature] 组件名字：修改内容描述
说明：
* 前面方括号用来区分 Issue / PR 的 类型：bug fix - 改 bug；breaking change: 不兼容的改动；new feature：新功能
* 修改内容尽可能言简意赅，总结 PR 的改动或者描述 Issue
* 描述请用中文
* 组件名字请用英文，首字母大写
示例：
* [bug fix] Button: 修改颜色
* [breaking change] Loading: 删除  `static` 属性
* [new feature] Form: 增加 `FormSelection` 支持
* [new feature] 新增 Abc 组件
Fixes #xx(issue number here), remove …
> [improvement] Rate: readonly和disabled的时候touchMove不应该做任何事

- packages/tabbar/en-US.md
- packages/tabbar/index.js
- packages/tabbar/index.less
- packages/tabbar/zh-CN.md
Fixed #1855
Changes in this pull request:
- 利用新特性来优化 tabbar 在 iPhone X 中的底部问题
使用时需要 html meta viewport 中添加 viewport-fit=cover 来激活
> [improvement] Tabbar: add iPhone X layout feature for fixed tabbar

- packages/step/index.js
- packages/steps/en-US.md
- packages/steps/zh-CN.md
remove document of top bar props, should be deprecated in v2
> [new feature] Step: add active-icon slot

- README.zh-CN.md
- packages/submit-bar/demo/index.vue
- packages/submit-bar/en-US.md
- packages/submit-bar/index.less
- packages/submit-bar/index.tsx
- packages/submit-bar/test/__snapshots__/demo.spec.js.snap
- packages/submit-bar/zh-CN.md
> [new feature] SubmitBar: add tip-icon prop

- packages/pull-refresh/index.js
- packages/pull-refresh/test/__snapshots__/demo.spec.js.snap
- packages/pull-refresh/test/__snapshots__/index.spec.js.snap
> [bugfix] PullRefresh: transform style (#3256)

- packages/utils/test/index.spec.js
- packages/utils/validate/src.ts
> [bugfix] Utils: is-src add blob image source

- packages/address-edit/test/__snapshots__/index.spec.js.snap
- packages/area/test/__snapshots__/demo.spec.js.snap
- packages/area/test/__snapshots__/index.spec.js.snap
- packages/area/test/index.spec.js
- packages/datetime-picker/test/__snapshots__/demo.spec.js.snap
- packages/picker/PickerColumn.js
- packages/picker/index.js
- packages/picker/index.less
- packages/picker/test/__snapshots__/demo.spec.js.snap
- packages/picker/test/__snapshots__/index.spec.js.snap
- packages/picker/test/index.spec.js
> [improvement] Picker: 交互优化

- docs/markdown/changelog.zh-CN.md
fix typo（`guter` -> `gutter`）
Example：
> [bugfix] docs: Update changelog.zh-CN.md

- packages/toast/Toast.js
toggleClickale 拼写错误 =>>  修改为 toggleClickable
Example：
> [improvement] toggleClickable 拼写错误

- packages/address-edit/test/__snapshots__/index.spec.js.snap
- packages/area/test/__snapshots__/demo.spec.js.snap
- packages/area/test/__snapshots__/index.spec.js.snap
- packages/datetime-picker/test/__snapshots__/demo.spec.js.snap
- packages/picker/PickerColumn.js
- packages/picker/index.js
- packages/picker/test/__snapshots__/demo.spec.js.snap
- packages/picker/test/__snapshots__/index.spec.js.snap
> [improvement] Picker: stop momentum before emit confim event

- src/picker/PickerColumn.js
- src/picker/index.less
>  [bugfix] Picker: fix the error at low version of the Android

- build/build-lib.js
> [improvement] Build: remove unnecessary argument in build script

- src/datetime-picker/index.js
https://github.com/youzan/vant/issues/3795
> [bugfix] DatetimePicker: confirm event param incorrect when use filter

- src/collapse-item/index.js
- src/swipe/README.md
- src/swipe/README.zh-CN.md
- src/swipe/index.js
- src/swipe/test/index.spec.js
- src/utils/dom/raf.ts
https://github.com/youzan/vant/issues/3799
> [new feature] Swipe: add immediate option of swipeTo method

- src/dropdown-menu/README.md
- src/dropdown-menu/README.zh-CN.md
- src/dropdown-menu/test/__snapshots__/index.spec.js.snap
- src/dropdown-menu/test/index.spec.js
- src/mixins/click-outside.ts
https://github.com/youzan/vant/issues/3806
> [new feature] DropdownMenu: add close-on-click-outside prop

- src/pull-refresh/README.md
- src/pull-refresh/README.zh-CN.md
- src/pull-refresh/index.js
- src/pull-refresh/test/__snapshots__/index.spec.js.snap
- src/pull-refresh/test/index.spec.js
https://github.com/youzan/vant/issues/3807
> [new feature] PullRefresh: add distance of slotProps

- src/area/test/__snapshots__/demo.spec.js.snap
- src/area/test/__snapshots__/index.spec.js.snap
- src/datetime-picker/test/__snapshots__/demo.spec.js.snap
- src/picker/PickerColumn.js
- src/picker/test/__snapshots__/demo.spec.js.snap
- src/picker/test/__snapshots__/index.spec.js.snap
https://github.com/youzan/vant/issues/3828
> [improvement] Picker: add class for selected item

- src/dropdown-menu/test/__snapshots__/index.spec.js.snap
- src/mixins/popup/overlay.ts
https://github.com/youzan/vant/issues/3797
https://github.com/youzan/vant/issues/3819
> [bugfix] Popup: overlay may cover popup in some cases

- src/sku/README.md
- src/sku/README.zh-CN.md
- src/sku/components/SkuMessages.js
- src/sku/type.ts
- src/utils/types.ts
https://github.com/youzan/vant/issues/3841
> [new feature] Sku: support custom placeholder

- build/build-entry.js
2. Follow the [contributing guide](https://github.com/youzan/vant/blob/dev/.github/CONTRIBUTING.md) to setup your develop environment.
Example：
> [typo] build: fix typo

- src/coupon-list/README.md
- src/coupon-list/README.zh-CN.md
- src/coupon-list/index.js
- src/coupon-list/test/__snapshots__/index.spec.js.snap
- src/coupon-list/test/index.spec.js
https://github.com/youzan/vant/issues/3927
> [new feature] CouponList: add empty-image prop

- src/index-bar/index.js
https://github.com/youzan/vant/issues/3933
> [bugfix] IndexBar: should update when index-list updated

- src/sticky/index.js
- src/tabs/index.js
https://github.com/youzan/vant/issues/3931
> [bugfix] Tabs: fix scroll position deviation when sticky

- src/swipe-cell/README.md
- src/swipe-cell/README.zh-CN.md
- src/swipe-cell/index.js
https://github.com/youzan/vant/issues/3950
https://github.com/youzan/vant/issues/3880
> [new feature] SwipeCell: add stop-propagation prop

- docs/site/doc.config.js
> [Doc]: Fix typo, remove Chinese characters.

- src/image-preview/ImagePreview.js
- src/image-preview/test/__snapshots__/index.spec.js.snap
- src/uploader/test/__snapshots__/index.spec.js.snap
#3999 
* [bugfix] ImagePreview: Image beyond the screen height cover index
> [bugfix] ImagePreview: Image beyond the screen height cover index

- src/sku/components/SkuMessages.js
#3986 
[bugfix] Sku: sku data no message error
> [bugfix] Sku: sku data no message error

- src/uploader/README.zh-CN.md
- src/uploader/test/utils.spec.js
- src/uploader/utils.ts
https://github.com/youzan/vant/issues/4022
> [new feature] Uploader: support isImage flag

- src/tabs/index.js
https://github.com/youzan/vant/issues/4090
> [bugfix] Tab: incorrect title position when insert tab pane

- src/action-sheet/README.zh-CN.md
https://github.com/youzan/vant/issues/4095
> [Doc] ActionSheet: add tips of component name

- src/collapse/README.md
- src/collapse/README.zh-CN.md
> [Doc] Collapse: fix misapprehensive type of params

- package.json
- src/tabbar/test/index.spec.js
- src/utils/router.ts
- yarn.lock
https://github.com/youzan/vant/issues/4141
> [bugfix] Tabbar: avoid navigation duplicated

- src/tabbar-item/index.js
- src/tabbar/test/__snapshots__/index.spec.js.snap
- src/tabbar/test/index.spec.js
https://github.com/youzan/vant/issues/4141
> [new feature] Tabbar: support match route by to.name

- src/area/README.md
- src/area/README.zh-CN.md
- src/area/index.js
https://github.com/youzan/vant/issues/4127
> [new feature] Area: add is-oversea-code prop

- src/style/hairline.less
https://github.com/youzan/vant/issues/4181
> fix: hairline missing relative position

- package.json
- packages/vant-eslint-config/index.js
- packages/vant-eslint-config/package.json
- yarn.lock
this rule is conflict with prettier
> chore(lint): remove vue/max-attributes-per-line rule

- src/uploader/README.md
- src/uploader/README.zh-CN.md
- src/uploader/demo/index.vue
- src/uploader/index.js
- src/uploader/test/index.spec.js
https://github.com/youzan/vant/issues/4173
> feat(Uploader): add click-preview event

- src/dropdown-menu/index.js
- src/dropdown-menu/index.less
- src/dropdown-menu/test/__snapshots__/index.spec.js.snap
- src/dropdown-menu/test/index.spec.js
- src/style/var.less
https://github.com/youzan/vant/issues/4200
> feat(DropdownMenu): add @dropdown-menu-title-active-text-color less var

- src/cell-group/index.tsx
- src/cell/README.md
- src/cell/README.zh-CN.md
- src/cell/test/__snapshots__/index.spec.js.snap
- src/cell/test/index.spec.js
https://github.com/youzan/vant/issues/4217
> feat(CellGroup): add title slot

- src/number-keyboard/index.less
https://github.com/youzan/vant/issues/4222
> fix(NumberKeyboard): incorrect sidebar position when has title

- src/image/README.md
- src/image/README.zh-CN.md
- src/image/index.js
- src/image/test/__snapshots__/index.spec.js.snap
- src/image/test/index.spec.js
https://github.com/youzan/vant/issues/4223
> feat(Image): add radius prop

- src/locale/README.md
- src/locale/lang/es-ES.ts
Adds Spanish (Spain) translation
> feat(Locale): add Spanish (Spain) translation

- src/sku/Sku.js
- src/sku/components/SkuHeader.tsx
- src/sku/type.ts
> feat(Sku): can preview images of non-first level sku

- src/notify/Notify.tsx
- src/notify/README.md
- src/notify/README.zh-CN.md
- src/notify/demo/index.vue
- src/notify/index.less
- src/notify/index.ts
- src/notify/test/__snapshots__/demo.spec.js.snap
- src/notify/test/__snapshots__/index.spec.js.snap
- src/notify/test/index.spec.js
- src/style/var.less
- types/notify.d.ts
https://github.com/youzan/vant/issues/4220
> feat(Notify): add type prop

- src/circle/index.js
- src/circle/index.less
- src/circle/test/__snapshots__/demo.spec.js.snap
- src/circle/test/__snapshots__/index.spec.js.snap
https://github.com/youzan/vant/issues/4254
> fix(Circle): stroke-width can't be greater than 60

- src/picker/PickerColumn.js
https://github.com/youzan/vant/issues/4210
> fix(Picker): avoid click event when moving

- src/picker/PickerColumn.js
- src/picker/README.md
- src/picker/README.zh-CN.md
- src/picker/index.js
- src/picker/shared.ts
- src/picker/test/__snapshots__/index.spec.js.snap
- src/picker/test/index.spec.js
https://github.com/youzan/vant/issues/4270
> feat(Picker): add allow-html prop

- src/password-input/README.md
- src/password-input/README.zh-CN.md
- src/password-input/demo/index.vue
- src/password-input/index.less
- src/password-input/index.tsx
- src/password-input/test/__snapshots__/demo.spec.js.snap
- src/style/var.less
https://github.com/youzan/vant/issues/4221
> feat(NumberKeyboard): add focused prop

- docs/markdown/theme.en-US.md
- docs/markdown/theme.zh-CN.md
https://github.com/youzan/vant/issues/4275
> docs(theme): add guide of override with less file

- src/image-preview/ImagePreview.js
https://github.com/youzan/vant/issues/4301
> fix(ImagePreview): should reset scale after toggle

- src/tree-select/README.md
- src/tree-select/README.zh-CN.md
- src/tree-select/index.tsx
- src/tree-select/test/index.spec.js
https://github.com/youzan/vant/issues/4307
> feat(TreeSelect): add max prop

- src/dropdown-item/index.js
- src/dropdown-item/index.less
- src/dropdown-menu/test/__snapshots__/index.spec.js.snap
- src/style/var.less
https://github.com/youzan/vant/issues/4329
> fix(DropdownItem): missing default active color

- src/sidebar/README.md
- src/sidebar/README.zh-CN.md
- src/slider/index.js
- src/slider/test/index.spec.js
- src/tree-select/README.md
- src/tree-select/README.zh-CN.md
https://github.com/youzan/vant/issues/4335
> fix(Slider): should format initial value

- src/dialog/Dialog.js
https://github.com/youzan/vant/issues/4348
> fix(Dialog): should reset loading when close

- src/uploader/README.md
- src/uploader/README.zh-CN.md
- src/uploader/index.js
- src/uploader/test/index.spec.js
https://github.com/youzan/vant/issues/4375
> feat(Uploader): add close-preview event

- src/field/index.less
https://github.com/youzan/vant/issues/4379
> fix(Field): reset appearance in safari

- src/tree-select/README.md
- src/tree-select/README.zh-CN.md
- src/tree-select/index.tsx
- src/tree-select/test/__snapshots__/index.spec.js.snap
- src/tree-select/test/index.spec.js
https://github.com/youzan/vant/issues/4158
> feat(TreeSelect): support show info

- src/uploader/index.js
https://github.com/youzan/vant/issues/4406
> fix(Uploader): should't emit click-preview when delete

- src/uploader/README.md
- src/uploader/README.zh-CN.md
- src/uploader/index.js
- src/uploader/test/index.spec.js
https://github.com/youzan/vant/issues/4458
> feat(Uploader): add index param

- src/address-list/Item.tsx
- src/address-list/index.less
- src/address-list/test/__snapshots__/demo.spec.js.snap
- src/style/var.less
https://github.com/youzan/vant/issues/4466
> feat(AddressList): add @address-list-item-radio-icon-color var

- src/datetime-picker/DatePicker.js
- src/datetime-picker/utils.ts
https://github.com/youzan/vant/issues/4474
> fix(DatetimePicker): infinite loop when use formatted text is unnumeric

- src/search/README.md
- src/search/README.zh-CN.md
- src/search/demo/index.vue
- src/search/index.tsx
- src/search/test/__snapshots__/index.spec.js.snap
- src/search/test/index.spec.js
https://github.com/youzan/vant/issues/4497
> feat(Search): add action-text prop

- packages/vant-doc/src/component/Block.vue
- packages/vant-doc/src/style/highlight.less
- src/card/index.less
- src/dialog/index.less
- src/grid-item/index.less
- src/notice-bar/index.less
- src/notify/index.less
- src/sidebar-item/index.less
- src/sku/index.less
- src/toast/index.less
https://github.com/youzan/vant/issues/4503
> feat: improve word wrap

- src/overlay/README.md
- src/overlay/README.zh-CN.md
- src/overlay/demo/index.vue
- src/overlay/index.tsx
- src/overlay/test/__snapshots__/index.spec.js.snap
- src/overlay/test/index.spec.js
https://github.com/youzan/vant/issues/4559
> feat(Overlay): add default slot

- src/area/README.md
- src/area/README.zh-CN.md
- src/area/demo/index.vue
- src/area/index.js
- src/area/test/__snapshots__/demo.spec.js.snap
feat(Area): add columns-placeholder prop
> feat(Area): add columns-placeholder prop

- src/uploader/index.js
https://github.com/youzan/vant/issues/4543
> fix(Uploader): incorrect preview index when upload same images

- src/address-edit/README.md
- src/address-edit/README.zh-CN.md
- src/address-edit/index.js
feat(address-edit): add area-columns-placeholder props
> feat(address-edit): add area-columns-placeholder props

- types/index.d.ts
https://github.com/youzan/vant/issues/4599
> types: fix missing overlay component

- docs/src/docs-entry.js
- packages/area/demo/index.vue
- packages/area/en-US.md
- packages/area/index.js
- packages/area/zh-CN.md
feat(Area): columns placeholder
> feat(Area): columns placeholder

- src/number-keyboard/Key.js
https://github.com/youzan/vant/issues/4626
> fix(NumberKeyboard): compatible with Vue 2.6 event bubble bug

- src/stepper/index.js
https://github.com/youzan/vant/issues/4672
> fix(Stepper): can't work when step is small

- src/uploader/README.md
- src/uploader/README.zh-CN.md
- src/uploader/index.js
- src/uploader/test/index.spec.js
- src/uploader/utils.ts
https://github.com/youzan/vant/issues/4408
> feat(Uploader): add file result-type

- src/goods-action/README.md
- src/goods-action/README.zh-CN.md
https://github.com/youzan/vant/issues/4679
> docs(GoodsAction): fix missing double quote

- src/utils/router.ts
https://github.com/youzan/vant/issues/4703
> fix: router err maybe undefined

- docs/src/docs-entry.js
- packages/address-edit/demo/index.vue
- packages/area/index.js
feat(Area): getArea method filter placeholder
> feat(Area): getArea method filter placeholder

- src/address-edit/README.md
- src/address-edit/README.zh-CN.md
- src/address-edit/demo/index.vue
- src/address-edit/index.js
- src/address-edit/test/__snapshots__/index.spec.js.snap
- src/address-edit/test/index.spec.js
- src/area/index.js
feat(AddressEdit): add area confirmation verification
> feat(AddressEdit): add area confirmation verification

- .github/CONTRIBUTING.md
- .gitpod.yml
- build/webpack.site.dev.js
Hi! there, :slightly_smiling_face:
this PR adds support for Gitpod, a free online tool that lets you automate your dev environment, eases the hurdles for contributions and generally working on GitHub projects. It allows anyone to get a ready-to-code dev environment for any branch, issue and pull request with a single click.
You can give it a try on my fork of the repo: https://gitpod.io/#https://github.com/nisarhassan12/vant
t seems to work well! Please let me know if there is anything that can be improved. I would love to help :)
> Simplifies code contributions and reviews + automates the dev enviroment

- src/address-edit/index.js
- src/area/index.js
fix(AddressEdit): choose overseas failure when configuring placeholer
> fix(AddressEdit): choose overseas failure when configuring placeholer

- src/style/var.less
- src/toast/README.md
- src/toast/README.zh-CN.md
- src/toast/Toast.js
- src/toast/demo/index.vue
- src/toast/index.less
- src/toast/test/__snapshots__/index.spec.js.snap
https://github.com/youzan/vant/issues/4774
> feat(Toast): add @toast-loading-icon-color var

- src/toast/Toast.js
- src/toast/index.less
- src/toast/test/__snapshots__/index.spec.js.snap
https://github.com/youzan/vant/issues/4774
> feat(Toast): add type classNames

- src/picker/PickerColumn.js
- src/picker/README.md
- src/picker/README.zh-CN.md
- src/picker/demo/index.vue
- src/picker/index.js
- src/picker/shared.ts
https://github.com/youzan/vant/issues/4812
> feat(Picker): add swipe-duration prop

- src/address-edit/README.md
- src/address-edit/README.zh-CN.md
docs(AddressEdit): docs area-columns-placeholder error
> docs(AddressEdit): docs area-columns-placeholder error

- src/grid-item/index.js
- src/grid-item/index.less
- src/grid/test/__snapshots__/index.spec.js.snap
- src/grid/test/index.spec.js
https://github.com/youzan/vant/issues/4899
> fix(Grid): info、dot prop not work when use icon slot

- src/uploader/README.md
- src/uploader/README.zh-CN.md
- src/uploader/index.js
- src/uploader/test/index.spec.js
https://github.com/youzan/vant/issues/4924
> feat(Uploader): add deletable prop

- src/stepper/README.md
- src/stepper/README.zh-CN.md
- src/stepper/index.js
- src/stepper/test/index.spec.js
https://github.com/youzan/vant/issues/4907
> feat(Stepper): add name prop

- src/tag/README.md
- src/tag/README.zh-CN.md
https://github.com/youzan/vant/issues/4937
> docs(Tag): fix closeable demo

- src/style/mixins/hairline.less
https://github.com/youzan/vant/issues/4932
> fix: can't custom hairline border color

- src/toast/README.md
- src/toast/README.zh-CN.md
- src/toast/index.js
- types/toast.d.ts
https://github.com/youzan/vant/issues/4900
> feat(Toast): add clickOnClickOverlay option

- src/swipe/README.md
- src/swipe/README.zh-CN.md
- src/swipe/index.js
https://github.com/youzan/vant/issues/4970
> feat(Swipe): add stop-propagation prop

- src/datetime-picker/utils.ts
https://github.com/youzan/vant/issues/4819
> fix(DatetimePicker): can't change when filter when empty array

- src/swipe-cell/README.md
- src/swipe-cell/README.zh-CN.md
- src/swipe-cell/index.js
- src/swipe-cell/test/index.spec.js
https://github.com/youzan/vant/issues/4955
> feat(SwipeCell): add opened event

- src/tab/index.js
- src/tab/test/index.spec.js
https://github.com/youzan/vant/issues/4988
> fix(Tab): can't match when name is 0

- src/action-sheet/README.md
- src/action-sheet/README.zh-CN.md
https://github.com/youzan/vant/issues/5001
> docs(ActionSheet): add close-icon description

- src/cell/index.less
https://github.com/youzan/vant/issues/5027
> fix(Cell): should break word of value

- src/dropdown-item/index.js
- src/dropdown-menu/demo/index.vue
https://github.com/youzan/vant/issues/5025
> fix(DropdownMenu): should't close when custom container and get clicked

- src/field/demo/index.vue
- src/field/index.js
https://github.com/youzan/vant/issues/5033
> fix(Field): incorrect count of line break in safari

- src/swipe/README.md
- src/swipe/README.zh-CN.md
- src/swipe/index.js
- src/swipe/test/index.spec.js
https://github.com/youzan/vant/issues/5051
> feat(Swipe): add resize method

- src/swipe-cell/demo/index.vue
- src/swipe-cell/index.js
- src/swipe-cell/test/__snapshots__/demo.spec.js.snap
- src/swipe-cell/test/index.spec.js
https://github.com/youzan/vant/issues/5026
> fix(SwipeCell): compatible with desktop scenario

- src/popup/README.md
- src/popup/README.zh-CN.md
https://github.com/youzan/vant/issues/5074
> docs: add tips of get-container in root node

- src/tabbar/index.less
https://github.com/youzan/vant/issues/5045
> fix(Tabbar): incorrect style when using safe-area-inset-bottom

- src/overlay/README.md
- src/overlay/README.zh-CN.md
https://github.com/youzan/vant/issues/5068
> docs(Overlay): add api version tip

- src/field/README.md
- src/field/README.zh-CN.md
- src/search/README.md
- src/search/README.zh-CN.md
https://github.com/youzan/vant/issues/5095
> docs: add desc of autofocus prop

- src/number-keyboard/index.js
数字键盘在开启状态并设置了hideOnClickOutside才触发onBlur事件
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
> fix(NumberKeyboard):  数字键盘在开启状态并设置了hideOnClickOutside才触发onBlur事件

- src/tree-select/index.tsx
- src/tree-select/test/index.spec.js
https://github.com/youzan/vant/issues/5136
> fix(TreeSelect): should sync value before trigger click-item event

- src/count-down/README.md
- src/count-down/README.zh-CN.md
- src/count-down/demo/index.vue
- src/count-down/test/__snapshots__/index.spec.js.snap
- src/count-down/test/index.spec.js
- src/count-down/utils.ts
https://github.com/youzan/vant/issues/5129
> feat(CountDown): support SS and S format

- src/style/var.less
- src/tag/index.less
> fix spelling mistake

- src/uploader/index.js
https://github.com/youzan/vant/issues/5164
> fix(Uploader): not trigger oversize event when upload same file

- src/stepper/README.md
- src/stepper/README.zh-CN.md
- src/stepper/index.js
- src/stepper/test/index.spec.js
feat(Stepper): add disabledPlus & disabledMinus props
> feat(Stepper): add disable-plus & disable-minus props

- src/card/index.less
- src/card/index.tsx
- src/card/test/__snapshots__/demo.spec.js.snap
- src/style/var.less
fix(Card): fix price font-family
> fix(Card): fix price font-family

- src/submit-bar/index.tsx
fix(SubmitBar): fix decimal-length  bug
fix #5141
> fix(SubmitBar): fix decimal-length  bug

- src/address-list/Item.tsx
https://github.com/youzan/vant/issues/5228
> fix(AddressList): incorrect tel when isDefault is 0

- src/card/index.tsx
- src/card/test/__snapshots__/demo.spec.js.snap
https://github.com/youzan/vant/issues/5227
> chore(Card): add class for currency

- src/dropdown-item/index.js
- src/dropdown-menu/README.md
- src/dropdown-menu/README.zh-CN.md
https://github.com/youzan/vant/issues/5261#issuecomment-565324843
> docs(DropdownItem): add closed event

- src/dialog/Dialog.js
https://github.com/youzan/vant/issues/5263
> fix(Dialog): show not trigger close event when hidden

- src/coupon-list/test/__snapshots__/index.spec.js.snap
- src/tab/README.zh-CN.md
- src/tab/index.js
- src/tab/test/__snapshots__/demo.spec.js.snap
- src/tab/test/__snapshots__/index.spec.js.snap
- src/tab/test/index.spec.js
- src/tabs/Title.js
- src/tabs/index.js
- src/tabs/index.less
https://github.com/youzan/vant/issues/5240
can't use both dot and title ellipsis in current version
> feat(Tab): add dot prop

- src/checkbox-group/index.js
https://github.com/youzan/vant/issues/5284
> feat(Checkbox): improve toggleAll perf

- src/mixins/popup/index.js
https://github.com/youzan/vant/issues/5243
> fix(Popup): should reopen when activated

- src/dropdown-item/index.js
- src/dropdown-menu/index.js
- src/list/test/index.spec.js
https://github.com/youzan/vant/issues/5305
> fix(DropdownMenu): incorrect menu position when scroll

- .github/workflows/test.yml
- src/tab/README.md
- src/tab/README.zh-CN.md
- src/tab/demo/index.vue
- src/tab/index.js
- src/tab/test/index.spec.js
https://github.com/youzan/vant/issues/5138
> feat(Tabs): add rendered prop

- src/sku/README.md
- src/sku/README.zh-CN.md
- src/sku/Sku.js
- src/sku/demo/data.ts
- src/sku/demo/index.vue
- src/sku/test/index.spec.js
https://github.com/youzan/vant/issues/5132
> feat(Sku): add resetSelectedSku method

- packages/vant-cli/src/compiler/compile-site.ts
fix(VantCli): enable Lan access
> fix(VantCli): enable Lan access

- src/count-down/README.md
- src/count-down/README.zh-CN.md
- src/count-down/demo/index.vue
- src/count-down/index.js
https://github.com/youzan/vant/issues/5330
> fix(CountDown): infinite tick if call reset after finish

- src/image-preview/index.js
- src/image-preview/test/index.spec.js
https://github.com/youzan/vant/issues/5338
> fix(ImagePreview): onClose should only trigger once

- src/mixins/touch.ts
- src/picker/PickerColumn.js
- src/swipe/index.js
> fix(Swipe): avoid Vue 2.6 event bubble issues

- packages/vant-cli/site/mobile/components/DemoSection.vue
- src/pull-refresh/index.js
> fix(PullRefresh): avoid Vue 2.6 event bubble issues

- src/swipe-cell/index.js
> fix(SwipeCell): avoid Vue 2.6 event bubble issues

- src/number-keyboard/Key.js
> fix(NumberKeyboard): avoid Vue 2.6 event bubble issues

- src/checkbox/README.zh-CN.md
- src/checkbox/index.js
- types/checkbox-group.d.ts
- types/checkbox.d.ts
- types/index.d.ts
https://github.com/youzan/vant/issues/5329
> types(Checkbox): add toggle method type

- src/list/README.md
- src/list/README.zh-CN.md
- src/list/index.js
- src/list/test/__snapshots__/index.spec.js.snap
- src/list/test/index.spec.js
https://github.com/youzan/vant/issues/5384
> feat(List): add finished slot

- src/toast/Toast.js
- src/toast/lock-click.ts
- src/toast/test/index.spec.js
https://github.com/youzan/vant/issues/5383
> fix(Toast): may lose forbid click when has multiple toasts

- src/image-preview/ImagePreview.js
- src/image-preview/test/index.spec.js
https://github.com/youzan/vant/issues/5338
> fix(ImagePreview): should't emit close when tapped in async-close mode 

- src/action-sheet/index.tsx
- src/dialog/Dialog.js
- src/image-preview/ImagePreview.js
- src/image-preview/demo/index.vue
- src/image-preview/test/index.spec.js
- src/mixins/popup/index.js
- src/mixins/popup/overlay.ts
- src/notify/Notify.tsx
- src/popup/index.js
- src/toast/Toast.js
- types/image-preview.d.ts
https://github.com/youzan/vant/issues/5338
> fix(ImagePreview): close event triggered twice

- src/tag/index.less
- src/tag/index.tsx
https://github.com/youzan/vant/issues/5407
> fix(Tag): incorrect transition when set closeable dynamically

- src/datetime-picker/DatePicker.js
- src/datetime-picker/README.md
- src/datetime-picker/README.zh-CN.md
- src/datetime-picker/TimePicker.js
- src/datetime-picker/shared.js
- src/picker/README.md
- src/picker/README.zh-CN.md
- src/picker/index.js
- types/datetime-picker.d.ts
- types/index.d.ts
- types/picker.d.ts
https://github.com/youzan/vant/issues/5401
> feat(Picker): add confirm method

- src/button/README.md
- src/button/README.zh-CN.md
- src/button/demo/index.vue
- src/button/test/__snapshots__/demo.spec.js.snap
- src/cell/README.md
- src/cell/README.zh-CN.md
- src/cell/demo/index.vue
- src/cell/test/__snapshots__/demo.spec.js.snap
- src/checkbox/README.md
- src/checkbox/README.zh-CN.md
- src/checkbox/demo/index.vue
- src/checkbox/test/__snapshots__/demo.spec.js.snap
- src/radio/README.md
- src/radio/README.zh-CN.md
- src/radio/demo/index.vue
- src/radio/test/__snapshots__/demo.spec.js.snap
- docs(Button): 添加块级元素事例
- docs(Cell): 添加多行文本垂直居中事例
- docs(Checkbox): 添加自定义图标大小，禁用文本点击事例
- docs(Radio): 添加自定义图标大小，自定义形状，禁用文本点击事例
> docs(Button/Cell/Checkbox/Radio): update some examples

- src/stepper/index.less
https://github.com/youzan/vant/issues/5427
> fix(Stepper): input disabled text color in safari

- src/picker/PickerColumn.js
https://github.com/youzan/vant/issues/5421
> fix(Picker): compatible with desktop scenario

- src/coupon-cell/index.tsx
- src/coupon-list/test/__snapshots__/index.spec.js.snap
- src/locale/lang/en-US.ts
- src/locale/lang/es-ES.ts
- src/locale/lang/tr-TR.ts
- src/locale/lang/zh-CN.ts
- src/locale/lang/zh-HK.ts
- src/locale/lang/zh-TW.ts
- refactor(CouponCell): modify tips
- refactor(CouponCell): prefer to use value over denominations
> feat(CouponCell): prefer to use value over denominations & modify tips

- src/calendar/components/Month.js
- src/calendar/test/__snapshots__/demo.spec.js.snap
- src/calendar/test/__snapshots__/index.spec.js.snap
https://github.com/youzan/vant/issues/5451
> fix(Calendar): incorrect day offset

- src/image/README.md
- src/image/README.zh-CN.md
- src/image/demo/index.vue
- src/image/index.js
- src/image/test/__snapshots__/index.spec.js.snap
- src/image/test/index.spec.js
https://github.com/youzan/vant/issues/5463
> feat(Image): add loading-icon prop

- src/image/README.md
- src/image/README.zh-CN.md
- src/image/index.js
- src/image/test/__snapshots__/index.spec.js.snap
- src/image/test/index.spec.js
https://github.com/youzan/vant/issues/5463
> feat(Image): add error-icon prop

- packages/vant-cli/src/common/index.ts
- packages/vant-cli/src/compiler/gen-package-entry.ts
- packages/vant-cli/src/compiler/gen-package-style.ts
- packages/vant-cli/src/compiler/gen-site-desktop-shared.ts
- packages/vant-cli/src/compiler/gen-site-mobile-shared.ts
> fix(vant-cli): replace \ to / in path #5431

- src/card/index.less
fix(Card): thumb image border-radius become effective
> fix(Card): thumb image border-radius become effective

- src/stepper/README.md
- src/stepper/README.zh-CN.md
https://github.com/youzan/vant/issues/5484
> docs(Stepper): add default-value description

- src/field/README.md
- src/field/README.zh-CN.md
- src/field/demo/index.vue
- src/field/index.js
- src/field/test/__snapshots__/demo.spec.js.snap
- src/field/test/index.spec.js
https://github.com/youzan/vant/issues/5425
> fix(Field): should limit number input in iOS

- src/calendar/index.js
- src/calendar/test/index.spec.js
- test/dom.ts
https://github.com/youzan/vant/issues/5500
> feat(Calendar): scroll to current month when show

- src/calendar/components/Month.js
https://github.com/youzan/vant/issues/5533
> fix(Calendar): missing info when selected

- src/pull-refresh/README.md
- src/pull-refresh/README.zh-CN.md
- src/pull-refresh/demo/index.vue
- src/pull-refresh/index.js
- src/pull-refresh/index.less
- src/pull-refresh/test/__snapshots__/demo.spec.js.snap
- src/pull-refresh/test/__snapshots__/index.spec.js.snap
- src/pull-refresh/test/index.spec.js
https://github.com/youzan/vant/issues/5499
> fix(PullRefresh): should set height when using head-height

- src/swipe/README.md
- src/swipe/README.zh-CN.md
- src/swipe/index.js
- src/swipe/test/index.spec.js
https://github.com/youzan/vant/issues/5546
> feat(Swipe): add prev、next method

- src/locale/lang/zh-CN.ts
- src/locale/lang/zh-HK.ts
https://github.com/youzan/vant/issues/5556
> chore(AddressEdit): update confirm delete message

- src/image-preview/demo/index.vue
- src/image-preview/index.less
https://github.com/youzan/vant/issues/5557
> feat(ImagePreview): improve error image style

- src/search/README.md
- src/search/README.zh-CN.md
- src/search/demo/index.vue
- src/search/test/__snapshots__/demo.spec.js.snap
feat(Search): Search  demo desc adjustment
> docs(Search): Search  demo desc adjustment

- src/rate/README.md
- src/rate/README.zh-CN.md
- src/rate/demo/index.vue
- src/rate/test/__snapshots__/demo.spec.js.snap
feat(Rete): Rate change event demo
> docs(Rate): add change event demo

- src/action-sheet/README.md
- src/calendar/README.md
- src/calendar/README.zh-CN.md
- src/calendar/index.js
https://github.com/youzan/vant/issues/5607
> feat(Calendar): add get-contaienr prop

- src/sku/README.md
- src/sku/README.zh-CN.md
- src/sku/Sku.js
- src/sku/demo/index.vue
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
> feat(sku): add sku-actions-top slot

- packages/vant-cli/site/desktop/components/Header.vue
> 修复文档选择相同版本时跳转到undefiend的bug

- src/style/var.less
- src/uploader/README.md
- src/uploader/README.zh-CN.md
- src/uploader/demo/index.vue
- src/uploader/index.js
- src/uploader/index.less
- src/uploader/test/__snapshots__/demo.spec.js.snap
- src/uploader/utils.ts
https://github.com/youzan/vant/issues/4231
> feat(Uploader): support failed status

- src/style/var.less
- src/uploader/README.md
- src/uploader/README.zh-CN.md
- src/uploader/demo/index.vue
- src/uploader/index.js
- src/uploader/index.less
- src/uploader/test/__snapshots__/demo.spec.js.snap
https://github.com/youzan/vant/issues/4231
> feat(Uploader): support uploading status

- packages/vant-cli/src/commands/changelog.ts
- packages/vant-cli/src/compiler/gen-site-desktop-shared.ts
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
> fix(vant-cli): fix the bug of getting MD file

- src/style/var.less
- src/uploader/README.md
- src/uploader/README.zh-CN.md
- src/uploader/demo/index.vue
- src/uploader/index.js
- src/uploader/index.less
- src/uploader/test/__snapshots__/demo.spec.js.snap
feat(Uploader): add uploader component disabled style
> feat(Uploader): add uploader component disabled style

- src/tabs/index.js
https://github.com/youzan/vant/issues/5636
> fix(Tabs): scrollspy not work when customing scroller

- packages/vant-cli/src/common/index.ts
- packages/vant-cli/src/compiler/gen-component-style.ts
- packages/vant-cli/src/compiler/gen-style-deps-map.ts
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
> fix(vant-cli): fix Windows system build style problems

- src/image-preview/ImagePreview.js
- src/image-preview/README.md
- src/image-preview/README.zh-CN.md
- src/image-preview/index.js
- src/image-preview/test/index.spec.js
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
> feat(imagePreview): add scale event

- src/sku/components/SkuMessages.js
fix(Sku): initialMessages undefined error
> fix(Sku): initialMessages undefined error

- src/sku/README.md
- src/sku/README.zh-CN.md
- src/sku/Sku.js
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
> feat(Sku): add preview-on-click-image prop

- src/uploader/README.md
- src/uploader/README.zh-CN.md
- src/uploader/index.js
- src/uploader/test/index.spec.js
- yarn.lock
Related：
#5804
#4864
使用 https://github.com/fengyuanchen/compressorjs ，向 beforeRead 中传入 Promise ，对用户在上传的图片进行压缩和旋转等自定义处理。
> feat(Uploader): use before read promise resolved value

- src/swipe-cell/README.md
- src/swipe-cell/README.zh-CN.md
#5836 
先修改了SwipeCell的文档(所有修改已在本地测试通过)，
如果对于这个组件文档的修改通过，
就依照这个样子，将其余组件的文档也修改了
> docs(SwipeCell): change "slot" to "v-slot"

- src/calendar/index.js
> fix(Calendar): fix the default date of multiple selection type

- packages/vant-cli/package.json
- packages/vant-cli/src/compiler/compile-sfc.ts
- packages/vant-cli/src/module.d.ts
- packages/vant-cli/yarn.lock
> feat(cli): support scoped style

- src/sidebar/index.less
https://github.com/youzan/vant/issues/5914
> feat(Sidebar): set overflow-y auto

- src/image-preview/test/__snapshots__/index.spec.js.snap
- src/swipe/index.js
https://github.com/youzan/vant/issues/5912
> fix(Swipe): incorrect offset after resize

- src/field/index.js
- src/form/README.md
- src/form/README.zh-CN.md
- src/form/index.js
- src/form/test/props.spec.js
https://github.com/youzan/vant/issues/5924
> feat(Form): add show-error-message prop

- src/number-keyboard/README.md
- src/number-keyboard/README.zh-CN.md
- src/number-keyboard/demo/index.vue
- src/number-keyboard/index.js
- src/number-keyboard/index.less
- src/number-keyboard/test/index.spec.js
https://github.com/youzan/vant/issues/5929
> fix(NumberKeyboard): show-delete-key prop not work

- src/field/index.js
- src/form/README.md
- src/form/README.zh-CN.md
- src/form/index.js
- src/form/test/props.spec.js
https://github.com/youzan/vant/issues/5924
> feat(Form): add show-error prop

- src/button/README.md
- src/button/README.zh-CN.md
- src/button/index.tsx
- src/button/test/__snapshots__/index.spec.js.snap
- src/button/test/index.spec.js
https://github.com/youzan/vant/issues/5945
> fix(Button): icon-prefix prop not work

- src/nav-bar/index.less
https://github.com/youzan/vant/issues/5930
> fix(NavBar): icon align center

- src/picker/PickerColumn.js
https://github.com/youzan/vant/issues/5925
> feat(Picker): improve scroll speed

- src/field/index.js
- src/stepper/index.js
https://github.com/youzan/vant/issues/5961
> fix(Stepper): readonly not work in lagacy mobile safari

- src/calendar/README.zh-CN.md
- src/calendar/demo/index.vue
- src/calendar/index.js
https://github.com/youzan/vant/issues/5967
> fix(Calendar): rendering error when activated

- src/nav-bar/test/__snapshots__/index.spec.js.snap
- src/nav-bar/test/index.spec.js
- src/tabbar/README.md
- src/tabbar/README.zh-CN.md
- src/tabbar/index.js
- src/tabbar/test/__snapshots__/index.spec.js.snap
- src/tabbar/test/index.spec.js
https://github.com/youzan/vant/issues/5972
> feat(Tabbar): add placeholder prop

- src/field/index.js
- src/form/index.js
- src/form/test/index.spec.js
- src/mixins/relation.ts
- src/utils/vnodes.ts
https://github.com/youzan/vant/issues/5966
> fix(Form): incorrect validation order when add field dynamically

- src/empty/README.md
- src/empty/README.zh-CN.md
- src/empty/demo/index.vue
- src/empty/index.js
- src/empty/index.less
- src/empty/test/__snapshots__/demo.spec.js.snap
- src/empty/test/__snapshots__/index.spec.js.snap
- src/empty/test/demo.spec.js
- src/empty/test/index.spec.js
- src/style/var.less
- types/index.d.ts
- vant.config.js
https://github.com/youzan/vant/issues/4862
> feat: add Empty component

- src/address-edit/README.md
- src/address-edit/README.zh-CN.md
- src/address-edit/index.js
feat(AddressEdit): add areaPlaceholder props
> feat(AddressEdit): add area-placeholder prop

- src/utils/vnodes.ts
https://github.com/youzan/vant/issues/6042
> fix: sortChildren broke SSR

- src/image/README.md
- src/image/README.zh-CN.md
- src/image/test/index.spec.js
close https://github.com/youzan/vant/issues/6047
> docs(Image): rename Image to VanImage

- src/empty/Network.tsx
- src/empty/index.js
- src/empty/test/__snapshots__/index.spec.js.snap
- src/empty/test/index.spec.js
- yarn.lock
https://github.com/youzan/vant/issues/6041
> feat(Empty): support offline scenario

- src/slider/index.js
- src/slider/index.less
- src/slider/test/__snapshots__/demo.spec.js.snap
- src/slider/test/__snapshots__/index.spec.js.snap
https://github.com/youzan/vant/issues/6062
> fix(Slider): incorrect bar-height when vertical

- src/checkbox/test/index.spec.js
- src/mixins/checkbox.js
https://github.com/youzan/vant/issues/6064
> fix(Checkbox): get changed value in click event

- src/picker/index.js
https://github.com/youzan/vant/issues/6077
> fix(Picker): setColumnValues failed in cascade mode

- src/overlay/README.md
- src/overlay/README.zh-CN.md
- src/overlay/index.tsx
- src/overlay/test/index.spec.js
https://github.com/youzan/vant/issues/6032
> feat(Overlay): add lock-scroll prop

- src/uploader/README.md
- src/uploader/README.zh-CN.md
- src/uploader/index.js
https://github.com/youzan/vant/issues/6061
> feat(Uploader): add lazy-load prop

- src/image-preview/test/__snapshots__/index.spec.js.snap
- src/swipe/index.js
https://github.com/youzan/vant/issues/6036
> fix(Swipe): incorrect width after resize if hidden

- src/utils/vnodes.ts
https://github.com/youzan/vant/issues/6067
> fix: sort vnode not work

- packages/vant-cli/docs/config.md
https://github.com/youzan/vant/issues/6054
> docs(cli): add srcDir config

- src/image-preview/ImagePreview.js
- src/image-preview/test/index.spec.js
https://github.com/youzan/vant/issues/6128
> feat(ImagePreview): adjust double-click interval to 250ms

- src/image-preview/ImagePreview.js
- src/tab/test/__snapshots__/insert.spec.js.snap
- src/tab/test/insert.spec.js
- src/utils/vnodes.ts
https://github.com/youzan/vant/issues/6118
> fix: incorrect vnode order in some cases

- src/uploader/index.js
- src/uploader/test/__snapshots__/index.spec.js.snap
- src/uploader/test/index.spec.js
https://github.com/youzan/vant/issues/6113
> fix(Uploader): file message should be reactive

- src/col/index.js
- src/col/test/__snapshots__/demo.spec.js.snap
- src/image/test/__snapshots__/demo.spec.js.snap
- src/mixins/relation.ts
- src/row/index.js
https://github.com/youzan/vant/issues/6130
> fix(Layout): outside of the screen after setting gutter

- src/nav-bar/index.less
https://github.com/youzan/vant/issues/6145
> style(NavBar): left & right part align to bottom

- types/component.d.ts
https://github.com/youzan/vant/issues/6134
> types: VanComponent should extends Vue

- src/uploader/README.md
- src/uploader/README.zh-CN.md
- src/uploader/demo/index.vue
- src/uploader/index.js
- src/uploader/test/__snapshots__/demo.spec.js.snap
- src/uploader/test/index.spec.js
> fix(uploader): automatically filter files exceeding the max-size

- src/checkbox/index.less
https://github.com/youzan/vant/issues/6165
> fix(Checkbox): incorrect icon position after font-size scale

- src/notice-bar/index.js
https://github.com/youzan/vant/issues/6185
> fix(NoticeBar): allow dynamic setting of scrollable

- src/locale/lang/ro-RO.ts
> feat(Locale): adding Romanian language support - ro-RO.ts

- src/field/README.md
- src/field/README.zh-CN.md
- src/field/index.js
- src/field/test/__snapshots__/index.spec.js.snap
- src/field/test/index.spec.js
- src/form/README.md
https://github.com/youzan/vant/issues/6192
> feat(Field): add colon prop

- src/col/index.js
- src/col/test/__snapshots__/demo.spec.js.snap
- src/col/test/__snapshots__/index.spec.js.snap
- src/col/test/index.spec.js
- src/image/test/__snapshots__/demo.spec.js.snap
- src/mixins/relation.ts
- src/row/index.js
https://github.com/youzan/vant/issues/6166
> fix(Layout): gutter calculation

- src/calendar/README.md
- src/calendar/README.zh-CN.md
- src/calendar/index.js
- src/calendar/test/index.spec.js
- src/calendar/utils.ts
https://github.com/youzan/vant/issues/6184
> feat(Calendar): add unselect event

- src/calendar/README.md
- src/calendar/README.zh-CN.md
- src/calendar/index.js
- src/calendar/test/prop.spec.js
https://github.com/youzan/vant/issues/6184
> feat(Calendar): support max-range when type is multiple

- src/sku/README.md
- src/sku/README.zh-CN.md
- src/sku/Sku.js
增加`sku-reset`事件，以供内外规格与属性选择状态一致
> feat(Sku): add sku-reset event

- src/step/index.js
https://github.com/youzan/vant/issues/6210
> fix(Step): active-color should effect circle

- src/field/index.js
- src/field/test/index.spec.js
https://github.com/youzan/vant/issues/6262
> fix(Field): textarea line break failed on enter

- docs/markdown/theme.en-US.md
- docs/markdown/theme.zh-CN.md
Reference: https://github.com/youzan/vant/issues/6236 https://github.com/youzan/vant/issues/6223
> docs: adopt changes on less-loader v6.0.0

- src/number-keyboard/README.md
- src/number-keyboard/README.zh-CN.md
- src/number-keyboard/demo/index.vue
- src/number-keyboard/index.js
- src/number-keyboard/test/__snapshots__/demo.spec.js.snap
https://github.com/youzan/vant/issues/6264
> feat(NumberKeyboard): support multiple extra key

- src/calendar/README.md
- src/calendar/README.zh-CN.md
- src/calendar/index.js
- src/calendar/test/prop.spec.js
https://github.com/youzan/vant/issues/6291
> feat(Calendar): add month-show event

- src/notice-bar/index.js
- src/notice-bar/index.less
- src/notice-bar/test/__snapshots__/demo.spec.js.snap
- src/notice-bar/test/__snapshots__/index.spec.js.snap
- src/notice-bar/test/index.spec.js
https://github.com/youzan/vant/issues/6072
> fix(NoticeBar): replay event only triggered once

- src/utils/format/number.ts
- src/utils/test/index.spec.js
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
> fix(Field): minus can only be placed on the first char

- types/picker.d.ts
> types(Picker): support generic

- src/form/README.md
- src/form/README.zh-CN.md
- src/form/index.js
- types/form.d.ts
https://github.com/youzan/vant/issues/6334
> feat(Form): scrollToField can scroll to bottom

- src/field/index.js
- src/form/README.md
- src/form/README.zh-CN.md
- src/form/index.js
https://github.com/youzan/vant/issues/6240
> feat(Form): add submit-on-enter prop

- src/goods-action-button/index.less
- src/goods-action/README.md
- src/goods-action/README.zh-CN.md
- src/goods-action/demo/index.vue
- src/goods-action/test/__snapshots__/demo.spec.js.snap
https://github.com/youzan/vant/issues/6342
> fix(GoodsAction): incorrect single button radius

- src/address-list/index.less
https://github.com/youzan/vant/issues/6351
> style(AddressList): add safe-area-inset-bottom

- src/area/index.js
https://github.com/youzan/vant/issues/6352
> feat(Area): use first city code when county list is empty

- src/dropdown-menu/test/__snapshots__/index.spec.js.snap
- src/dropdown-menu/test/index.spec.js
- src/mixins/popup/context.ts
- src/mixins/popup/index.js
- src/mixins/popup/overlay.ts
https://github.com/youzan/vant/issues/6288
> refactor(Popup): create overlay for every popup

- src/field/README.zh-CN.md
- src/search/README.zh-CN.md
https://github.com/youzan/vant/issues/6367
> docs(Search): add clear icon faq

- src/field/index.js
https://github.com/youzan/vant/issues/6378
> fix(Field): can not disable error in form

- src/sidebar-item/index.js
- src/sidebar/index.js
- src/sidebar/test/index.spec.js
- src/tree-select/test/index.spec.js
https://github.com/youzan/vant/issues/6379
> fix(Sidebar): should emit change when v-model changed

- src/notice-bar/index.js
- src/notice-bar/test/__snapshots__/demo.spec.js.snap
- src/notice-bar/test/__snapshots__/index.spec.js.snap
- src/notice-bar/test/index.spec.js
https://github.com/youzan/vant/issues/6415
> fix(NoticeBar): scroll failed after activated

- src/mixins/popup/overlay.ts
https://github.com/youzan/vant/issues/6418
> fix(Popup): incorrect overlay z-index when reopened

- src/image-preview/README.zh-CN.md
- src/notify/Notify.tsx
- src/notify/README.md
- src/notify/README.zh-CN.md
- src/notify/demo/index.vue
- src/notify/index.less
- src/notify/index.ts
- src/notify/test/__snapshots__/demo.spec.js.snap
- types/notify.d.ts
https://github.com/youzan/vant/issues/6436
> feat(Notify): support component call

- src/dropdown-item/index.js
- src/dropdown-menu/README.md
- src/dropdown-menu/README.zh-CN.md
https://github.com/youzan/vant/issues/6444
> feat(DropdownItem): add lazy-render prop

- src/share-sheet/README.md
- src/share-sheet/README.zh-CN.md
- src/share-sheet/demo/index.vue
- src/share-sheet/index.js
- src/share-sheet/index.less
- src/style/var.less
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
> feat(ShareSheet): add options description

- src/picker/index.js
https://github.com/youzan/vant/issues/6461
> fix(Picker): cursor.defaultIndex may be 0

- src/utils/router.ts
- yarn.lock
https://github.com/youzan/vant/issues/6458
> fix(Tabbar): avoid redundant navigation error

- src/tabs/index.js
https://github.com/youzan/vant/issues/6484
> chore(Tab): rename onShow to init

- src/field/index.js
- src/field/test/index.spec.js
https://github.com/youzan/vant/issues/6476
> fix(Field): formatter not work when v-model changed

- src/image-preview/ImagePreview.js
- src/image-preview/test/__snapshots__/index.spec.js.snap
https://github.com/youzan/vant/issues/4553
> fix(ImagePreview): image blurred after scale on iOS

- src/field/README.md
- src/field/README.zh-CN.md
- src/stepper/README.md
- src/stepper/README.zh-CN.md
- src/stepper/index.js
- src/stepper/test/__snapshots__/index.spec.js.snap
- src/stepper/test/index.spec.js
https://github.com/youzan/vant/issues/6517
> feat(Stepper): add placeholder prop

- src/collapse-item/index.js
- src/collapse-item/index.less
https://github.com/youzan/vant/issues/6526
> fix(CollapseItem): can't hide border

- src/field/index.js
- src/form/test/events.spec.js
https://github.com/youzan/vant/issues/6535
> feat(Form): rule message can be empty

- src/field/index.js
- src/field/test/index.spec.js
https://github.com/youzan/vant/issues/6537
> fix(Field): should not display null

- src/dialog/Dialog.js
- src/dialog/index.js
- src/dialog/test/__snapshots__/index.spec.js.snap
- src/dialog/test/index.spec.js
- types/dialog.d.ts
https://github.com/youzan/vant/issues/6555
> feat(Dialog): add allow-html prop

- src/image-preview/README.md
- src/image-preview/README.zh-CN.md
- src/image-preview/index.js
- src/image-preview/test/index.spec.js
- types/image-preview.d.ts
ImagePreview通过函数调用是可以用getContainer自定义挂载节点的。
> docs(ImagePreview): optimizing in Options

- src/picker/index.js
- src/picker/test/__snapshots__/cascade.spec.js.snap
- src/picker/test/cascade.spec.js
https://github.com/youzan/vant/issues/6578
> fix(Picker): disabled not work in cascade mode

- src/button/index.less
- src/style/var.less
should be merged in next minor version
> style(Button): adjust small button size

- src/image-preview/ImagePreview.js
- src/image-preview/README.md
- src/image-preview/README.zh-CN.md
- src/image-preview/demo/index.vue
- src/image-preview/test/index.spec.js
- types/image-preview.d.ts
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
> feat(ImagePreview): add swipeTo method

- src/sku/components/SkuRowItem.js
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
> fix(Sku): small image mode and text ellipsis

- src/sku/components/SkuRow.js
- src/sku/components/SkuRowItem.js
- src/sku/index.less
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
> fix(Sku): scroll issue and add default picture

- src/field/README.zh-CN.md
https://github.com/youzan/vant/issues/6374
https://github.com/youzan/vant/issues/6608
> docs(Field): add input type faq

- src/stepper/index.js
https://github.com/youzan/vant/issues/6645
> fix(Stepper): incorrect button disable status

- src/image-preview/ImagePreviewItem.js
- src/image-preview/test/__snapshots__/index.spec.js.snap
- src/image-preview/test/index.spec.js
https://github.com/youzan/vant/issues/5402
> fix(ImagePreview): incorrect position after scale

- src/image-preview/ImagePreviewItem.js
- src/image-preview/index.less
- src/image-preview/test/__snapshots__/index.spec.js.snap
- src/image-preview/test/index.spec.js
https://github.com/youzan/vant/issues/6642
> fix(ImagePreview): longpress error on mobile safari

- src/area/test/__snapshots__/demo.spec.js.snap
- src/area/test/__snapshots__/index.spec.js.snap
- src/datetime-picker/test/__snapshots__/date-picker.spec.js.snap
- src/datetime-picker/test/__snapshots__/datetime-picker.spec.js.snap
- src/datetime-picker/test/__snapshots__/demo.spec.js.snap
- src/datetime-picker/test/__snapshots__/time-picker.spec.js.snap
- src/picker/PickerColumn.js
- src/picker/index.less
- src/picker/test/__snapshots__/cascade.spec.js.snap
- src/picker/test/__snapshots__/demo.spec.js.snap
- src/picker/test/__snapshots__/index.spec.js.snap
- src/style/var.less
https://github.com/youzan/vant/issues/6602
> fix(Picker): revert add @picker-option-height var

- src/dialog/README.md
- src/dialog/README.zh-CN.md
https://github.com/youzan/vant/issues/6665
> docs(Dialog): add allow-html prop

- src/image-preview/ImagePreviewItem.js
- src/number-keyboard/Key.js
https://github.com/youzan/vant/issues/6498
> fix(NumberKeyboard): eliminate tap delay on safari

- src/mixins/popup/index.js
https://github.com/youzan/vant/issues/6673
> fix(Popup): lock-scroll not work in some cases

- src/search/README.md
- src/search/README.zh-CN.md
- src/search/index.tsx
https://github.com/youzan/vant/issues/6681
> feat(Search): add clear-trigger prop

- src/uploader/README.md
- src/uploader/README.zh-CN.md
- src/uploader/demo/index.vue
- src/uploader/index.js
- src/uploader/index.less
- src/uploader/test/__snapshots__/demo.spec.js.snap
- src/uploader/test/__snapshots__/index.spec.js.snap
- src/uploader/test/index.spec.js
https://github.com/youzan/vant/issues/6618
> feat(Uploader): add preview-cover slot

- src/calendar/components/Month.js
- src/calendar/index.js
https://github.com/youzan/vant/issues/6709
> fix(Calendar): subtitle not updated in some cases

- src/image/index.js
- src/utils/index.ts
https://github.com/youzan/vant/issues/6711
> fix(Image): memory leak during SSR

- src/picker/PickerColumn.js
https://github.com/youzan/vant/issues/6644
> fix(Picker):  click during momentum case incorrect result

- types/image-preview.d.ts
https://github.com/youzan/vant/issues/6708
> types(ImagePreview): swipeTo should be optional

- src/mixins/relation.js
https://github.com/youzan/vant/issues/6659
> fix(Checkbox): dynamic bind group

- src/password-input/index.tsx
- src/password-input/test/__snapshots__/demo.spec.js.snap
feat(PasswordInput): add focused item className ,support  focused Item customize style
> feat(PasswordInput): add focus item className

- src/submit-bar/README.md
- src/submit-bar/README.zh-CN.md
- src/submit-bar/index.tsx
- src/submit-bar/test/__snapshots__/index.spec.js.snap
- src/submit-bar/test/index.spec.js
https://github.com/youzan/vant/issues/6740
> feat(SubmitBar): add button-color prop

- src/step/index.js
- src/steps/README.md
- src/steps/README.zh-CN.md
- src/steps/index.js
- src/steps/test/__snapshots__/index.spec.js.snap
- src/steps/test/index.spec.js
https://github.com/youzan/vant/issues/6720
> feat(Steps): add inactive-color prop

- src/stepper/README.md
- src/stepper/README.zh-CN.md
- src/stepper/index.js
- src/stepper/test/index.spec.js
https://github.com/youzan/vant/issues/6735
> feat(Stepper): add allow-empty prop

- src/calendar/README.md
- src/calendar/README.zh-CN.md
- src/calendar/components/Header.js
- src/calendar/components/Month.js
- src/calendar/demo/index.vue
- src/calendar/index.js
- src/calendar/test/__snapshots__/demo.spec.js.snap
- src/calendar/test/prop.spec.js
Add `firstDayOfWeek` support to `Calendar` component
for example
```jsx
<Calendar firstDayOfWeek={1} />
```
```jsx
<Calendar firstDayOfWeek={6} />
```
> feat: calendar support firstDayOfWeek

- src/number-keyboard/Key.js
- src/number-keyboard/index.less
- src/number-keyboard/test/__snapshots__/demo.spec.js.snap
- src/number-keyboard/test/__snapshots__/index.spec.js.snap
- src/password-input/test/__snapshots__/demo.spec.js.snap
https://github.com/youzan/vant/issues/6799
> fix(NumberKeyboard): flex not work on legacy safari

- src/uploader/README.md
- src/uploader/README.zh-CN.md
- src/uploader/index.js
- src/uploader/test/index.spec.js
https://github.com/youzan/vant/issues/6797
> feat(Uploader): add preview-options prop

- src/image-preview/index.less
https://github.com/youzan/vant/issues/6792
> fix(ImagePreview): image overflow in some cases

- src/calendar/index.js
- src/utils/dom/scroll.ts
https://github.com/youzan/vant/issues/6749
> fix(Calendar): rendering fails in some cases

- README.md
- README.zh-CN.md
- docs/markdown/home.en-US.md
- docs/markdown/home.zh-CN.md
https://github.com/youzan/vant/issues/3930
> docs: add vant-react link

- src/area/README.md
- src/area/README.zh-CN.md
- src/datetime-picker/README.md
- src/datetime-picker/README.zh-CN.md
- src/picker/README.md
- src/picker/README.zh-CN.md
- src/sticky/README.md
- src/sticky/README.zh-CN.md
- src/sticky/test/__snapshots__/index.spec.js.snap
- src/sticky/test/index.spec.js
- src/tab/README.md
- src/tab/README.zh-CN.md
- src/utils/format/unit.ts
https://github.com/youzan/vant/issues/6796
> feat: Sticky/Picker support vw unit

- src/tab/README.md
- src/tab/README.zh-CN.md
- src/tab/demo/index.vue
- src/tab/test/__snapshots__/demo.spec.js.snap
- src/tab/test/index.spec.js
- src/tabs/index.js
https://github.com/youzan/vant/issues/6685
> feat(Tabs): add before-change prop

- src/image-preview/ImagePreview.js
- src/swipe/index.js
https://github.com/youzan/vant/issues/6753
> fix(ImagePreview): fit orientationchange

- src/picker/README.zh-CN.md
Fixed spelling-problems: citys -> cities
> docs(Picker): fix spelling-problems

- src/address-edit/README.md
- src/address-edit/README.zh-CN.md
- src/address-edit/index.js
- src/address-edit/test/index.spec.js
https://github.com/youzan/vant/issues/6826
> feat(AddressEdit): add tel-maxlength prop

- src/mixins/portal.js
- src/number-keyboard/README.md
- src/number-keyboard/README.zh-CN.md
- src/number-keyboard/index.js
https://github.com/youzan/vant/issues/6864
> feat(NumberKeyboard): add get-container prop

- src/share-sheet/README.md
- src/share-sheet/README.zh-CN.md
- src/share-sheet/demo/index.vue
- src/share-sheet/index.js
- src/share-sheet/test/index.spec.js
> feat(ShareSheet): add className option

- src/coupon-cell/index.tsx
- src/coupon-list/test/__snapshots__/index.spec.js.snap
> style(Coupon): insert a space after currency

- src/tab/README.md
- src/tab/README.zh-CN.md
- src/tab/test/__snapshots__/demo.spec.js.snap
- src/tabs/index.js
- src/tabs/index.less
- 开启滚动默认个数调整至 5 个
- 调整 `complete` 模式下的选项间隔
> [improvement] adjust padding in complete mode

- src/calendar/components/Month.js
- src/calendar/index.js
- src/calendar/test/index.spec.js
- src/calendar/test/prop.spec.js
https://github.com/youzan/vant/issues/6866
> fix(Calendar): should not scroll document when inited

- src/dialog/Dialog.js
- src/dialog/README.md
- src/dialog/README.zh-CN.md
- src/dialog/demo/index.vue
- src/dialog/index.js
- src/dialog/index.less
- src/dialog/test/__snapshots__/demo.spec.js.snap
- src/style/var.less
- types/dialog.d.ts
- add new prop button-theme
- change default confirm button color
> feat(Dialog): add new prop theme

- src/address-edit/index.js
- src/address-edit/test/__snapshots__/index.spec.js.snap
https://github.com/youzan/vant/issues/6933
> fix(AddressEdit): render error in some cases

- src/picker/index.js
> fix(Picker): When item.defaultIndex is 0, this.defaultIndex will be used

- src/share-sheet/README.zh-CN.md
https://github.com/youzan/vant/issues/6951
> docs(ShareSheet): add hide cancel button guide

- .github/workflows/preview.yml
- vant.config.js
https://github.com/marketplace/actions/surge-pr-preview
> chore: add surge preview action

- src/calendar/components/Month.js
- src/calendar/test/__snapshots__/index.spec.js.snap
https://github.com/youzan/vant/issues/7043
> fix(Calendar): row-height should work on selected month

- vant.config.js
https://github.com/youzan/vant/issues/6954
> docs: fix gitee search result hostname

- src/action-sheet/README.md
- src/action-sheet/README.zh-CN.md
- src/action-sheet/index.tsx
- src/action-sheet/test/__snapshots__/index.spec.js.snap
- src/action-sheet/test/index.spec.js
https://github.com/youzan/vant/issues/7055
> feat(ActionSheet): add description slot

- docs/markdown/design.zh-CN.md
https://github.com/youzan/vant/issues/7049
> docs: add axure resource

- src/tabbar/README.md
- src/tabbar/README.zh-CN.md
- src/tabbar/index.js
- src/utils/interceptor.ts
- src/utils/test/interceptor.spec.js
https://github.com/youzan/vant/issues/7062
> feat(Tabbar): add before-change prop

- src/dialog/README.md
- src/dialog/README.zh-CN.md
> docs: fix theme in dialog

- src/toast/index.js
https://github.com/youzan/vant/issues/7093
> fix(Toast): failed to clear in some cases

- src/form/index.js
https://github.com/youzan/vant/issues/7088
> fix(Form): scroll to first matched field

- src/field/index.js
https://github.com/youzan/vant/issues/7092
> fix(Form): should reset validation before submit

- src/picker/PickerColumn.js
- src/picker/README.md
- src/picker/README.zh-CN.md
- src/picker/index.js
- src/picker/shared.ts
- src/picker/test/index.spec.js
https://github.com/youzan/vant/issues/7070
> feat(Picker): add readonly prop

- src/area/README.md
- src/area/README.zh-CN.md
- src/area/index.js
https://github.com/youzan/vant/issues/7070
> feat(Area): add readonly prop

- src/field/index.js
- src/utils/format/number.ts
- src/utils/test/index.spec.js
https://github.com/youzan/vant/issues/7089
> fix(Field): disallow minus when using digit type

- src/calendar/README.md
- src/calendar/README.zh-CN.md
- src/calendar/components/Month.js
- src/calendar/index.js
https://github.com/youzan/vant/issues/7013
> feat(Calendar): allow default-date to be null

- src/coupon-cell/index.tsx
fix(CouponCell): fix discounted price
> fix(CouponCell): fix discounted price

- src/calendar/index.js
https://github.com/youzan/vant/issues/7120
> fix(Calendar): readonly not work in multiple mode

- src/list/index.js
https://github.com/youzan/vant/issues/7121
> fix(List): scoped style not applied to first child

- src/image-preview/ImagePreview.js
- src/image-preview/ImagePreviewItem.js
- src/image-preview/test/index.spec.js
https://github.com/youzan/vant/issues/7133
> fix(ImagePreview): incorrect move range in some cases

- src/tabs/index.js
https://github.com/youzan/vant/issues/7135
> fix(Tabs): incorrect scroll position when offset-top has unit

- packages/vant-cli/site/common/style/base.less
- src/style/var.less
https://github.com/youzan/vant/issues/7147
> fix(Tag): text vertical align in miui

- src/notice-bar/index.js
https://github.com/youzan/vant/issues/7132
> fix(NoticeBar): fix cache issues with forwards and back history in safari

- src/button/README.md
- src/button/README.zh-CN.md
- src/button/index.less
- src/button/index.tsx
- src/button/test/__snapshots__/index.spec.js.snap
- src/button/test/index.spec.js
https://github.com/youzan/vant/issues/7129
> feat(Button): add icon-position prop

- src/slider/README.md
- src/slider/README.zh-CN.md
- src/slider/demo/index.vue
- src/slider/index.js
- src/slider/index.less
> feat(slider): add dual thumb mode for slider

- src/slider/README.md
- src/slider/README.zh-CN.md
- src/slider/demo/index.vue
- src/slider/index.js
- src/slider/index.less
- src/slider/test/__snapshots__/demo.spec.js.snap
> feat(2.x/slider): add dual thumb mode for slider

- src/form/README.zh-CN.md
https://github.com/youzan/vant/issues/7168
> docs(Form): fix missing onSubmit validate-trigger

- src/calendar/components/Month.js
- src/calendar/index.js
- src/calendar/test/__snapshots__/demo.spec.js.snap
- src/calendar/test/__snapshots__/index.spec.js.snap
- src/calendar/utils.ts
https://github.com/youzan/vant/issues/7170
> fix(Calendar): incorrect height when using rem

- src/cell/README.zh-CN.md
type(ComponentName?)：docs: fix class name
> docs: fix class name

- src/calendar/index.js
- src/calendar/test/__snapshots__/demo.spec.js.snap
https://github.com/youzan/vant/issues/7198
> fix(Calendar): incorrect month title

- src/swipe/index.js
https://github.com/youzan/vant/issues/7204
> fix(Swipe): can't disable loop in some cases

- src/sidebar-item/index.js
- src/sidebar/README.md
- src/sidebar/README.zh-CN.md
- src/sidebar/test/__snapshots__/index.spec.js.snap
- src/sidebar/test/index.spec.js
new pull request [#7201](https://github.com/youzan/vant/issues/7201)
> feat(SidebarItem): add @sidebar-item title slot

- src/pagination/README.md
- src/pagination/README.zh-CN.md
- src/pagination/demo/index.vue
- src/pagination/index.js
- src/pagination/test/__snapshots__/demo.spec.js.snap
- src/pagination/test/__snapshots__/index.spec.js.snap
- src/pagination/test/index.spec.js
> feat(Pagination): pagination item custom render

- src/utils/functional.ts
https://github.com/youzan/vant/issues/7229#issuecomment-697239324
> fix(Button): incorrect ref in for

- src/tab/index.js
- src/tab/test/__snapshots__/index.spec.js.snap
- src/tab/test/index.spec.js
https://github.com/youzan/vant/issues/7236
> perf(Tab): skip rendering empty pane

- src/locale/README.zh-CN.md
> docs(Locale): add German to CN README

- src/form/README.md
- src/form/README.zh-CN.md
https://github.com/youzan/vant/issues/7243
> docs(Form): add validate-trigger detail

- types/swipe.d.ts
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
> types(Swipe): add prev, next method types

- src/field/index.js
- src/field/test/index.spec.js
https://github.com/youzan/vant/issues/7265
> fix(Field): incorrect maxlength slicing

- packages/vant-markdown-vetur/src/parser.ts
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
> fix(vant-markdown-vetur): fix Windows system build vetur problem (#7277)

- src/grid-item/index.less
https://github.com/youzan/vant/issues/3894
> fix(GridItem): failed to break word

- packages/vant-cli/site/desktop/components/Header.vue
This is my first time to make a PR for vant, Please to tell me if it has something wrong.
> fix(cli): Header.vue add key attr

- src/tab/README.zh-CN.md
- src/tabs/Title.js
- src/tabs/index.js
https://github.com/youzan/vant/issues/7326
> chore(Tab): remove unused prop and update desc

- src/calendar/README.md
- src/calendar/README.zh-CN.md
https://github.com/youzan/vant/issues/7320
> docs(Calendar): fix false typo

- src/cell/README.md
fix https://github.com/youzan/vant/issues/7344
> docs(Cell): fix demo translation

- src/tab/index.js
https://github.com/youzan/vant/issues/7353
> fix(Tabs): incorrect animation when content is empty

- src/calendar/index.js
- src/calendar/test/__snapshots__/demo.spec.js.snap
https://github.com/youzan/vant/issues/7329
> fix(Calendar): does not show current month with larger screen sizes

- src/image/index.js
https://github.com/youzan/vant/issues/7365
> feat(Image): skip render loading placeholder during ssr

- src/grid-item/index.js
https://github.com/youzan/vant/issues/7429
> fix(GridItem): should not emit deprecation warning

- types/index.d.ts
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
> fix(Types): fix ActionBar #7440

- src/tab/test/__snapshots__/insert.spec.js.snap
- src/tab/test/insert.spec.js
- src/tabs/index.js
https://github.com/youzan/vant/issues/7417
> fix(Tabs): should keep active value after insert item

- src/action-sheet/index.less
- src/action-sheet/index.tsx
- src/action-sheet/test/__snapshots__/index.spec.js.snap
> chore(ActionSheet): optimize dom

- src/sidebar-item/index.less
https://github.com/youzan/vant/issues/7455
> style(Sidebar): fix long number wrap

- src/image/README.md
- src/image/README.zh-CN.md
- src/image/index.js
- src/image/test/__snapshots__/index.spec.js.snap
- src/image/test/index.spec.js
https://github.com/youzan/vant/issues/7446
> feat(Image): add icon-prefix prop

- src/submit-bar/README.md
- src/submit-bar/README.zh-CN.md
- src/submit-bar/index.tsx
- src/submit-bar/test/__snapshots__/index.spec.js.snap
- src/submit-bar/test/index.spec.js
https://github.com/youzan/vant/issues/7441
> feat(SubmitBar): add button slot

- src/swipe-item/index.js
- src/swipe/test/index.spec.js
https://github.com/youzan/vant/issues/7399
> fix(Swipe): item should only rendered once

- src/style/var.less
- src/switch/index.less
https://github.com/youzan/vant/issues/7494
> style(Switch): remove unnecessary z-index

- src/area/README.md
- src/area/README.zh-CN.md
- src/datetime-picker/README.md
- src/datetime-picker/README.zh-CN.md
- src/picker/README.md
- src/picker/README.zh-CN.md
- src/sticky/README.md
- src/sticky/README.zh-CN.md
- src/tab/README.md
- src/tab/README.zh-CN.md
- src/utils/format/unit.ts
- src/utils/test/index.spec.js
https://github.com/youzan/vant/issues/7476
> feat(Sticky): offset-top support vh unit

- src/picker/index.js
- src/picker/test/__snapshots__/cascade.spec.js.snap
- src/picker/test/cascade.spec.js
https://github.com/youzan/vant/issues/7487
> fix(Picker): move to next option when default option is disabled

- src/picker/index.js
- src/picker/test/__snapshots__/cascade.spec.js.snap
- src/picker/test/cascade.spec.js
https://github.com/youzan/vant/issues/7487
> fix(Picker): should move to first option when all options are disabled

- src/nav-bar/README.md
- src/nav-bar/README.zh-CN.md
- src/nav-bar/index.js
- src/nav-bar/index.less
- src/nav-bar/test/__snapshots__/index.spec.js.snap
- src/nav-bar/test/index.spec.js
https://github.com/youzan/vant/issues/7503
> feat(NavBar): add safe-area-inset-top prop

- src/notice-bar/index.js
https://github.com/youzan/vant/issues/7187
> fix(NoticeBar): can't replay in iOS14

- src/nav-bar/index.less
> fix(NavBar): safe-area-inset-top css incorrect

- src/mixins/popup/index.js
- src/popup/README.md
- src/popup/README.zh-CN.md
- src/popup/index.js
> feat(Popup): add transition-appear prop

- src/dropdown-menu/README.zh-CN.md
https://github.com/youzan/vant/issues/7547
> docs(DropdownItem): update title slot description

- packages/vant-cli/src/common/index.ts
- packages/vant-cli/src/config/postcss.config.ts
https://github.com/youzan/vant/issues/7530
> feat(cli): postcss plugins can be array

- src/utils/dom/scroll.ts
https://github.com/youzan/vant/issues/3823
> fix(Sticky): not work in some cases

- src/swipe/index.js
https://github.com/youzan/vant/issues/7422
> fix(Swipe): leak when width has decimal

- src/calendar/components/Month.js
- src/calendar/index.js
- src/calendar/test/__snapshots__/demo.spec.js.snap
- src/calendar/test/__snapshots__/index.spec.js.snap
https://github.com/youzan/vant/issues/7512
> fix(Calendar): should not render all months on mounted

- src/calendar/index.js
https://github.com/youzan/vant/issues/7512
> fix(Calendar): month-show event triggered multiple times

- .github/workflows/sync.yml
sync 需要指定部署的分支为 `gh-pages`，否则 Gitee Pages 部署有问题。
> fix: add deploy branch `gh-pages`

- docs/markdown/quickstart.en-US.md
> docs: fix typo

- src/nav-bar/index.less
https://github.com/youzan/vant/issues/7606
> style(NavBar): z-index not work when border is hidden

- src/checkbox/demo/index.vue
> docs: update field

- src/button/index.less
https://github.com/youzan/vant/issues/7626
https://www.zhangxinxu.com/wordpress/2015/08/css-deep-understand-vertical-align-and-line-height/
> fix(Button): icon button vertical align

- src/checkbox-group/index.js
- src/checkbox/README.md
- src/checkbox/README.zh-CN.md
- src/checkbox/test/index.spec.js
- types/checkbox-group.d.ts
https://github.com/youzan/vant/issues/7608
> feat(CheckboxGroup): toggleAll support skipDisabled option

- src/datetime-picker/README.md
- src/datetime-picker/README.zh-CN.md
- src/datetime-picker/index.js
- src/datetime-picker/shared.js
- src/datetime-picker/test/__snapshots__/datetime-picker.spec.js.snap
- src/datetime-picker/test/datetime-picker.spec.js
https://github.com/youzan/vant/issues/7638
> feat(DatetimePicker): support picker slots

- src/popover/README.md
- src/popover/README.zh-CN.md
- src/popover/demo/index.vue
- src/popover/index.js
- src/popover/test/__snapshots__/index.spec.js.snap
- src/popover/test/index.spec.js
https://github.com/youzan/vant/issues/7618
> feat(Popover): add trigger prop

- src/uploader/index.js
> fix(uploader): change status is not valid

- docs/markdown/quickstart.en-US.md
- docs/markdown/quickstart.zh-CN.md
https://github.com/youzan/vant/issues/7672
> docs: update cdn link version

- src/stepper/index.js
https://github.com/youzan/vant/issues/7690
> fix(Stepper): fix mobile safari page scroll down issue

- src/popover/index.js
- src/popover/index.less
- src/popover/test/__snapshots__/index.spec.js.snap
https://github.com/youzan/vant/issues/7698
> fix(Popover): incorrect border position in wework

- packages/vant-cli/site/desktop/router.js
- packages/vant-markdown-loader/src/index.js
this request is in order to solve the problem in issues/7719
https://github.com/youzan/vant/issues/7719
> fix(@vant/cli): doc preview page cannot scroll to the correct anchor

- packages/vant-cli/src/common/constant.ts
https://github.com/youzan/vant/issues/7737
> fix(cli): failed to find root dir

- README.md
- README.zh-CN.md
- docs/markdown/home.en-US.md
- docs/markdown/home.zh-CN.md
我们维护的vant支付宝小程序版，已稳定运行一年左右，申请增加一个链接~
> docs: add vant-aliapp link

- packages/vant-eslint-config/index.js
> chore: 修复eslint 组件名称配置冲突

- packages/vant-stylelint-config/index.js
> chore(stylelint): deep error in vue3 compiler

- src/stepper/index.tsx
> feat(Stepper): add props 'showInput'

- src/index-bar/README.md
- src/index-bar/README.zh-CN.md
- src/index-bar/index.js
- src/index-bar/test/index.legacy.js
增加`ref`方法`scrollTo(index: string | number)`，方便用户初始化定位
issue #7695
> feat(IndexBar): add scrollTo method

- src/count-down/index.js
https://github.com/youzan/vant/issues/7807
> fix(CountDown): fix ssr memory leak

- src/form/README.md
- src/form/README.zh-CN.md
- src/form/index.js
- src/form/test/methods.spec.js
- types/form.d.ts
https://github.com/youzan/vant/issues/7769
> feat(Form): support valdiate multiple names

- src/stepper/README.md
- src/stepper/README.zh-CN.md
- src/stepper/index.js
- src/stepper/test/index.spec.js
https://github.com/youzan/vant/issues/7773
> feat(Stepper): add show-input prop

- src/stepper/index.js
- src/stepper/test/index.spec.js
https://github.com/youzan/vant/issues/7780
> fix(Stepper): change event emitted twice

- src/image-preview/test/__snapshots__/index.spec.js.snap
- src/notice-bar/test/__snapshots__/demo.spec.js.snap
- src/swipe-item/index.js
- src/swipe/index.js
- src/swipe/test/__snapshots__/demo.spec.js.snap
https://github.com/youzan/vant/issues/7750
> fix(Swipe): incorrect size during ssr

- src/image/index.js
https://github.com/youzan/vant/issues/7721
> fix(Image): mismatching warning during ssr

- src/datetime-picker/README.md
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
> fix(DatetimePicker): 英文文档翻译

- src/field/index.js
- src/form/README.md
- src/form/README.zh-CN.md
- src/form/index.js
1. 禁用表单所有输入框
2. 修改表单所有输入框的状态为只读
> feat(Form): add disabled and readonly prop

- src/search/index.js
> fix(Search): add update:modelValue emits

- src/circle/index.tsx
- src/circle/test/__snapshots__/demo.spec.js.snap
fix #7905
2.x has the same problem, I can submit another PR if necessary
> fix(Circle): the gradient color is incorrect

- src/utils/format/number.ts
- src/utils/test/index.spec.js
ref #7899
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
> enhanced number formatter

- src/cell/README.md
- src/cell/README.zh-CN.md
- src/cell/index.tsx
- src/cell/shared.ts
- src/cell/test/index.spec.js
https://github.com/youzan/vant/issues/7896
> feat(Cell): allow to disable clickable when using is-link

- src/toast/README.md
- src/toast/README.zh-CN.md
- src/toast/Toast.js
- src/toast/index.js
- types/toast.d.ts
https://github.com/youzan/vant/issues/7898
> feat(Toast): add overlayClass option

- src/cascader/README.md
- src/cascader/README.zh-CN.md
- src/cascader/demo/index.vue
- src/cascader/index.js
- src/cascader/test/__snapshots__/demo.spec.js.snap
https://github.com/youzan/vant/issues/7908
> feat(Cascader): add field-names prop

- packages/create-vant-cli-app/src/generator.ts
…#7904)
[window系统下fast-glob模块](https://github.com/mrmlnc/fast-glob#how-to-write-patterns-on-windows)
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
>  fix(create-vant-cli-app): window system failed to generate template (#7904)

- src/calendar/README.md
- src/calendar/README.zh-CN.md
- src/calendar/index.js
- types/calendar.d.ts
https://github.com/youzan/vant/issues/7943
> feat(Calendar): reset method support specified date

- src/dialog/Dialog.js
https://github.com/youzan/vant/issues/7963
> fix(Dialog): failed to render when toggling allowHtml

- src/image-preview/ImagePreviewItem.js
https://github.com/youzan/vant/issues/7946
> feat(ImagePreview): reset scale after swiping

- src/calendar/index.js
https://github.com/youzan/vant/issues/7978
> fix(Calendar): should expose scrollToDate method

- src/form/README.md
- src/form/README.zh-CN.md
https://github.com/youzan/vant/issues/7993
> docs(Form): fix Calendar v-model usage

- src/field/README.md
- src/field/README.zh-CN.md
https://github.com/youzan/vant/issues/7995
> docs(Field): fix model-value prop

- src/goods-action-icon/index.js
https://github.com/youzan/vant/issues/8032
> fix(GoodsActionIcon): info warning

- src/dropdown-menu/README.md
- src/dropdown-menu/README.zh-CN.md
https://github.com/youzan/vant/issues/8027
> docs(DropdownItem): fix v-model document

- src/toast/Toast.js
- src/toast/demo/index.vue
- src/toast/test/index.legacy.js
- src/toast/test/index.spec.js
https://github.com/youzan/vant/issues/8031
> fix(Toast): closeOnClickOverlay not work

- src/sticky/README.md
- src/sticky/README.zh-CN.md
- src/sticky/demo/index.vue
- src/sticky/index.less
- src/sticky/index.tsx
- src/sticky/test/__snapshots__/demo.spec.js.snap
- src/sticky/test/__snapshots__/index.spec.js.snap
- src/sticky/test/index.spec.js
#7531
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
> feat(Sticky): 添加吸底

- src/image-preview/ImagePreview.js
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
link issue: #8059
> fix(ImagePreview): 修复图片显示异常

- packages/vant-lazyload/src/util.js
> fix(util): remove unused []

- src/action-sheet/index.tsx
- src/action-sheet/test/__snapshots__/index.spec.js.snap
- src/action-sheet/test/index.spec.js
- src/nav-bar/test/index.spec.js
https://github.com/youzan/vant/issues/8083
> fix(ActionSheet): safe-area-inset-bottom not work

- src/dialog/README.md
- src/dialog/README.zh-CN.md
https://github.com/youzan/vant/issues/8101
> docs(Dialog): fix Promise typo

- src/step/index.js
- src/step/index.less
- src/steps/README.md
- src/steps/README.zh-CN.md
- src/steps/index.js
- src/steps/test/__snapshots__/index.spec.js.snap
- src/steps/test/index.spec.js
https://github.com/youzan/vant/issues/8093
> feat(Steps): add finish-icon prop

- src/utils/test/index.spec.ts
- src/utils/validate/email.ts
https://github.com/youzan/vant/issues/8211
> chore: remove legacy isEmail util

- src/picker/README.md
- src/picker/README.zh-CN.md
> docs(Picker): fix typo

- src/list/README.md
- src/list/README.zh-CN.md
https://github.com/youzan/vant/issues/7797
> docs(List): remove legacy sync modifier

- src/step/index.js
- src/steps/README.md
- src/steps/README.zh-CN.md
https://github.com/youzan/vant/issues/8093
> feat(Step): add finish-icon slot

- src/locale/README.md
- src/locale/README.zh-CN.md
- src/locale/lang/th-TH.ts
feat:
- Added Thai language pack
- Modified Locale README
todo:
Need to be merged into V3
> feat: add locale(th-TH)

- package.json
- tsconfig.declaration.json
- tsconfig.json
https://github.com/youzan/vant/issues/8249
> build: using cli to generate type declaration

- src/action-sheet/index.tsx
- src/action-sheet/test/__snapshots__/index.spec.js.snap
- src/action-sheet/test/index.spec.js
- src/mixins/popup/index.js
https://github.com/youzan/vant/issues/8186
> fix(ActionSheet): should not reopen when closed

- src/image-preview/ImagePreview.js
- src/image-preview/README.md
- src/image-preview/README.zh-CN.md
- src/image-preview/index.js
- types/image-preview.d.ts
https://github.com/youzan/vant/issues/8248
> feat(ImagePreview): add transition prop

- src/stepper/index.less
https://github.com/youzan/vant/issues/8200
> fix(Stepper): incorrect text color in iOS14 when disabled

- src/pull-refresh/README.md
- src/pull-refresh/README.zh-CN.md
- src/pull-refresh/index.js
https://github.com/youzan/vant/issues/8171
> feat(PullRefresh): add pull-distance prop

- src/swipe/index.tsx
- src/swipe/test/__snapshots__/index.spec.js.snap
- src/swipe/test/index.spec.js
https://github.com/youzan/vant/pull/8061#pullrequestreview-604840172
> fix(Swipe): should render dynamic swipe item correctly

- src/field/index.tsx
**修改内容**：`filed` 组件添加 `showClear` 计算属性默认返回值
> fix(Filed): filed 组件 showClear 计算属性添加默认返回值

- src/locale/README.md
- src/locale/README.zh-CN.md
- src/locale/lang/th-TH.ts
https://github.com/youzan/vant/pull/8247
> feat(Locale): add th-TH lang

- packages/vant-cli/src/common/css.ts
- packages/vant-cli/src/compiler/compile-js.ts
https://github.com/youzan/vant/issues/8300
> fix(cli): should not replace style entry import ext

- src/swipe/index.js
- src/swipe/test/__snapshots__/demo.spec.js.snap
- src/swipe/test/demo.spec.js
https://github.com/youzan/vant/issues/8299
> fix(Swipe): incorrect item width after scaled

- packages/vant-cli/README.md
- packages/vant-cli/docs/config.md
- packages/vant-cli/docs/desktop.md
- packages/vant-cli/package.json
- packages/vant-cli/site/desktop/App.vue
- packages/vant-cli/site/desktop/components/DemoPlayground.vue
- packages/vant-cli/site/desktop/components/index.vue
- packages/vant-cli/site/desktop/main.js
- packages/vant-cli/src/compiler/gen-site-desktop-shared.ts
- packages/vant-cli/src/config/webpack.base.ts
- packages/vant-cli/yarn.lock
- packages/vant-markdown-loader/src/extract-demo.js
- packages/vant-markdown-loader/src/index.js
- packages/vant-markdown-loader/src/md-parser.js
- packages/vant-markdown-loader/src/side-effect-tags.js
解决 vant-cli 生成的项目只能预览移动端组件的问题 https://github.com/youzan/vant/issues/8342
> vant-cli 支持 PC 组件预览

- packages/vant-eslint-config/index.js
- packages/vant-eslint-config/test/.eslintrc
- packages/vant-eslint-config/test/index.spec.js
- packages/vant-eslint-config/test/vue-tsx/app.tsx
- packages/vant-eslint-config/test/vue-tsx/index.tsx
- packages/vant-eslint-config/test/vue-tsx/main.ts
- packages/vant-eslint-config/test/vue-tsx/tsconfig.json
- packages/vant-eslint-config/test/vue/index.vue
- packages/vant-eslint-config/test/vue/main.js
fix the problem that eslint does not take effect in the `.tsx` file
> fix: eslint .tsx file failed

- packages/vant-markdown-loader/src/index.js
> perf:  improve markdown loader

- src/sticky/README.md
- src/sticky/README.zh-CN.md
> docs(Sticky):reorder documents

- src/composables/use-touch.ts
- test/event.ts
> fix: corrected horizontal slip judgment

- src/sticky/Sticky.tsx
https://github.com/youzan/vant/issues/8403
> fix(Sticky): Element not exist during SSR

- packages/vant-cli/src/compiler/compile-site.ts
> fix(vant-cli): fixed app cannot HMR when port is not 8080

- src/field/Field.tsx
- src/form/test/index.spec.tsx
https://github.com/youzan/vant/issues/8402
> fix(Field): should not reset validation after blured

- src/field/README.md
- src/field/README.zh-CN.md
https://github.com/youzan/vant/issues/8415
> docs(Field): add autocomplete prop

- src/dialog/Dialog.tsx
- src/dialog/README.md
- src/dialog/README.zh-CN.md
- src/dialog/index.tsx
- src/dialog/test/__snapshots__/funciton-call.spec.js.snap
- src/dialog/test/funciton-call.spec.js
https://github.com/youzan/vant/issues/8416
> feat(Dialog): allow to render JSX message

- src/datetime-picker/README.md
- src/datetime-picker/README.zh-CN.md
- src/datetime-picker/demo/index.vue
- src/datetime-picker/test/__snapshots__/demo.spec.ts.snap
https://github.com/youzan/vant/issues/8347
> docs(DatetimePicker): update demo

- packages/vant-markdown-vetur/src/formatter.ts
- packages/vant-markdown-vetur/src/index.ts
- src/calendar/README.md
- src/calendar/README.zh-CN.md
https://github.com/youzan/vant/issues/8219
> fix(markdown-vetur): extract component name from table title

- src/uploader/README.zh-CN.md
- src/uploader/utils.ts
https://github.com/youzan/vant/issues/8466
> docs(Uploader): add heic faq

- src/sticky/README.md
- src/sticky/README.zh-CN.md
- src/sticky/index.js
https://github.com/youzan/vant/issues/8476
> feat(Sticky): add change event

- src/popup/Popup.tsx
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
> fix: fix PopupCloseIconPosition type

- src/uploader/README.zh-CN.md
https://github.com/youzan/vant/issues/5804
> docs(Uploader): add exif faq

- src/field/Field.tsx
- src/search/Search.tsx
https://github.com/youzan/vant/issues/8484
> types(Search): missing some props in jsx

- src/steps/README.md
- src/steps/README.zh-CN.md
> docs(Steps): fix typo of basic usage

- src/contact-list/ContactList.tsx
- src/contact-list/test/__snapshots__/index.spec.ts.snap
- src/contact-list/test/index.spec.ts
1、windows环境下编译
TS2322: Type 'string' is not assignable to type 'Element'.
2、增加默认联系人标签文案单元测试
> fix(ContactList): fix TS type check error

- src/calendar/index.js
https://github.com/youzan/vant/issues/8509
> fix(Calendar): failed to update subtitle in some cases

- .eslintrc
- packages/vant-eslint-config/index.js
https://github.com/vuejs/vue-next/commit/80c868aefe089f0f1b98504801a53b49ca6d1d87
> chore: setup eslint for prohibited syntax

- src/share-sheet/index.js
https://github.com/youzan/vant/issues/8540
> fix(ShareSheet): duration prop not work

- src/form/demo/ValidateRules.vue
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
> fix(form): 修复 form demo 的 submit 事件拼写错误

- packages/vant-cli/package.json
- packages/vant-cli/yarn.lock
- yarn.lock
https://github.com/vuejs/jsx-next/commit/14adaa5f3a433cac60b796671db8db9c61dc8dff
> perf: bump jsx-pugin to reduce bundle size

- src/sku/Sku.js
- src/sku/demo/data.ts
- src/utils/index.ts
- remove `只有一个属性值时，默认选中`
- add `外部未传入选中的属性时，对没有加价的属性，默认选中第一个属性值`
> feat(sku): 商品属性默认选中交互逻辑修改

- package.json
https://github.com/youzan/vant/issues/8560#issuecomment-822123462
> chore: add jsdelivr entry config

- src/dropdown-menu/README.zh-CN.md
https://github.com/youzan/vant/issues/8565
> docs(DropdownMenu): add transform faq

- src/locale/lang/zh-HK.ts
- src/locale/lang/zh-TW.ts
https://github.com/youzan/vant/issues/8562
> fix(Calendar): incorrect weekdays locale

- packages/vant-cli/src/compiler/get-deps.ts
https://github.com/youzan/vant/issues/8554
> fix(cli):  ignore import types when analyzing deps

- docs/markdown/advanced-usage.en-US.md
- docs/markdown/advanced-usage.zh-CN.md
https://github.com/youzan/vant/issues/1181
> docs: add rem custom rootValue demo

- packages/vant-cli/site/desktop/components/index.vue
> feat(Cli)：windows系统禁用左右方向键快捷导航(vant2)

- src/tag/Tag.tsx
- src/tag/index.less
- src/tag/test/__snapshots__/demo.spec.ts.snap
- src/tag/test/__snapshots__/index.spec.ts.snap
- src/tag/test/index.spec.ts
https://github.com/youzan/vant/issues/8578
> fix(Tag): incorrect border color when using plain

- packages/vant-use/src/useScrollParent/index.ts
https://github.com/youzan/vant/issues/8594
> fix(@vant/use): useScrollParent ssr

- src/cascader/Cascader.tsx
- src/cascader/README.md
- src/cascader/README.zh-CN.md
- src/cascader/test/index.spec.ts
> feat(Cascader): click-tab event

- src/uploader/index.js
https://github.com/youzan/vant/issues/8610
> fix(Uploader): failed to render scoped class

- src/stepper/Stepper.tsx
- src/stepper/test/index.spec.ts
> fix(Stepper): 修复blur事件触发异常

- src/step/index.js
- src/steps/README.md
- src/steps/README.zh-CN.md
- src/steps/index.js
close https://github.com/youzan/vant/issues/8629
> feat(Steps): add icon-prefix prop

- src/composables/on-popup-reopen.ts
- src/popup/Popup.tsx
https://github.com/youzan/vant/issues/8634
> feat: add onPopupReopen

- src/tabs/Tabs.tsx
https://github.com/youzan/vant/issues/8634
> fix(Tabs): setLine when popup reopened

- src/swipe/Swipe.tsx
https://github.com/youzan/vant/issues/8634
> fix(Swipe): re-initialize when popup reopened

- src/dialog/README.zh-CN.md
- src/notify/README.zh-CN.md
- src/toast/README.zh-CN.md
https://github.com/youzan/vant/issues/8327
> docs: add tip for using global method in setup

- docs/markdown/quickstart.en-US.md
- docs/markdown/quickstart.zh-CN.md
https://github.com/youzan/vant/issues/8317
> docs: add more CDN services link

- docs/markdown/theme.en-US.md
- docs/markdown/theme.zh-CN.md
https://github.com/youzan/vant/issues/7986
> docs: add vite theme guide
