youzan/vant

packages/dialog/src/dialog.vue
1. 将dialog的基础z-index设置为2500
popup 2000+
dialog 2500+
toast 3000+
=> fix: 修复popup和dialog同时出现时，几率出现dialog被挡住的情况

packages/swipe/index.vue
hide indicators when one swipe page
=> hide indicators when one swipe page

packages/pull-refresh/index.vue
当下拉刷新元素的父级（非window）有可滚动元素的时候，刷新触发时机错误，下拉刷新不可用
=> [bug fix] PullRefreash: when $parents.$el scrollable, pull refreash trigger error

packages/vant-css/src/button.css, packages/vant-css/src/loading.css
问题页面: [https://www.youzanyun.com/zanui/vant/examples#/zh-CN/component/button](https://www.youzanyun.com/zanui/vant/examples#/zh-CN/component/button)
因为spinner有旋转的动画所以需要独立的layer~, 其他的不需要~
=> [optimize & bug fix] Button: 优化layer, 修复滚动时, gpu占用过高情况

docs/demos/views/tabbar.vue, docs/markdown/en-US/tabbar.md, docs/markdown/zh-CN/tabbar.md, packages/tabbar-item/index.vue
- Add slot-scope to TabbarItem to avoid checking `active` by item index
It allows to
```vue
<van-tabbar v-model="active">
<van-tabbar-item icon="shop">
<span>Custom</span>
</van-tabbar-item>
</van-tabbar>
```
instead of
```vue
<van-tabbar v-model="active">
<van-tabbar-item icon="shop">
<span>Custom</span>
</van-tabbar-item>
</van-tabbar>
```
=> [improvement] TabbarItem: add slot-scope to avoid check by index

package.json
- add "types" in "files" field of package.json to deliver types in npm package
=> [Improvement] package.json: include "types" in "files" field

packages/actionsheet/index.vue, packages/dialog/dialog.vue, packages/image-preview/image-preview.vue, packages/popup/index.vue, test/unit/specs/popup.spec.js
Fixes #466
- treat the empty string as true for boolean props
Enable the syntax suger `<van-popup lock-on-scroll />`, other than boolean binding `<van-popup :lock-on-scroll="true" />`;
=> [Improvement] Mixins: treat empty string as true for boolean props

docs/demos/views/coupon.vue
- fix exchange coupon demo
The coupon demo was not able to `exchange` due to immutable computed `coupons` attribute.
Also, creates random id to avoid duplicated keys warning.
=> [bug fix] Coupon docs: fix exchange coupons

packages/pull-refresh/index.vue
有时我们想要使用下拉刷新的同时支持水平滑动，此次提交避免在水平滑动的时候触发下拉刷新
=> [bug fix] PullRefresh: 水平滑动时避免触发下拉刷新

packages/stepper/index.vue, test/unit/specs/stepper.spec.js
Fixes #545
- stop firing events by watching the value prop
- fire events in the callbacks `onInput` and `onChange`
=> [bug fix] Stepper: not fire event on changing the value prop

packages/vant-css/src/cell.css
修复 
> ^0.12.0  版本更新内容
> CellGroup 左内边距移至 Cell 内 
导致 `.van-cell--required::before`  绝对定位 ` left ` 的错位。
=> [bugfix] Cell: fix required style

docs/demos/views/dialog.vue, docs/markdown/en-US/dialog.md, docs/markdown/zh-CN/dialog.md, packages/dialog/dialog.vue
Dialog 以组件形式调用时，可以异步关闭并让按钮进入loading状态。传入一个返回Pormise的函数的参数`async-confirm`。
`resolve`时可以关闭弹窗，`reject`时，去除loading，可重新点击确定按钮。
=> [improvement] Dialog: support async close

packages/dialog/dialog.vue
[new feature] Dialog: 给beforeClose添加回调参数 当done回调false时弹层不关闭，停止loading滚动
实际使用中需要用到beforeClose的情景下存在用户输入不符合规范必须停止下一步操作的情况。
不执行done按钮 loading会一直滚动，执行done弹层又会被关闭，只能通过`this.$refs.dialog.loading.confirm = false`来停止loading滚动，这显然是不科学的。
=> [new feature] Dialog: beforeClose Add callback parameters

packages/vant-css/src/actionsheet.css
* [bug fix] div: 修改css
- smallwei
=> fix:actionsheet的标题div没有值设置具体值导致rem布局不自适应

packages/mixins/popup/index.js
修复设置`getContainer`的`Popup`在父级组件销毁时DOM对象没有销毁
=> [bug fix]Fix `Popup` of setting `getContainer` when the parent component is destroyed and the DOM object is not destroyed

packages/tab/zh-CN.md
修正 van-tab 组件内说明文档的错别字“阙值、阀值”为阈值
=> [Doc] 修正文档错别字“阙值、阀值”为阈值

packages/pagination/en-US.md, packages/pagination/zh-CN.md
补全 van-pagination 组件文档中缺少的 total-items 属性和 page-count 属性的说明
=> [Doc] 补全 van-pagination 组件文档中缺少的 total-items 属性和 page-count 属性的说明

.gitignore, build/build-components.js, package.json, yarn.lock
- Import markdown parser util
- Add build task which parse `.md` file to `tags.json` and `attributes.json`
- Declare vetur config in package.json
=> [new feature]  Vue template language auto compeletion on vscode

build/build-components.js
- `build/build-components.js`中注释 `reomve unnecessary files`应该是`remove unnecessary files`
=> [typo] 修改了构建脚本里一处注释拼写错误

build/build-entry.js
Fixes #2228 
- `build/build-entry.js`中的 `buildDocsEntry` 函数中使用 `replace` 将 `windows` 系统中的 `\` 替换为 `/`
=> [bug fix] 修复在windows上构建docs-entry.js错误的问题

packages/sku/Sku.vue, packages/sku/components/SkuHeader.vue, packages/sku/demo/data.js, packages/sku/demo/index.vue, packages/sku/index.less, packages/sku/test/__snapshots__/demo.spec.js.snap, packages/sku/zh-CN.md
- [new feature] Sku: 支持隐藏售罄规格
- [compatibility] Sku: 规格图片兼容img_url字段
=> [new feature] Sku 支持隐藏售罄规格

packages/step/index.less
[bug fix] Steps 设置为 vertical 时 active-icon自定义图标样式错误
=> [bug fix] Steps 设置为 vertical 时 active-icon自定义图标样式错误

packages/swipe-cell/index.js, packages/swipe-cell/test/__snapshots__/index.spec.js.snap, packages/swipe-cell/test/index.spec.js
Changes in this pull request:
- fix typo https://github.com/youzan/vant/commit/d8d1aa6e829a89dd343a6e4fa526b01962927248#r32888966
- adjust `swipeLeaveTransition` method's parameter values https://github.com/youzan/vant/commit/c5474b21069694a66415c77f52eb313d4ca27ca8#r32888882
- add annotation
=> [improvement] SwipeCell: fix typo and adjust `swipeLeaveTransition` method's parameter values

packages/button/index.less
=> [bugfix] Button: 修改方形细边框按钮边框半径

packages/step/index.js
如果`step`是通过`v-for`动态生成，数据动态变更重新渲染下父`steps`只添加不减少，导致通过`avtive`计算的`status`出错
=> [bugfix] Step: step 销毁之前从父 steps 中移除

README.md
This PR fixes a link to wikipedia article about MIT License in english `README.md`.
=> [Doc] English link to MIT License

packages/utils/test/index.spec.js, packages/utils/validate/src.ts
Data URLs isn't prefixed with data:image
example:
'xdata:image/jpeg;base64,/9j/4AAQSkZ' return true in the test, but this is wrong
=> [bugfix] Utils: <is-src> data URLs should be prefixed with the data:image

packages/picker/index.js
将`picker`或基于`picker`的`datetime-picker`与`dropdown-menu`结合使用时，`toolbar`的最佳位置是底部，目前`toolbar`固定在顶部导致想更好的配合使用必须关闭`showToolbar`另外写自定义按钮，添加这个配置项可以解决这个问题
| 参数 | 说明 | 类型 | 默认值 | 版本 |
|------|------|------|------|------|
| columns | 对象数组，配置每一列显示的数据 | `Array` | `[]` | - |
| show-toolbar | 是否显示工具栏 | `Boolean` | `false` | - |
| title | 顶部栏标题 | `String` | `''` | - |
| toolbar-position | 工具栏的位置，可选值为 bottom | `String` | `top` | - |
| loading | 是否显示加载状态 | `Boolean` | `false` | - |
| value-key | 选项对象中，文字对应的 key | `String` | `text` | - |
| item-height | 选项高度 | `Number` | `44` | - |
| confirm-button-text | 确认按钮文字 | `String` | `确认` | - |
| cancel-button-text | 取消按钮文字 | `String` | `取消` | - |
| visible-item-count | 可见的选项个数 | `Number` | `5` | - |
| default-index | 单列选择器的默认选中项索引，<br>多列选择器请参考下方的 Columns 配置 | …
=> [new feature] 给`picker`添加一个配置项`toolbar-position`，决定`toolbar`位置

packages/popup/en-US.md, packages/popup/zh-CN.md
修改popup组件的描述文件
```
<van-botton type="primary" @click="showPopup">
展示弹出层
</van-button>
改为
<van-button type="primary" @click="showPopup">
展示弹出层
</van-button>
```
=> [Doc] Popup: fix typo

src/stepper/index.js
same problem with filed component, so I just copy the code(src/field/index.js line138~line143), and tested ok on wechat
ios Version: 12.3.2
wechat version: 7.0.4
=> [bugfix] Stepper: Hack for iOS12 page scroll

src/image-preview/ImagePreview.js, src/image-preview/README.md, src/image-preview/README.zh-CN.md, src/image-preview/demo/index.vue, src/image-preview/index.js
Our UI thought it is too slow when he swipe the images, so I tried to set some props to make it faster. 
Sadly, the component do not support such kind of props. So I make this pr, and hope it can be merged.
And the reason I did not use duration as prop name, is because it will affect overlay(src/mixins/popup/index.js line 174), so I use swipeDuration instead.
=> [new feature] ImagePreview: add swipe-duration prop

docs/site/utils/iframe-router.js
add error catch in changePath method
>The jump link in the development guide will cause the routing prompt "NavigationDuplicated" error message 
>eg: (jump) quickstart page ---> changelog page,the mobile page matching route  ↓↓↓
```js
const route = [
{
path: '*',
redirect: () => `/${Vue.prototype.$vantLang}/`
}
];
```
reference: https://github.com/vuejs/vue-router/issues/2881
=> docs: add router err catch

src/datetime-picker/DatePicker.js, src/datetime-picker/TimePicker.js, src/datetime-picker/shared.js, src/datetime-picker/test/time-picker.spec.js
https://github.com/youzan/vant/issues/4668
=> fix(DatetimePicker): should update value when range changed

src/dialog/index.less, src/style/var.less
Text blurring may occur on chrome when the length of dialog is odd.
=> fix(Dialog): improve width and avoid text blurry

src/style/var.less
Below error occurred when import less directly.
@toast-border-radius: @border-radius-md;
@toast-background-color: rgba(@text-color, .88);
^
Error evaluating function `rgba`: color functions take numbers as parameters
=> fix less import issue

src/picker/PickerColumn.js
=> fix(Picker): avoid Vue 2.6 event bubble issues by manually binding event

src/calendar/README.zh-CN.md, src/image-preview/ImagePreview.js, src/image-preview/test/index.spec.js
=> fix(ImagePreview): avoid Vue 2.6 event bubble issues

src/list/index.js
As I understand it, the `offset` property of list component is always a positive number. The `scrollerRect.top` should be greater than `placeholderRect.top` with the `direction` as `up` under normal conditions.
For example, if the placeholder has been scrolled out of viewport, `scrollerRect.top` will not be changed but `placeholderRect.top` might be `-1000` or even less. Then `placeholderRect.top  -  scrollerRect.top` will be always less than `offset`. It will cause `isReachEdge` being equivalent to `true` constantly.
=> fix(List): incorrect reaching edge condition

src/calendar/README.zh-CN.md
第一种方式我是打算:value="formateDate(date)"来展示，这样的话date默认要给一个new Date()而不是字符串''。
然后区间选择的时候默认值是数组[]，这样的话就需要再写一个formateRangeDate(date)来进行展示，这样显然是最好的。使用者不用再声明保存时间的变量。
第二种方式，就是拿到时间戳，格式化之后赋值给它本身。由于我不打算改动变量的类型，这样做并不好。
考虑到只是demo示例，我pull request最好是最小改动，就用了第三种方式。
value只是最为展示的字符串，而不是保存所选的时间或时间区间的变量。
=> docs: update calendar examples

src/calendar/components/Month.js, src/calendar/index.js, src/calendar/test/index.spec.js
https://github.com/youzan/vant/issues/5552
=> fix(Calendar): incorrect month title after auto scroll

types/toast.d.ts
Refer to the source code of toast component.
=> types(Toast): incorrect definition of 'setDefaultOptions' method

packages/vant-cli/site/desktop/components/Header.vue
vant-cli项目里，桌面网站样式在大屏显示器上会出现 **header左右留白的情况**，不够完美。如下图：
设置`.van-doc-header`下`.van-doc-row`宽度100%，以覆盖原样式：
```css
media (min-width: 1680px)
.van-doc-row {
width: 1680px;
margin: 0 auto;
}
```
=> fix(cli): change site header'width

src/notice-bar/index.js
If the component is in a hidden state, the obtained width is 0, so please extract the scrolling method, which is easy to call in the displayed state. In addition, when the text content is replaced, it can be scrolled if it exceeds the length originally, but it can also be scrolled if it does not exceed the length now. Therefore, you need to reset the relevant variables, please adopt!
=> Notice bar reset variable and scrollable method extraction

src/calendar/components/Month.js
当选择日期范围时，allow-same-day情形下选择同一天，color设置不生效
=> fix(Calendar): Invalid color setting

src/field/index.js, src/field/test/__snapshots__/index.spec.js.snap, src/field/test/index.spec.js
修复设置了 maxlength 同时 value 为 undefined 或者 null 时，组件报错无法渲染的问题
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
=> feat(Field): fix render error when value is null or undefined

src/field/index.less
https://github.com/youzan/vant/issues/6452
=> style(Field): default label align should be left

src/field/README.md, src/field/README.zh-CN.md, src/form/README.md, src/form/README.zh-CN.md, src/style/var.less
在 iOS 上，14px 的汉字实际宽度为 14.2645833333px，因此 6em 宽度无法保证一行能显示六个汉字
=> fix(Field): can't display six characters in iOS

src/number-keyboard/index.less
https://github.com/youzan/vant/issues/6823
=> fix(NumberKeyboard): incorrect key height on legacy safari

src/action-sheet/README.md, src/action-sheet/README.zh-CN.md, src/action-sheet/index.tsx, src/action-sheet/test/index.spec.js
使用 `ActionSheet` 的时候如果设置了 `title` ，此时会默认显示关闭图标，以便于自定义面板时关闭窗口。
但是当设置 `title` 的同时，还设置了 `cancel-text` ，关闭图标就有些多余了，所以想添加一个显示隐藏关闭图标的 prop。
不知这样是否可行呢？
=> feat(ActionSheet): add closeable prop

src/style/var.less, src/tabbar-item/index.less
This adds the possibility of changing the background colour of the tab bar items. 
With this change it's possible to achieve the following:
=> feat(TabbarItem): add @tabbar-item-active-background-color less var

packages/vant-cli/package.json, packages/vant-cli/yarn.lock
使用@vant/cli迁移项目运行`yarn test`命令提示如下错误
```bash
FAIL  src/price-label/test/index.spec.js
● Test suite failed to run
/Users/chenzihao/Desktop/playground/vis-ui/vant-cli-migrate/src/price-label/components/price-label.vue: don't know how to turn this value into a node
at valueToNode (../../vant/packages/vant-cli/node_modules/@babel/types/lib/converters/valueToNode.js:87:9)
at Object.valueToNode (../../vant/packages/vant-cli/node_modules/@babel/types/lib/converters/valueToNode.js:81:58)
at Object.exit (../../vant/packages/vant-cli/node_modules/istanbul-lib-instrument/dist/visitor.js:638:30)
at PluginPass.exit (../../vant/packages/vant-cli/node_modules/babel-plugin-istanbul/lib/index.js:158:38)
at newFn (../../vant/packages/vant-cli/node_modules/@jest/transform/node_modules/@babel/traverse/lib/vis …
```
=> chore(@vant/cli): 修复vue-jest生成sourcemap导致jest生成覆盖率失败

src/field/index.less
https://github.com/youzan/vant/issues/7194
The text color become invisible when using `background-color: transparent;` and `-webkit-text-fill-color: currentColor;` in iOS 14
=> fix(Field): incorrect disabled color in iOS 14

packages/vant-cli/src/common/index.ts, packages/vant-cli/src/config/webpack.package.ts, packages/vant-cli/src/config/webpack.site.dev.ts, packages/vant-cli/src/config/webpack.site.prd.ts, packages/vant-cli/yarn.lock
@vant/cli中，使用者无法修改cli的webpackConfig，导致使用者如果想要修改原有loader的默认行为或者是参数，都无法做到；比如场景：需要过滤Markdown文件的frontMeta头信息，但是没有办法修改@vant/markdown-loader的options，所以导致`enableMetaData`属性是无效的，所以如果在markdown文件中添加yaml头，就会导致文档展示中出现这个yaml头信息（不是预期内的结果）。
修改cli中获取webpackConfig的函数，使用webpackBaseConfig作为入参，允许使用者从webpack.config.js文件导出一个函数修改baseConfig。
=> feat(@vant/cli): suport modify internal webpack config

src/field/index.less
https://github.com/youzan/vant/issues/7343
=> fix(Field): incorrect label length when label-align is right

src/button/README.md
Just a quick fix for the docs in English
=> docs(Button): Fixed grammar in button readme.

src/nav-bar/index.js, src/nav-bar/test/__snapshots__/index.spec.js.snap
- The navbar can render an empty `<div class="van-nav-bar__left"></div>` which shows a pointer cursor when hovered on desktop. 
- This may also be picked up by screen readers and any other assistive technologies. 
- The blank left/right elements can also be clicked so if you parse `:left-text="leftTextMethod" @click-left="someMethod"` and `leftTextMethod` returns null/false; `someMethod` can get invoked when clicking the white space.
=> fix(NavBar): Component renders blank left/right.

src/action-sheet/index.less
After testing, the `ActionSheet` component has no height in the pop-up content under the iOS 10 version. This patch can fix this problem.
=> fix(ActionSheet): The height of the flex container is lost under ios 10.

src/number-keyboard/index.js
=> fix(number-keyboard): fix hide-on-click-outside prop not working

src/calendar/components/Month.js
#7837
Calendar的month组件有一个getDate方法 [getDate](https://github.com/youzan/vant/blob/dev/src/calendar/components/Month.js#L68)，我的理解是该方法应该是用来获取`props`中的`date`，但是代码中却写成了`props.data`
将`props.data`改成`props.date`
=> fix(Calendar): change props.data to props.date to fix getDate bug #7837

src/number-keyboard/README.md, src/number-keyboard/README.zh-CN.md, src/number-keyboard/demo/index.vue, src/number-keyboard/index.js, src/number-keyboard/test/__snapshots__/demo.spec.js.snap, src/number-keyboard/test/index.spec.js
#7831 
通过 `number-random` 属性可以随机排序数字键盘，常用于安全等级较高的场景
Use `number-random` prop to random sort number keypads.
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
=> feat(NumberKeyboard): add number random prop

src/area/index.js
已测试
当前版本省市区选择器只能使用6位地区码，对于东莞市等只有2、4级地址的区域不太友好。
以及有些同学使用的8位，10位或12位的4级以上地区码，如果想用省市区选择器还得另行处理地区码.
于是对`getIndex`函数加一层判断。当`type`为"county"时不做地区码长度限制，就能更好的兼容各种地区码了。
=> feat(Area):适配8位,10位,12位等地区码,及处理东莞市等没有第三级区域码的问题

src/tabs/index.js
修改文件: tabs/index.js
问题：文档里tabs 组件可设置name 属性  取值类型为 string 或 number 然而当 我们去设置 v-model为0 运用 vfor 去渲染时，某一项的 name 也存在为 0 的，一切操作都没啥毛病， 呢么在渲染时 v-model的值会被改成 1，这显然不是我们想要的结果。
原因： 在赋值呢里 运用的是短路运算   props.active||currentName  如果我设置的默认值是数字类型的0  呢么就直接忽略，然后赋 currentName 了(虽然我的active 是已经赋值的了)
解决方案： 在开始赋值时 进行判断一下 active 为 0 的情况。
=> fix(Tabs): incorrect active tab when active is zero

packages/vant-markdown-loader/src/extract-demo.js, packages/vant-markdown-loader/src/index.js
=> fix(vant-markdown-loader): 修复 demo 组件和其他组件重名导致的渲染异常

src/mixins/touch.js, test/event.ts
Closes #8386
修复在 ios safari 中「手势返回」误触「右滑操作」的 bug
=> fix: corrected horizontal slip judgment

packages/vant-markdown-loader/src/highlight.js
更换新的api，原api项目启动一直循环警告
https://github.com/highlightjs/highlight.js/issues/2277
Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
Deprecated as of 10.7.0. Please use highlight(code, options) instead.
=> fix(vant-markdown-loader): 更换新的api

src/notify/function-call.tsx
启动之后ts类型校验失败，报错信息Type 'Timeout' is not assignable to type 'number'
可以运行但是控制台一直有报错信息。所以修改为window.setTimeout(Notify.clear, options.duration);
=> fix(Notify): Type 'Timeout' is not assignable to type 'number'

src/grid/README.md, src/grid/README.zh-CN.md
修复 Grid 文档和示例保持一致
否则在使用的时候造成困惑，误以为是整个row是处于横排。
=> docs: update parameters are consistent with the sample

packages/vant-markdown-vetur/src/formatter.ts, packages/vant-markdown-vetur/src/type.ts, packages/vant-markdown-vetur/src/utils.ts, packages/vant-markdown-vetur/src/vetur.ts
说明
**可选值用空格隔开**
示例
| 参数         | 说明 | 类型     | 默认值    | 可选值              |
| ------------ | ---- | -------- | --------- | ------------------- |
| type `1.0.0` | 类型 | _string_ | `primary` | `default` `primary`  `success` |
结果
```json
{
"u-button/type": {
"type": "string",
"description": "类型, 默认值: `primary`",
"options": ["default", "primary", "success"]
}
}
```
=> feat(markdown-vetur): 支持生成 attributes.json 的 options 属性

src/datetime-picker/DatePicker.js, src/datetime-picker/TimePicker.js, src/datetime-picker/test/date-picker.spec.js, src/datetime-picker/test/time-picker.spec.js
#7253 
- 原因应该是在`updateColumnValue`方法里存在`nextTick`，导致如果在`updateInnerValue`里面直接去取的话取的index会不正确
- DatePicker和TimePicker都存在相同问题
- 原先的测试用例没有覆盖到类似的情况
=> fix(DatetimePicker): fixed incorrect value when dynamic set min/max

src/calendar/Calendar.tsx, src/calendar/utils.ts
修复当直接点击确认按钮时，获取的时间与点击日期后确认时间不一致的问题
**复现步骤：**
使用一下demo，并打印onConfirm中获取的date
```vue
<van-calendar
type='range'
:poppable="false"
@confirm='onConfirm'
/>
```
- 当我们直接点击，confirm时候，我们将收到带有时间的Date
- 当我们点击同样选中的日期范围后，点击confirm，我们将收到不带时间的Date
**原因**
是由于在`Calendar.tsx`中我们对`props.minDate`、`props.maxDate`、`getInitialDate()`中用到的`now`没有进行时间处理导致的
而在`CalendarMonth.tsx`中我们对`computed days`使用到的Date是进行过处理的，关注`line 211`
**影响**
- 不大不小的问题，这会导致不同的行为（是否手动点击日期）点击确认后获取的日期不一致：）
- 单测过不了~由于vant3单测直接对Date进行比较，而不是像vant2一样format之后再进行比较，所以部分单测会一直failed
=> fix(Calendar): initial date incorrect

src/datetime-picker/DatePicker.js, src/datetime-picker/TimePicker.js, src/datetime-picker/test/date-picker.spec.js, src/datetime-picker/test/time-picker.spec.js
- 修复: 动态调整 `max-date` `max-hour` `max-minute` props 显示时间为最小日期时间问题（期望：超出最大边界选中最大时间）
- 删除: `set max-hour & max-minute smaller than current then emit correct value` 单测，和调整后逻辑有冲突
- 当动态设置maxDate，且改变后maxDate < currentDate时，currentDate会自动变成最小日期时间
- 我们在watch这些属性的时候，如果这些属性改变，则触发`updateInnerValue`动态调整
- 而`updateInnerValue`主要做的事情是：得到`picker.getIndexs()`通过index，触发`picker.setValues`调整columns的选中值
- 在`Picker`中，默认如果超出边界，indexs会返回第一个索引，即为0，我们期望是 `index = columns.length - 1`
- 所以在watch的时候，如果判断当前的改变的currentDate >= maxValue，则直接设置currentDate = maxValue，绕过`updateInnerValue`
=> fix(DatetimePicker): fix change max-* emit incorrect value

src/datetime-picker/DatePicker.js, src/datetime-picker/test/date-picker.spec.js
#8907 #8924 
当同时使用`(min|max)Date` & `filter` 时，超出边界后再`formatValue`中仅简单返回`(min|max)Date`，导致value不正确
在界定是否越界的同时还需二次判断 `(min|max)Date`是否超越 `filter`定义的边界
由于在 `originColumns` 计算属性中，有用到 `filter`，因此可以利用这一特性进行处理
`updateInnerValue` 方法中我们最终需要对 `value` 进行 `formatValue` 处理，所以调整 `formatValue` 相对比较合理
- 兼容：type: `year-month` `month-day` `time`
- 兼容：`columns-order` prop
=> fix(DatetimePicker): fix incorrect value when using filter

src/list/List.tsx, src/list/test/index.spec.js
https://github.com/youzan/vant/issues/9017
=> fix(List): should emit load event when parent tab is activated

src/field/Field.tsx, src/field/README.md, src/field/README.zh-CN.md, src/field/test/index.spec.js
https://github.com/youzan/vant/issues/9318
=> feat(Field): add id prop

package.json, packages/vant-popperjs/package.json, packages/vant-use/package.json, pnpm-lock.yaml
fix(build): use rimraf
rm -rf does not work for windows so we add a lib `rimraf` and replace `rm -rf` to `rimraf`
=> fix(build): use rimraf

packages/vant-cli/src/common/constant.ts
https://github.com/youzan/vant/discussions/9838
https://github.com/nodejs/node/issues/31710
=> fix(cli): absolute file paths don't work on Windows

src/datetime-picker/TimePicker.js
fix(DatetimePicker)：修复没有v-model的时候，DatetimePicker confirm value出错的问题
=> fix(DatetimePicker): fix incorrect confirm value when v-model is not used

src/swipe/index.less
=> fix(Swipe): `overflow` lose efficacy in  iOS safari

src/calendar/components/Month.js, src/calendar/index.js
fix(Calendar): date is empty when `poppable = fasle` in dialog (#9845)
=> fix(Calendar): date is empty when `poppable = fasle` in dialog (#9845)

packages/vant/src/swipe/index.less
fix(Swipe): `overflow` lose efficacy in  iOS safari (#9933)
=> fix(Swipe): `overflow` lose efficacy in  iOS safari (#9933)

packages/vant/package.json
https://github.com/youzan/vant/issues/9980
=> fix: missing es、lib dir in exports field

.github/dependabot.yml
dependabot not support pnpm yet.
https://github.com/dependabot/dependabot-core/issues/1736
=> build: remove dependabot

packages/vant-cli/site/index.html, packages/vant-cli/site/mobile.html, packages/vant-cli/src/config/vite.site.ts
`description` is used by the HTML ejs template, so it needs to be written explicitly here to avoid ejs error:
```
description is not defined
```
=> fix(@vant/cli): explicitly write the description field

packages/vant/src/composables/use-height.ts
使用到useHeight的组件，在IOS（高概率）和安卓（低概率）可能获取到错误的高度，设计到的组件有NavBar, TabBar中的usePlaceholder hooks。
=> fix: useHeight may get the wrong height

packages/vant-cli/src/common/constant.ts, packages/vant-cli/src/compiler/compile-site.ts, packages/vant-cli/src/compiler/gen-package-style.ts, packages/vant-cli/src/compiler/gen-site-desktop-shared.ts, packages/vant-cli/src/compiler/gen-site-mobile-shared.ts, packages/vant-cli/src/config/vite.site.ts
gen-site-mobile-shared/gen-site-desktop-shared 采用vite plugin虚拟文件的方式生成, gen-package-style site模式下同样使用虚拟文件, build模式下不走plugin
=> fix(vant-cli): pnpm compatibility

packages/vant/src/icon/index.less
=> fix(Icon): use image URL as name prop, remove white space under image

packages/vant-use/src/useRelation/useChildren.ts, packages/vant/src/tab/test/__snapshots__/insert.spec.tsx.snap
close https://github.com/youzan/vant/issues/10230
=> fix(@vant/use): missing subTree when flattening vnodes

packages/vant/src/swipe-cell/SwipeCell.tsx
#10304 
看起来应该是 `getClickHandler` 中的 `event.stopPropagation()` 没有被触发。
=> fix(SwipeCell): cell should stopPropagation when lockClick is true

packages/vant/src/dialog/README.zh-CN.md
- docs(Dialog)：fix README.zh-CN.md case error, modify JSX.ELement to JSX.Element。
=> docs: fix README.zh-CN.md case error, modify JSX.ELement to JSX.Element。

packages/vant/src/calendar/index.less, packages/vant/src/dialog/index.less, packages/vant/src/picker/index.less
=> fix(Calendar, Picker): Fix calendar and picker's title color in dark mode

packages/vant/src/tabs/Tabs.tsx
#10292
issue中复现代码放在 `vant3` 的 `tab/demo/index.vue` 中可百分百复现
应该是 map render 时没有为 `TabTitle` 添加唯一 `key` 导致的
=> fix(Tab): add key when render TabsTitle

packages/vant/src/datetime-picker/DatePicker.tsx
#10110
关联历史issue: #7253
历史issue是为了解决动态改变最大值最小值时，currentDate不准确问题，加了层 `nextTick`，当时 `maxDate` 没加这层。
本次调整让 `minDate` `maxDate` 的行为保持一致
=> fix(DatetimePicker): fix minDate && maxDate wacher

packages/vant/src/calendar/Calendar.tsx
=> fix(calendar): scrollToDate method is invalid

packages/vant/src/calendar/CalendarDay.tsx, packages/vant/src/calendar/README.md, packages/vant/src/calendar/README.zh-CN.md, packages/vant/src/calendar/index.less, packages/vant/src/calendar/test/__snapshots__/index.spec.ts.snap, packages/vant/src/calendar/test/__snapshots__/prop.spec.ts.snap, packages/vant/src/calendar/var.less
#10440
- CalendarDay 默认 marginBottom = 10px
- 每月最后一周日期默认 marginBottom = 0
- APP上的携程、美团等样式均有10px间距，然而网页版的均无marginBottom，个人审美感觉加上后会美观点
=> feat(CalendarDay): add default margin-bottom

README.md, README.zh-CN.md, packages/vant/docs/markdown/home.en-US.md, packages/vant/docs/markdown/home.zh-CN.md
Try Vant in the Playground. Currently only Vant 3+ is supported
Details https://sfc-playground-vant.vercel.app/
https://github.com/zhixiaoqiang/sfc-playground-vant
=> doc: update readme add sfc-playground-vant to Community Ecosystem

packages/vant/src/rate/Rate.tsx, packages/vant/src/rate/test/index.spec.ts
=> perf(Rate): Precisely selected

packages/vant/src/form/README.md, packages/vant/src/form/README.zh-CN.md
the docs is behind the [demo code](https://github.com/youzan/vant/blob/004f6426229fdb2916fae64101d1e04be201aa76/packages/vant/src/form/demo/ValidateRules.vue), so update the readme to keep it constitent with the demo code.
https://github.com/youzan/vant/blob/004f6426229fdb2916fae64101d1e04be201aa76/packages/vant/src/form/demo/ValidateRules.vue#L38-L56
=> docs(vant): keep the doc consistent with the demo code

packages/vant/src/picker/Picker.tsx, packages/vant/src/picker/test/index.spec.tsx
**问题定位：**
当我在使用picker组件时，我希望columns数据改变后，修改columns-field-names后能够正确的展示，如下：
初始时结果展示正确
当点击change按钮后，我希望修改了columns后，同时修改columns-field-names的text,能够正确展示如下图serverName字段，但实际是不可以的，现阶段是展示一个对象。
**希望得到得结果：**
直接修改columns-field-names的text属性，能够正确的展示结果
**上述案例地址：**
https://codesandbox.io/s/jovial-morning-rbjcni?file=/src/App.vue:393-472
**解决方案：**
关键代码
const columnsFieldNames = reactive({
// compatible with valueKey prop
text: props.valueKey || 'text',
values: 'values',
children: 'children',
});
extend(columnsFieldNames, props.columnsFieldNames);
watch(
() => props.columnsFieldNames,
(value) => {
if (value) extend(columnsFieldNames, value);
},
{
deep: true,
}
);
const {
text: textKey,
values: valuesKey,
children: childrenKey,
} = toRefs(columnsFieldNames);
**测试用例：**
test('columns-field-names …
=> fix(Picker): picker columnsfieldnames responsiveness

docs/markdown/changelog.en-US.md, vant.config.js
v2 网站的搜索依赖 docsearch 在 jsdelivr 上的 CDN 资源，而近期 jsdelivr 在很多地方无法访问，阻塞了文档加载。
相比来说，文档搜索功能的必要性没有那么强，因此暂时下线文档搜索。
close https://github.com/youzan/vant/issues/10631
=> docs: remove search from v2 site

packages/vant/vant.config.mjs
v3 版本的文档搜索功能一直存在问题，docsearch的爬虫无法爬取到有效的内容，尝试了一下未能解决，因此暂时下线文档搜索入口，后续有时间再处理。
close https://github.com/youzan/vant/issues/10308
=> docs: remove search from v3 site

packages/vant/src/calendar/Calendar.tsx
fix: #10628 
lazyRender模式下隐藏展开calendar时重新渲染下months，lazyRender时元素较少，渲染成本应该不大
=> fix(Calender): failed to render months after changing maxDate or minDate

packages/vant-cli/docs/config.md, packages/vant-cli/docs/config.zh-CN.md, packages/vant-cli/src/compiler/compile-bundles.ts, packages/vant-cli/src/config/vite.package.ts
Allow to config bundle options, and removed minified es and cjs output from default options, because they are never used.
=> feat(cli): add build.bundleOptions config

packages/vant-markdown-vetur/package.json
Hi, Vant team,
thanks for the great project!
I try to clone the repo and run it on local.
Will fail on `pnpm i` step in prepare script of `vant-markdown-vetur` package.
I think just because `typescript` dep is not in package.json cause. so I added it and rerun `pnpm i` then fixed the problem.
=> chore: add `typescript` dev deps to `vant-markdown-vetur`

packages/vant-cli/src/config/vite.package.ts
https://github.com/vitejs/vite/pull/8090
https://github.com/vant-ui/vant/issues/10878
=> fix(@vant/cli): should replace NODE_ENV in vite v3

packages/vant/src/popup/Popup.tsx
If the Popup content area does not have a cancel button, It is necessary to tell the device where to cancel the Popup.
=> feat(Popup): add role and tabindex for a11y

packages/vant/src/popup/index.less
1.目前的垂直居中方式会导致内容宽度自适应时，最大只能达到50%的宽度
2.同时也导致了Toast会有同样的问题，并且--van-toast-max-width失效
=> fix(Popup&Toast): invalid adaptive width

packages/vant/src/calendar/Calendar.tsx
https://github.com/vant-ui/vant/issues/10970
=> fix: calendar range type defaultDate when set allowSameDay

packages/vant/src/calendar/Calendar.tsx, packages/vant/src/calendar/test/prop.spec.ts
close https://github.com/vant-ui/vant/issues/10970
=> fix(Calendar): allow default date to be maxDate when enable allowSameDay

packages/vant-cli/site/desktop/components/Content.vue
packages/vant-cli/site/desktop/components/Content.vue
站点卡片添加 overflow:auto，避免缩小浏览器窗口时，介绍页核心团队卡片内头像列表超出。
=> fix: 卡片添加 overflow:auto

src/utils/index.ts
For example, when calling `get({}, 'button.small')`, it expects to return an empty string, but return a function (`''.small` is a native function, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/small).
=> fix(utils): avoid getting unexpected value

packages/vant/package.json
Vant 4 on longer publish less files, so the sideEffects of less is not used any more.
=> chore: remove *.less from sideEffects

packages/vant/src/image-preview/ImagePreviewItem.tsx, packages/vant/src/notice-bar/NoticeBar.tsx, packages/vant/src/notify/function-call.tsx, packages/vant/src/stepper/Stepper.tsx, packages/vant/src/swipe/Swipe.tsx, packages/vant/src/toast/Toast.tsx
https://github.com/youzan/vant/issues/11066
example:
```ts
// let startTimer: NodeJS.Timeout;
let startTimer: ReturnType<typeof setTimeout>;
```
=> perf: improve the type of setTimeout

packages/vant/src/image-preview/ImagePreview.tsx, packages/vant/src/image-preview/ImagePreviewItem.tsx, packages/vant/src/image-preview/README.md, packages/vant/src/image-preview/README.zh-CN.md, packages/vant/src/image-preview/demo/index.vue, packages/vant/src/image-preview/index.less, packages/vant/src/image-preview/test/index.spec.ts
This slot can custom image part content, example video.
Now, I want to preview the video in full screen, but ImagePreview cannot do it
=> feat(ImagePreview): add preview image slot

src/calendar/index.js
Bug cause: 该bug出现的原因是之前在修复 #9845 issue时的判断逻辑缺失。
该问题主要是为了解决平铺模式下Calendar在popup弹出层中使用时导致大量日期空白的问题。
但是对于非平铺模式（即弹出模式），在Calendar的mounted生命周期，组件并未渲染到DOM中，所以此时监听外层popup的opened event时去执行onScroll方法，会去获取 ref 名为body的元素并执行 getScrollTop 方法，此时因为还未渲染到DOM中，获取到的元素是undefined，执行了 getScrollTop 方法便导致了报错。
=> fix(Calendar): throw an error that scrollTop in undefined when poppable = true in popup(#10360)(#10614)

packages/vant/src/coupon/index.less
https://github.com/youzan/vant/issues/11149
The reason for this issue is that the parent element does not have `relative`, which makes the positioning of the checkbox dependent on the `van-tabs`
before
after
=> style(Coupon): fix the style of coupon checkbox

packages/vant/src/date-picker/test/index.spec.ts, packages/vant/src/picker/Picker.tsx, packages/vant/src/picker/test/cascade.spec.ts, packages/vant/src/picker/test/index.spec.tsx, packages/vant/src/time-picker/test/index.spec.tsx
close https://github.com/youzan/vant/issues/11186
=> fix(Picker): correct v-model when emit confirm event

packages/vant/src/action-sheet/index.less
fix: https://github.com/youzan/vant/issues/11211
`ActionSheet`在苹果手机上只有`close`图标时（title设置一个空格），无法关闭。
该问题在2.x及3.x都存在（2.x稍后修复）。
=> fix(ActionSheet): fix that close is invalid without title

packages/vant/src/lazyload/vue-lazyload/lazy-image.js
in vue 3.x h is not function. this.$slots.default is  a function.
[vue 3.x refs render-function-api-change](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0008-render-function-api-change.md)
[vue 3.x docs h](https://cn.vuejs.org/api/render-function.html#h)
- reappear
- test
```vue
// vant/packages/vant/src/lazyload/demo/index.vue
<script lang="ts">
import Lazyload from '..';
if (window.app) {
window.app.use(Lazyload, { lazyComponent: true, lazyImage: true });
}
</script>
<template>
<demo-block :title="t('basicUsage')">
<lazy-image v-for="img in imageList" :key="img" :src="img">
</lazy-image>
</demo-block>
</teamplate>
```
=> fix(lazyload): lazy-image h is not a function

src/sku/README.md, src/sku/README.zh-CN.md, src/sku/Sku.js, src/sku/components/SkuRowPropItem.js, src/sku/demo/data.ts
支持属性选择的禁用状态，通过 `text_status` 表示：0 - 禁用，1 - 启用。
=> feat(sku): 支持属性的禁用状态

src/checkbox/demo/index.vue, src/checkbox/test/__snapshots__/demo.spec.js.snap, src/form/README.zh-CN.md, src/rate/README.zh-CN.md, src/search/index.less
- 修复 `.van-cell` 下 `&__left-icon` 类名选择器错误问题，导致search中icon未能作用到 `color: @search-left-icon-color`
- 2.x 文档checkbox自定义形状类型组件文案错误
- 2.x 文档部分非法字符移除
=> fix(2.x): search component @search-left-icon-color invalid & docs update

packages/vant/src/date-picker/test/index.spec.ts, packages/vant/src/picker/Picker.tsx, packages/vant/src/picker/README.md, packages/vant/src/picker/README.zh-CN.md, packages/vant/src/picker/test/index.spec.tsx, packages/vant/src/picker/types.ts, packages/vant/src/time-picker/test/index.spec.tsx
https://github.com/youzan/vant/issues/11326
几个不确定点：
1. 这个属性是否确定要加？
2. 凡是用到picker的都会受影响吧（需要大佬check下）？
3. 该参数是增加到`getEventParams`还是单独给`confirm`加（目前是只给confirm加了）？
=> feat(Picker): add selectedIndexes to the confirm event

packages/vant/src/form/Form.tsx
This prevents Form submit values like 
```javascript
{
foo: 'bar',
undefined: 'foo'
}
```
=> fix(Form): filter no name field's value

packages/vant/src/picker/index.less
=> fix(Picker): picker loading color in dark theme

packages/vant/src/locale/lang/ru-RU.ts
_First of all, thanks for your work. Vant is amazing, please keep going 👍_ 
**PR**: Fixed typo of "Calendar" in `ru-RU` locale.
=> fix(Locale): ru-RU: fix typo of "Calendar"

packages/vant/src/image-preview/ImagePreview.tsx, packages/vant/src/image-preview/README.md, packages/vant/src/image-preview/README.zh-CN.md
fix(image-preview)：fix image-preview README、supplement teleport
demo使用的是index+1，文档是index，可能会有点误导
文档上有teleport这个参数，但实际并没有定义
=> fix(image-preview)：fix image-preview README、supplement teleport

packages/vant-cli/site/common/style/highlight.less, packages/vant/src/config-provider/README.md, packages/vant/src/config-provider/README.zh-CN.md
```css
:root {
--van-button-primary-background: red;
}
```
css like above not working, we need to raise the priority like below
```css
:root:root {
--van-button-primary-background: red;
}
```
reference: [antd-mobile](https://mobile.ant.design/guide/theming)
=> docs(ConfigProvider): fix how to override basic css variables

packages/create-vant-cli-app/generators/vue3/.gitignore.tpl
Directory `site-dist` rather than `site` was excluded from git.
Relative issue: https://github.com/youzan/vant/issues/11477
=> fix(create-vant-cli-app): fix .gitignore template

packages/vant/src/config-provider/README.md, packages/vant/src/config-provider/README.zh-CN.md, packages/vant/src/number-keyboard/README.md, packages/vant/src/number-keyboard/README.zh-CN.md, packages/vant/src/number-keyboard/index.less, packages/vant/src/picker/README.md, packages/vant/src/picker/README.zh-CN.md, packages/vant/src/picker/index.less, packages/vant/src/style/css-variables.less
- The confirm button of the picker and number-keyboard components is not the primary color.
- Original color is not obvious in dark mode.
- `--van-link-color` is not in use except for these two components,  so if I delete it  from `css-variables.less`,  will it be break-change?
=> fix: change some colors to primary color

packages/create-vant-cli-app/src/generator.ts
最新版本的create-vant-cli-app 执行`npx create-vant-cli-app` 得到的是一个空文件夹
替换enquirer的时候 choices的配置写错了
=> fix(create-vant-cli-app): prompt config bug

src/popover/index.js
close #8564 
故障原因：
`<transition>`对元素使用animation导致位置更新不及时。
由于不知道哪个元素的animation会导致位置popover位置变化，所以这里监听的window的animationend事件。
要使popover的位置根据animation实时跟进似乎没有很好的api可用，唯一能想到的是animationstart事件后用settimeout隔一段时间更新，直到animationend或animationcancel事件触发，不过这应该由上游依赖`popover.js`解决。
=> fix(popover): location update

packages/vant/src/popover/index.less
Checkout the official [Popover Placement](https://vant-ui.github.io/vant/#/en-US/popover#placement) demo, you can find that the arrow position of `*-start/end` placements has a different offset.
=> fix(Popover): fix arrow position of `*-start/end` placements

packages/vant/src/dialog/README.zh-CN.md
发现了一处文档代码示例错误
问题描述：Vant4.x 里的 Dialog 组件文档，“常见问题”的[第二个示例](http://vant-contrib.gitee.io/vant/#/zh-CN/dialog#zai-beforerouteleave-li-diao-yong-dialog-wu-fa-zhan-shi)代码是有问题的。对此进行了代码示例调整。
=> fix(docs): ✏️ 修复 Dialog 组件文档示例的问题

packages/vant/src/text-ellipsis/TextEllipsis.tsx
We should allow `TextEllipsis` to inherit attrs, such as custom styles.
```html
<van-text-ellipsis context="..." style="font-size: 20px;" />
```
=> fix(TextEllipsis): failed to inherit attrs

packages/vant/src/swipe/README.md, packages/vant/src/swipe/README.zh-CN.md, packages/vant/src/swipe/Swipe.tsx, packages/vant/src/swipe/test/index.spec.jsx
有些时候我并不关心 Swipe 播放到哪一个位置，但是如果用户自己去操作轮播时，我关心他朝着哪个方向滑动或者用户期望看到第几页(为此我不得不添加 onChange 事件去记录播放位置)。
我对 Swipe 组件中 onDragStart 和 onDragEnd 两个事件添加了 index 参数。
=> feat(Swipe): add index when trigger onDragStart or onDragEnd

packages/vant/src/dropdown-item/DropdownItem.tsx, packages/vant/src/dropdown-menu/DropdownMenu.tsx, packages/vant/src/dropdown-menu/types.ts
close: https://github.com/youzan/vant/issues/11637
改的时候发现，如果通过**外部按钮**控制菜单项下拉是否显示时，会和`close-on-click-outside=true`的情况下冲突。
https://github.com/youzan/vant/blob/c63fee0d13b360b2ea911e8a1a707648e8239a1e/packages/vant/src/dropdown-menu/DropdownMenu.tsx#L78
=> fix(DropdownMenu): fix dropdown-item position when expanded by default

packages/vant-cli/src/compiler/get-deps.ts
编译 `mjs` 或者 `cjs` 时，  替换 vue 文件导入出现重复后缀
=> fix(@vant/cli): replace vue file import causing duplicate suffixes

packages/vant/src/image-preview/ImagePreviewItem.tsx
当一个长竖图被放大时，如果宽度没有填满屏幕，就很难上下滑动，是因为上下滑动的时候，左右只移动了一点就触发了这个判断(moveX > maxMoveX.value || moveX < -maxMoveX.value) &&!isImageMoved)，所以导致无法滑动
=> fix(ImagePreview): long vertical images sliding up and down

packages/vant/src/field/Field.tsx
an input with readonly attr can focus & blur, but it only emit focus event right now.
=> fix(Field): should emit blur event when readonly

packages/vant/docs/markdown/release-note-v4.zh-CN.md
I found a documentation error when looking at the "release-note-v4" section in Vant@4.
The links of date-picker and time-picker are the same.
=> docs: fix link about date-picker in release-note-v4

packages/vant/src/watermark/README.md, packages/vant/src/watermark/README.zh-CN.md, packages/vant/src/watermark/Watermark.tsx, packages/vant/src/watermark/test/index.spec.ts
Keep the `text-color` prop name of the Watermark component consistent with other components.
=> chore(Watermark): rename font-color to text-color

packages/vant/src/swipe/Swipe.tsx
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
https://github.com/zhousg/vant/tree/demo
```ts
const { width } = useWindowSize();
```
```html
<demo-block :title="t('title5')">
<van-swipe
:width="(300 / 375) * width"
:loop="false"
indicator-color="white"
>
<van-swipe-item>1</van-swipe-item> …
```
=> fix(Swipe): should resize after props.width/height changed

packages/vant/src/watermark/Watermark.tsx, packages/vant/src/watermark/test/__snapshots__/index.spec.ts.snap
fix #11761
这个问题是blob MIME多写了charset=utf-8，Safari没认可。
还增加了xlink命名空间，看MDN Safari12以下都不支持直接写href。
=> fix(watermark): add xlink namespace and fix blob MIME type

packages/vant/src/sticky/Sticky.tsx, packages/vant/src/sticky/test/__snapshots__/index.spec.tsx.snap, packages/vant/src/sticky/test/index.spec.tsx, packages/vant/src/swipe/Swipe.tsx
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
https://vant-contrib.gitee.io/vant/mobile.html#/zh-CN/tab
横屏后
监听 resize 且是 fixed 状态后，还原 Sticky 组件容器样式切换至非 fixed 状态，让其再次获取原始大小重新设置容器尺寸，切换回 fixed 状态。
=> fix(Sticky): resize or orientationchange wrapper no reset width and height

.github/workflows/deploy-v4-site.yml
Fix the following warning:
Ref: 
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- https://github.com/JamesIves/github-pages-deploy-action/issues/1241
=> chore(CI): fix the set-output deprecation warning when deploy website

packages/vant/src/field/Field.tsx
Fix Filed Bug #11831
将 label 事件 stopPropagation() 改成 preventDefault()，使点击事件的对象不受影响，并主动聚焦input
=> fix(Filed): onclick label execute twice

packages/vant/src/signature/README.md, packages/vant/src/signature/README.zh-CN.md, packages/vant/src/signature/Signature.tsx, packages/vant/src/signature/index.less
1. 设置导出类型为jpg时依然还是png格式，只能设置jpeg不方便。
2. 当导出jpg时默认会将透明alpha像素转换为黑色，导致导出全黑图片。
3. 清晰度很低签名锯齿状很明显
1. 修复`type`设置为jpg不生效的错误，`canvas.toDataURL` 仅支持jpeg全称写法。
2. 增加一个背景色`backgroundColor`属性方便快速便捷的设置底色。
3. 通过物理像素分辨率与CSS 像素分辨率的像素比进行canvas放大缩小提高绘制清晰度，拟补显示器之间的差异。
_组件默认提供导出高清不缩小版，如果有特殊需求可以通过第二参数canvas自行处理导出图片_
| Before(锯齿) | Now(不缩小版) | Scaled(缩小版) |
| ------ | --- | ------ |
| <img src="https://github.com/youzan/vant/assets/48879481/e6396584-f7bd-4858-90c5-671837d635ed" width="344" height="202"> | <img src="https://github.com/youzan/vant/assets/48879481/e66d5af7-a7af-4598-b48a-d29013a7c599" width="344" height="202"> | <img src="https://github.com/youzan/vant/assets/48879481/5f566a2d-3b98-4e84-94fd-04f76dd4a9da" width="344" height="202"> |
| 7kb | 12kb | 7kb |
Changelog(CN) | Changelog(EN) | Related …
=> feat(signature): Enhance signature clarity by devicePixelRatio

packages/vant/src/dialog/index.less
圆角边框问题如图所示：
修复后 `theme="default"` 如图所示：
修复后 `theme="round-button"` 如图所示：
=> fix(Dialog): fix the rounded corners of shadow when button is clicked

packages/vant/src/area/Area.tsx
areaProps 包含 allow-html 和 show-toolbar 实际没有使用
=> fix(Area): areaProps omit allow-html show-toolbar

packages/vant/src/slider/Slider.tsx, packages/vant/src/slider/test/index.spec.ts
拖动按钮到最左边后，点击 slider 的其它地方会触发 change 事件。再点击 slider 的最左边，这个时候不会触发 change 事件。
=> fix(Slider): should update startValue when the slider is clicked

packages/vant/src/popover/Popover.tsx, packages/vant/src/popover/README.md, packages/vant/src/popover/README.zh-CN.md, packages/vant/src/popover/demo/index.vue, packages/vant/src/popover/index.less, packages/vant/src/popover/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/popover/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/popover/test/__snapshots__/index.spec.tsx.snap, packages/vant/src/popover/test/index.spec.tsx, packages/vant/src/popover/types.ts, packages/vant/src/utils/constant.ts
Implement an edit menu effect similar to iOS.
=> feat(Popover): add actions-direction prop

packages/vant-cli/site/mobile/components/DemoBlock.vue
官方文档，刷新页面的时候移动端页面根据 `hash` 进行定位
=> feat(VantCli): mobile page refreshes are located based on the hash

packages/vant/src/dropdown-menu/DropdownMenu.tsx, packages/vant/src/dropdown-menu/README.md, packages/vant/src/dropdown-menu/README.zh-CN.md, packages/vant/src/dropdown-menu/types.ts
当存在多个自定义的 `DropdownItem` 时，需要定义多个 `ref` 实例对应，想着是否可以增加一个组件级别的 `close` 方法，方便操作
=> feat(DropdownMenu): add close method

packages/vant/src/slider/README.md, packages/vant/src/slider/README.zh-CN.md, packages/vant/src/slider/Slider.tsx, packages/vant/src/slider/test/index.spec.ts
=> feat(Slider): button slot add dragging param

packages/vant-use/package.json
related discussion #11981 
[reference](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#package-json-exports-imports-and-self-referencing)
=> build(@vant/use): add types exports

packages/vant/src/floating-panel/FloatingPanel.tsx, packages/vant/src/floating-panel/README.md, packages/vant/src/floating-panel/README.zh-CN.md, packages/vant/src/floating-panel/demo/index.vue
=> fix(FloatingPanel): remove passive event warning

packages/vant/src/button/README.md, packages/vant/src/button/README.zh-CN.md, packages/vant/src/button/demo/index.vue, packages/vant/src/button/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/button/test/__snapshots__/demo.spec.ts.snap
之前遇到过这个动画按钮需求，发现vant的示例里没有，就以为做不到；后来自己还专门封装了一个动画按钮。
最近又遇到给H5做公告栏的需求，发现notice-bar组件里有一个`垂直滚动`的demo，实际上按这个做法，就可以完全实现当时的动画按钮的功能。
所以，这个PR就在Button组件的文档 加上了 `动画按钮` 的demo。
防止也有人看不到这个能力。
=> chore(Button): add animation button demo

packages/vant/src/rate/index.less
touchmove 的触发对象和 touchstart 是一致的。这意味着在 half icon 上触发移动后，即使在 half icon 外移动，事件也是在它上触发的。这会产生一个问题，因为现在监听的父元素的 touchmove 事件，当 half icon 从文档中移除后，touchmove 将无法冒泡到父元素，表现为断触。
before:
after this PR:
=> fix(Rate): should change value when half icon is touchmoved

packages/vant/src/rolling-text/README.md, packages/vant/src/rolling-text/README.zh-CN.md, packages/vant/src/rolling-text/RollingText.tsx, packages/vant/src/rolling-text/demo/index.vue
Considering the naming conventions in vant, I have renamed the `text-array` prop to `text-list`, which can be consistent with other APIs such as `area-list`, `index-list`, `disabled-list`.
=> chore(RollingText): rename text-array prop to text-list

.gitee/ISSUE_TEMPLATE.md
Gitee now supports reading templates from the .github directory, so we can remove the Gitee issue template.
- Ref: https://help.gitee.com/issue/templates#%E6%A8%A1%E6%9D%BF%E9%80%89%E6%8B%A9%E5%99%A8%E9%85%8D%E7%BD%AEconfigyml
=> chore: remove gitee issue template

packages/vant/src/uploader/Uploader.tsx, packages/vant/src/uploader/UploaderPreviewItem.tsx, packages/vant/src/uploader/types.ts, packages/vant/test/dom.ts
Render objectUrl to avoid perf issue, base64 image may slow down the Wechat WebView.
- https://github.com/youzan/vant/issues/12048
=> fix(Uploader): render objectUrl to avoid perf issue

packages/vant/src/toast/README.md, packages/vant/src/toast/README.zh-CN.md, packages/vant/src/toast/index.ts
Add `ToastWrapperInstance` type export.
=> types(Toast): add `ToastWrapperInstance` export.

packages/vant-cli/package.json, packages/vant-cli/src/compiler/vite-plugin-md.ts, packages/vant-cli/src/config/vite.site.ts, pnpm-lock.yaml
Remove the `vite-plugin-md` dependency, as it introduced a lot of breaking changes and is no longer suitable for Vant.
=> refactor(cli): rewrite vite-plugin-md

packages/vant-cli/src/compiler/vite-plugin-md.ts
https://github.com/youzan/vant/issues/12186
=> fix(cli): should escape curly brackets in markdown

packages/vant/src/dialog/Dialog.tsx
重新修改了在二次封装传入<slot /> 占位时，slots.default永远存在，即使不传入插槽内容也不会渲染message
=> fix(Dialog): improve slot exit judgment

packages/vant-use/src/index.ts, packages/vant-use/src/useRaf/index.ts, packages/vant-use/src/utils.ts, packages/vant/docs/markdown/use-raf.en-US.md, packages/vant/docs/markdown/use-raf.zh-CN.md, packages/vant/docs/markdown/vant-use-intro.en-US.md, packages/vant/docs/markdown/vant-use-intro.zh-CN.md, packages/vant/vant.config.mjs
Do you like this way to cancelRaf ?
we don't need to import { cancelRaf } from 'vant-use'
it's very common to use this way in `vueuse`
=> feat(vant-use): add useRaf

packages/vant/vant.config.mjs
貌似文档的菜单导航，只有 `BackTop` 没有按字母排序，给修改下。
=> docs: improve the menu position of back-top

packages/vant-auto-import-resolver/src/index.ts
Fix:
```text
Type '{ type: string; resolve: (name: string) => { name: string; from: string; sideEffects: string; }; }' is not assignable to type 'ComponentResolver | ComponentResolver[]'.
Type '{ type: string; resolve: (name: string) => { name: string; from: string; sideEffects: string; }; }' is not assignable to type 'ComponentResolverObject'.
Types of property 'type' are incompatible.
Type 'string' is not assignable to type '"component" | "directive"'.ts(2322)
```
=> fix(auto-import-resolver): type mismatch in TS projects

packages/vant/.eslintignore, packages/vant/.eslintrc
我看了看，eslint 更新到比较新的版本，需要更改忽略的写法
https://github.com/eslint/eslint/issues/16264
=> fix(eslint): eslint 不再支持.eslintignore文件, 需要在.eslintrc配置ignorePatterns

packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md
* feat(Cell): add css vars to customize font size of the cell value by @inottn in https://github.com/youzan/vant/pull/12260
* feat(ConfigProvider): supplement the type declaration of ConfigProviderThemeVars by @xieyezi in https://github.com/youzan/vant/pull/12264
* feat(NavBar): add leftDisabled and rightDisabled prop by @m-xlsea in https://github.com/youzan/vant/pull/12258
* fix(ConfigProvider): ConfigProviderThemeVars `fontSizeXs` hump by @xieyezi in https://github.com/youzan/vant/pull/12267
* docs(changelog): vant@4.6.7 by @chenjiahan in https://github.com/youzan/vant/pull/12249
* docs(NavBar): add disable button demo …
=> docs(changelog): vant@4.6.8

packages/vant/src/calendar/Calendar.tsx, packages/vant/src/calendar/CalendarDay.tsx, packages/vant/src/calendar/CalendarMonth.tsx, packages/vant/src/calendar/README.md, packages/vant/src/calendar/README.zh-CN.md, packages/vant/src/calendar/test/index.spec.ts
解决问题: 日历组件新增 click-disabled-date 事件
相关issue: https://github.com/youzan/vant/issues/12247
=> feat(Calendar): add click-disabled-date event

src/picker/PickerColumn.js, src/picker/test/index.spec.js
When the mouse scrolls once, the element will be scrolled several times, the operation is not synchronized. As shown in the image below, when the mouse wheel scrolls once, the list will scroll several items instead of one.
[https://i.ibb.co/ZMKRr4H/demo-2x.gif](https://i.ibb.co/ZMKRr4H/demo-2x.gif)
[https://lllomh.com/staticen/img/demo-2x.gif](https://lllomh.com/staticen/img/demo-2x.gif)
<br/><br/>
A fix has been made for this issue, please check.
Here's the fixed motion picture, the Item only scrolls once per mouse roll.
[https://i.ibb.co/RT3QmGk/demo-2x-fix.gif](https://i.ibb.co/RT3QmGk/demo-2x-fix.gif)
[https://lllomh.com/staticen/img/demo-2x-fix.gif](https://lllomh.com/staticen/img/demo-2x-fix.gif)
=>  fix(Picker): Fix the issue when scrolling the mouse wheel once but the element scrolls multiple times

packages/vant/src/swipe-cell/README.md, packages/vant/src/swipe-cell/README.zh-CN.md, packages/vant/src/swipe-cell/SwipeCell.tsx, packages/vant/src/swipe-cell/demo/index.vue, packages/vant/src/swipe-cell/test/index.spec.js, packages/vant/src/utils/interceptor.ts, packages/vant/src/utils/test/interceptor.spec.ts
SwipeCell在beforeClose执行期间，可能触发clickAway从而再次执行了onClick导致触发close事件的执行。
解决方案：
通过添加变量标记正在执行beforeClose中，对后续的onClick事件进行忽略，直到beforeClose返回确定值
关联issue：#12308
=> feat(SwipeCell): Fix triggered close by clickAway when in running beforeClose

packages/vant/src/signature/Signature.tsx
Signature 组件在设置了背景色以后，如果未签名时直接点击submit，输出的image中会自带背景颜色的base64值，而实际并未进行签名，这样会导致判断是否已经签名不准确。
=> fix(Signature): fix checking if canvas is empty when backgoundColor is set

.npmrc, package.json
No longer need `resolution-mode=highest` config
=> chore: bump pnpm v8.8.0

packages/vant/src/uploader/Uploader.tsx, packages/vant/src/uploader/demo/index.vue
fix(Uploader): multiple reupload only choose one & cancel chose problem，close #12358
=> fix(Uploader): multiple reupload only choose one & cancel chose problem

package.json, packages/vant/src/image-preview/ImagePreview.tsx, packages/vant/src/image-preview/ImagePreviewItem.tsx, packages/vant/src/image-preview/README.md, packages/vant/src/image-preview/README.zh-CN.md, packages/vant/src/image-preview/function-call.tsx, packages/vant/src/image-preview/types.ts, pnpm-lock.yaml
feat:添加了enableDoubleScale属性（默认为true），true为允许双击缩放，蒙层关闭会有250ms延迟；false为不允许双击缩放，蒙层关闭没有延迟。
解决问题：提供用户双向选择是否开启双击缩放，关闭会导致预留双击时间以致于关闭延迟，解决有些延迟效果不好而且双击缩放需求不大的场景。
=> feat: add enableDoubleScale attribute

packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md
* feat(Icon): add font-family css var by @JeremyFan in https://github.com/youzan/vant/pull/12354
*feat(ImagePreview): add doubleScale option by @coderXMin in https://github.com/youzan/vant/pull/12360
* fix(Icons): compatible with the browser range of Vant 2 by @chenjiahan in https://github.com/youzan/vant/pull/12356
* fix(Uploader): multiple reupload only choose one & cancel chose problem by @zhousg in https://github.com/youzan/vant/pull/12359
* docs(changelog): vant@4.7.1 by @chenjiahan in https://github.com/youzan/vant/pull/12346
* refactor(Signature): avoid setting the canvas width and height in the next tick by …
=> docs(changelog): vant@4.7.2

packages/vant/src/contact-edit/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/contact-edit/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/field/Field.tsx, packages/vant/src/field/test/index.spec.js, packages/vant/src/form/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/form/test/__snapshots__/demo.spec.ts.snap
当使用field时填写rules，如果rule 中required为true，希望看见label带星号。而不是专门再写required 为true的prop。</br>
这次改动参考 element-plus form item中label是否带星号的计算。
=> chore(Field): required label css will active when rules contain required

packages/vant/src/tab/README.md, packages/vant/src/tab/README.zh-CN.md
=> docs(Tab): keep docs and example the same

packages/vant-area-data/package.json
When a project's tsconfig contains `"moduleResolution": "bundler"`, typescript error show 
`There are types at 'xxxxxx/node_modules/@vant/area-data/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@vant/area-data' library may need to update its package.json or typing.`
After adding `types` in package.json, the error is fixed. Besides, if `moduleResolution` is `node` it works well.
=> fix(@vant/area-data): add exports types

packages/vant/src/search/Search.tsx, packages/vant/src/search/index.less
=> fix(Search): fix search style when has error message

.github/workflows/sync-gitee.yml
fork vant 仓库后, 每天都有很多该CI失败的邮件提醒, 添加if, 非原始仓库不跑该CI.
=> chore: forked repo, skip CI running

packages/vant/src/signature/Signature.tsx, packages/vant/src/signature/index.ts, packages/vant/src/signature/test/index.spec.ts, packages/vant/src/signature/types.ts
=> feat(Signature): expose resize method

packages/vant/src/checkbox/Checker.tsx, packages/vant/src/checkbox/README.md, packages/vant/src/checkbox/README.zh-CN.md, packages/vant/src/checkbox/test/index.spec.ts, packages/vant/src/radio/README.md, packages/vant/src/radio/README.zh-CN.md
=> feat(Checker): add checked and disabled params to the default slot

packages/vant/src/highlight/Highlight.tsx, packages/vant/src/highlight/README.md, packages/vant/src/highlight/README.zh-CN.md, packages/vant/src/highlight/demo/index.vue, packages/vant/src/highlight/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/highlight/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/highlight/test/index.spec.ts
1. 解决匹配的内容为空 以及 内容重叠时的高亮展示。
2. 拓展了下功能，可以分别设置高亮和非高亮元素的类名和标签。
3. 避免使用 innerHTML 可能出现的潜在问题。
=> refactor(Highlight): refactor implementation & increase functionality

packages/vant/src/col/Col.tsx, packages/vant/src/col/README.md, packages/vant/src/col/README.zh-CN.md, packages/vant/src/col/demo/index.vue, packages/vant/src/col/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/col/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/col/test/index.spec.tsx, packages/vant/src/row/Row.tsx
The `gutter` property of the `Row` component supports setting both horizontal and vertical spacing as an array.
close #12431
=> feat(Row): gutter support vertical space

packages/vant/src/text-ellipsis/TextEllipsis.tsx
1. Recalculation is only needed when the window width changes.
2. By reusing the windowWidth variable, we can avoid registering event listeners multiple times.
=> perf(TextEllipsis): reuse windowWidth to avoid repeat calculations

packages/vant/src/tree-select/README.md, packages/vant/src/tree-select/README.zh-CN.md
=> docs(TreeSelect): correct variable names

packages/vant/src/text-ellipsis/README.md, packages/vant/src/text-ellipsis/README.zh-CN.md, packages/vant/src/text-ellipsis/TextEllipsis.tsx, packages/vant/src/text-ellipsis/index.ts, packages/vant/src/text-ellipsis/types.ts
https://github.com/youzan/vant/issues/12470
=> feat(TextEllipsis): add the toggle instance method

packages/vant/src/tree-select/README.md, packages/vant/src/tree-select/README.zh-CN.md
TreeSelect 组件的多选模式，activeId 变量修改为 activeIds
resolve #12474
=> docs(TreeSelect): fix incorrect activeIds variable name

packages/vant/src/text-ellipsis/types.ts
相关 pr: https://github.com/youzan/vant/pull/12472
=> fix(TextEllipsis): fix missing param for toggle

packages/vant-cli/package.json, packages/vant-compat/package.json, packages/vant-use/package.json, packages/vant/package.json, packages/vant/tsconfig.json, pnpm-lock.yaml, tsconfig.json
- Bump Vue 3.4.0-beta.4 to improve Vue SFC compiler performance, see: https://github.com/vuejs/core/releases/tag/v3.4.0-beta.4
- Fix global JSX type, see: https://vuejs.org/guide/extras/render-function.html#jsx-type-inference
=> chore(deps): bump Vue 3.4.0-beta.4

packages/vant/src/image-preview/ImagePreviewItem.tsx, packages/vant/src/image-preview/test/index.spec.ts, packages/vant/src/image-preview/test/shared.ts
Fix the two issues below:
1. When `double-scale` is set to false, `close-on-click-overlay` will not work.
2. When `close-on-click-overlay` is set to false, double-click zooming will not work.
=> fix(ImagePreview): double-scale and close-on-click-overlay may not work in certain scenarios

.github/ISSUE_TEMPLATE/template-1-bug-report-vant.en-US.yml, .github/ISSUE_TEMPLATE/template-3-bug-report-vant.zh-CN.yml, .github/workflows/issue-labeled.yml
Update codesandbox URL, use devbox for easier debugging.
=> chore(workflow): update codesandbox URL

packages/vant-cli/package.json, packages/vant-compat/package.json, packages/vant-use/package.json, packages/vant/package.json, pnpm-lock.yaml
Rsbuild v0.2.10 provides better support for Vue v3.4.0, see: https://github.com/web-infra-dev/rsbuild/releases/tag/v0.2.10
=> chore(deps): bump Rsbuild and Vue

packages/vant/src/floating-bubble/test/index.spec.ts
Reduce the running time of the test by approximately 1 seconds.
=> test(FloatingBubble): reduce test run time

packages/vant/src/dropdown-item/DropdownItem.tsx, packages/vant/src/dropdown-menu/DropdownMenu.tsx, packages/vant/src/dropdown-menu/README.md, packages/vant/src/dropdown-menu/README.zh-CN.md, packages/vant/src/dropdown-menu/test/index.spec.tsx, packages/vant/src/utils/dom.ts, packages/vant/src/utils/test/index.spec.ts
=> feat(DropdownMenu): add auto-locate prop

packages/vant/src/lazyload/README.md, packages/vant/src/lazyload/README.zh-CN.md
=> docs(Lazyload): fix preLoad type error and spelling mistakes

packages/vant/src/notify/Notify.tsx, packages/vant/src/notify/README.md, packages/vant/src/notify/README.zh-CN.md
=> feat(Notify): add teleport prop

packages/vant/src/image-preview/ImagePreview.tsx, packages/vant/src/image-preview/ImagePreviewItem.tsx, packages/vant/src/image-preview/README.md, packages/vant/src/image-preview/README.zh-CN.md, packages/vant/src/image-preview/demo/index.vue, packages/vant/src/image-preview/test/index.spec.ts, packages/vant/src/image-preview/types.ts
resolve #12448
When the elements in the slot have their own click interaction logic, such as video elements, the click should not close the preview.
=> feat(ImagePreview): add close-on-click-image prop

packages/vant/src/tabs/index.less
=> fix(Tabs): van-border-radius-sm to van-radius-sm

packages/vant/src/toast/README.md, packages/vant/src/toast/README.zh-CN.md, packages/vant/src/toast/Toast.tsx, packages/vant/src/toast/types.ts
=> feat(Toast): add z-index prop

packages/vant/docs/markdown/quickstart.en-US.md, packages/vant/docs/markdown/quickstart.zh-CN.md
=> docs: improve quickstart tips

.github/workflows/deploy-v4-site.yml
在 fork 的项目中同步 Vant 代码后会执行 deploy-v4-site，然后运行失败
我想它不应该被执行
=> chore: avoid workflow running on forked repo

packages/vant/src/number-keyboard/NumberKeyboard.tsx, packages/vant/src/number-keyboard/test/__snapshots__/index.spec.ts.snap, packages/vant/src/number-keyboard/test/index.spec.ts
=> fix(NumberKeyboard): render delete slot correctly when theme is custom

packages/vant/docs/markdown/quickstart.en-US.md, packages/vant/docs/markdown/quickstart.zh-CN.md
Add Rsbuild import on demand guide.
=> docs: add Rsbuild import on demand guide

packages/vant/src/image/Image.tsx, packages/vant/src/image/README.md, packages/vant/src/image/README.zh-CN.md, packages/vant/src/image/test/__snapshots__/index.spec.ts.snap, packages/vant/src/image/test/index.spec.ts
=> feat(Image): add `crossorigin` & `referrerpolicy`

packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md
* feat(Image): add `crossorigin` & `referrerpolicy` props by @Jungzl in https://github.com/youzan/vant/pull/12641
* fix(NumberKeyboard): render delete slot correctly when theme is custom by @TPORL in https://github.com/youzan/vant/pull/12624
* docs: update docs for params related to Picker events by @wjw-gavin in https://github.com/youzan/vant/pull/12619
* docs(DatePicker): fix en-docs error by @wjw-gavin in https://github.com/youzan/vant/pull/12620
* docs(Uploader): fix miss double quote by @nemo-shen in https://github.com/youzan/vant/pull/12627
* docs: add full registration guide by @chenjiahan in …
=> docs(changelog): vant@4.8.5

packages/vant/src/image-preview/ImagePreview.tsx, packages/vant/src/image-preview/types.ts
=> feat(ImagePreview): add vertical prop

packages/vant/src/image-preview/ImagePreview.tsx, packages/vant/src/image-preview/ImagePreviewItem.tsx
relate PR: #12660
Vertical scrolling also involves the logic when the image is moved to the edge.
=> fix(ImagePreview): allow user to swipe to next image when the current image is moved to the edge

packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md
* feat(ImagePreview): add vertical prop by @suncohey in https://github.com/youzan/vant/pull/12660
* feat(signature): export clear and submit method by @chouchouji in https://github.com/youzan/vant/pull/12654
* feat: support unplugin-auto-import plugin by @DragonnZhang in https://github.com/youzan/vant/pull/12679
* feat(ActionSheet): add icon support to the actions data by @wjw-gavin in https://github.com/youzan/vant/pull/12671
* fix(ImagePreview): allow user to swipe to next image when the current image is moved to the edge by @inottn in https://github.com/youzan/vant/pull/12666
* fix(ActionSheet): icon class name by …
=> docs(changelog): vant@4.8.6

packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md
`2024-03-18`
- Revert "chore(deps): update dependency typescript to v5.4.2" by [@renovate](https://github.com/renovate) in [#12700](https://github.com/youzan/vant/pull/12700)
- chore: Update homepage by [@yoyo837](https://github.com/yoyo837) in [#12704](https://github.com/youzan/vant/pull/12704)
=> docs(changelog): vant@4.8.7

packages/vant/src/picker-group/PickerGroup.tsx, packages/vant/src/picker-group/test/index.spec.tsx, packages/vant/src/utils/basic.ts
=> fix(PickerGroup): rendering correctly when using v-for

packages/vant/src/address-list/AddressList.tsx, packages/vant/src/address-list/AddressListItem.tsx, packages/vant/src/address-list/README.md, packages/vant/src/address-list/README.zh-CN.md, packages/vant/src/address-list/test/index.spec.ts
close https://github.com/youzan/vant/issues/12680
=> feat(AddressList): add event param for click-item

packages/vant/docs/formatChangelog.mjs, packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md
`2024-03-31`
- feat(image-preview): export onLoad and style for image slot by [@chouchouji](https://github.com/chouchouji) in [#12740](https://github.com/youzan/vant/pull/12740)
- feat(AddressList): add event param for click-item by [@chenjiahan](https://github.com/chenjiahan) in [#12748](https://github.com/youzan/vant/pull/12748)
- fix(floating-bubble): update offset when the value changed by [@chouchouji](https://github.com/chouchouji) in [#12730](https://github.com/youzan/vant/pull/12730)
- fix(vant-cli): support defineOptions named by [@wChenonly](https://github.com/wChenonly) in [#12734](https://github.com/youzan/vant/pull/12734)
- fix(PickerGroup): rendering correctly when using v-for by [@inottn](https://github.com/inottn) in [#12732](https://github.com/youzan/vant/pull/12732)
- …
=> docs(changelog): vant v4.8.8

packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md
`2024-04-06`
- feat(TimePicker): support confirm and getSelectedTime methods by [@bluesky335](https://github.com/bluesky335) in [#12761](https://github.com/youzan/vant/pull/12761)
- feat(DatePicker): support confirm and getSelectedDate method by [@bluesky335](https://github.com/bluesky335) in [#12762](https://github.com/youzan/vant/pull/12762)
- feat(Coupon): support for checkbox usage by [@CatsAndMice](https://github.com/CatsAndMice) in [#12744](https://github.com/youzan/vant/pull/12744)
- chore(deps): update dependency vite to v5.0.13 [security] by [@renovate](https://github.com/renovate) in [#12767](https://github.com/youzan/vant/pull/12767)
- chore(deps): update all patch dependencies by [@renovate](https://github.com/renovate) in [#12756](https://github.com/youzan/vant/pull/12756)
- …
=> docs(changelog): vant v4.8.10

packages/vant/src/list/README.md, packages/vant/src/list/README.zh-CN.md
resolve #12777 
demo里头的代码在列表加载失败时有设置 `loading`为`false`
https://github.com/youzan/vant/blob/c857d1fbcb15053fc936df714e93ba8815ddfc4f/packages/vant/src/list/demo/index.vue#L64
但是演示`code`里头没有
=> docs(list):  update Error loading module code

packages/vant-cli/src/compiler/web-types/formatter.ts, packages/vant-cli/src/compiler/web-types/index.ts, packages/vant-cli/src/compiler/web-types/parser.ts
- https://youtrack.jetbrains.com/issue/WEB-52219
**[intellij-community](https://github.com/JetBrains/intellij-community)** **2021** 年起的所有版本。
> [Version 2.0 of the format](https://github.com/JetBrains/web-types?tab=readme-ov-file#version-20-of-the-format)
>
> Starting with version 2021.3.1 of [WebStorm](https://www.jetbrains.com/webstorm/) (and other [JetBrains IDEs](https://www.jetbrains.com/products/#lang=js&type=ide)), a full support for the new Web-Types format is supported (the new format has been partially supported since 2021.2).
我本地只验证了版本（ [**IntelliJ IDEA 2021.2.3**](https://www.jetbrains.com/idea/download/other.html) 到 **IntelliJ IDEA 2023.3.2** ）修复有效。
更早之前的版本有这个问题的话应该也适用。
按照 **WebStorm** 相关代码的维护者所说，在 **web-types.json** 中应该使用属性名 `modelValue` 而非 `v-model` …
=> fix: warning `is not a valid value for v-model` in JetBrains IDE

packages/vant-cli/site/tsconfig.json
The site tsconfig is useless and should not be published.
=> fix(Cli): remove site tsconfig

packages/vant-cli/src/compiler/compile-sfc.ts
Fix: #12797
应该始终坚持使用 compileScript, 顺便添加 scopeId支持
=> fix(cli): Vue SFC style binding failure

vant.config.js
删除 Vant 2 英文文档中位于表单组件中的 `SwitchCell` 组件 。
`SwitchCell` 组件在 Vant 2 文档中已被归类到 废弃 模块。
=> docs(SwitchCell): remove SwitchCell in the form component

README.md, README.zh-CN.md
The previous badge URL is broken and other services are unstable too.
=> docs: remove gzip size badge

packages/vant-cli/src/compiler/compile-sfc.ts
There's a hole here 🥲, if you don't set `preprocessLang` compileStyle to css by default, scopedId will be added for each class name
```css
// raw set scoped
.hello{
&-title{
color:red;
}
}
```
```css
// expect
.hello-title[data-v-7578cda5] {
color: red;
}
```
```css
// preprocessLang is not set
.hello[data-v-7578cda5] {
&-title[data-v-7578cda5] {
color: red;
}
}
// to
.hello[data-v-7578cda5]-title[data-v-7578cda5] {
color: red;
}
```
But it's the equivalent of going through two CSS preprocessor compilations
fix #12844
=> fix(cli): CSS preprocessor for scoped

packages/vant-auto-import-resolver/README.md, packages/vant-auto-import-resolver/README.zh-CN.md, packages/vant-auto-import-resolver/src/index.ts, packages/vant/docs/markdown/quickstart.en-US.md, packages/vant/docs/markdown/quickstart.zh-CN.md
在 #12679 的基础上添加对 unplugin-auto-import 的 imports 选项的支持
该选项可以一次性导出 VantResolver 中的 API 到 `auto-imports.d.ts` 中，以优化编辑器的提示，并避免后续开发过程中该文件的频繁变更
=> feat: supports `imports` option for auto-import

packages/vant/src/area/README.md, packages/vant/src/area/README.zh-CN.md, packages/vant/src/area/demo/index.vue, packages/vant/src/area/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/area/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/area/test/index.spec.ts, packages/vant/src/area/utils.ts
bugfix [#12856](https://github.com/youzan/vant/issues/12856)
当传入 placeholder 后，处理 `市`、`区` 数据有点问题，尝试如下修改：
=> fix(area): columns-placeholder prop rendering error

packages/vant/src/tabs/index.less
在开启 type="card" 后，如果对 tab 进行 disabled 处理，那么 disabled 之后的 tab 项样式和正常样式并无差异。检查代码发现是因为一行 css 未生效，具体可见 commit。
```
<van-tabs v-model:active="active" type="card">
<van-tab title="标签 1">内容 1</van-tab>
<van-tab title="标签 2" disabled>内容 2</van-tab>
<van-tab title="标签 3">内容 3</van-tab>
</van-tabs>
```
之前：
现在：
=> fix(Tab): incorrect style

packages/vant/src/card/Card.tsx, packages/vant/src/card/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/card/test/index.spec.ts, packages/vant/src/swipe-cell/test/__snapshots__/demo-ssr.spec.ts.snap
=> fix(Card): render correctly when the price is an integer

packages/vant/src/tabs/utils.ts
旧的代码：
```
scroller.scrollLeft += (to - from) / frames;
```
当 `(to - from) / frames` 的计算结果为小数，比如 `(to - from) / frames === 0.9` 时，`scroller.scrollLeft` 将永远不会递增。因为在 Chrome 浏览器下，scroller.scrollLeft 的值将被向下取整。也就是说，如果 scroller.scrollLeft = 0.9 时，浏览器将会自动处理为 0。
这会导致两个情况：
1. 在某些情况下，比如动画时间 `duration` 设置为 `3` 时，`(to - from) / frames` 的计算结果为小数。此时点击 tab 后，该 tab 并不会自动居中
2. 由于 Chrome 浏览器会向下取整，那么会导致居中效果出现误差。比如 `(to - from) / frames === 1.5` 时，每帧滚动的像素可能并不是 1.5 而是 1
新的代码：
```
scrollLeft += (to - from) / frames;
scroller.scrollLeft = scrollLeft;
```
将每帧累计的值保存到变量 `scrollLeft` 上，直接将 `scrollLeft` 赋值给 `scroller.scrollLeft`
=> fix(Tab): "scrollLeftTo" function could not handle decimal correctly

packages/vant/src/nav-bar/demo/index.vue
文档里第二个实例定义的左侧按钮的点击事件
而示例代码写的右侧按钮的点击事件
=> docs(nav-bar): replace click-right with click-left for second example

packages/vant/src/tab/README.md, packages/vant/src/tab/README.zh-CN.md
根据以下 Tabs.tsx 的源码，完善文档对应 ellipsis 和 swipe-threshold 的描述：
```
const scrollable = computed(
() =>
children.length > +props.swipeThreshold ||
!props.ellipsis ||
props.shrink,
);
```
根据以下 Badge.tsx 的源码，完善文档对应 badg 的描述：
```
const renderContent = () => {
const { dot, max, content } = props;
if (!dot && hasContent()) {
if (slots.content) {
return slots.content();
}
if (isDef(max) && isNumeric(content!) && +content > +max) {
return `${max}+`;
}
return content;
}
};
```
=> docs(Tab): refine the description of 'props'

packages/vant/src/badge/README.md, packages/vant/src/badge/README.zh-CN.md
根据以下 Badge.tsx 的源码，完善文档对应 content 的描述：
```
const renderContent = () => {
const { dot, max, content } = props;
if (!dot && hasContent()) {
if (slots.content) {
return slots.content();
}
if (isDef(max) && isNumeric(content!) && +content > +max) {
return `${max}+`;
}
return content;
}
};
```
=> docs(Badge): refine the description of 'props'

packages/vant-cli/package.json
=> chore(vant-cli): drop NodeJS 14 support

packages/vant/src/form/Form.tsx, packages/vant/src/form/README.md, packages/vant/src/form/README.zh-CN.md
新一个属性 `scrollToErrorPosition` 来控制 `scrollIntoView` 这个 api 滚动结束时的位置
=> feat(Form): add prop "scrollToErrorPosition"

packages/vant/src/image-preview/README.md, packages/vant/src/image-preview/README.zh-CN.md
fix missing parameters(src) when  using image slot
=> docs(ImagePreview): fix missing parameters

packages/vant-compat/src/dialog.ts, packages/vant-compat/src/toast.ts
- fix #12952 
- add Toast.loading in vant-compat/src/toast.ts
- correct  Dialog.confirm function name in vant-compat/src/dialog.ts （Dialog.config to Dialog.confirm）
=> fix(vant-compat): [Toast][Dialog] fix missed and incorrect export error #12952

packages/vant/src/calendar/CalendarHeader.tsx, packages/vant/src/calendar/test/switch-mode.spec.ts
=> fix(Calendar): disable the previous month button correctly when the minDate is the current time

packages/vant/src/text-ellipsis/TextEllipsis.tsx, packages/vant/src/text-ellipsis/test/__snapshots__/demo-ssr.spec.ts.snap
=> fix(TextEllipsis): calculate the width of the action slot correctly

packages/vant/src/swipe-cell/README.md, packages/vant/src/swipe-cell/README.zh-CN.md, packages/vant/src/swipe-cell/SwipeCell.tsx, packages/vant/src/swipe-cell/test/index.spec.js
resolve https://github.com/youzan/vant/issues/7631#issuecomment-2260092093
=> feat(SwipeCell): add event param for before-close

packages/vant/src/swipe-cell/SwipeCell.tsx
fix #13037
Conflicts may need to be resolved after #13039  is merged.
=> fix(SwipeCell): the click will be triggered after the touchend event on desktop

packages/vant/src/steps/README.md, packages/vant/src/steps/README.zh-CN.md
This PR updates the default value of the `active-color` property in the Steps component documentation.
=> docs(Steps): update active-color default value

packages/vant/src/lazyload/vue-lazyload/index.d.ts
vue-router pinia has been replaced. 
https://github.com/vuejs/router/pull/2295
https://github.com/vuejs/router/commit/4f082cd05507f33c6d0e6c9dd042cbe75d38ccb5
https://github.com/vuejs/pinia/commit/8a6ce86db83b6315c067c8a98c898b3c74efe62e
Sometimes because vant is not replaced, `ComponentCustomProperties` cannot be used in vue-router and pinia (Only one of these two ways will work) I'm not familiar with Typescript and I don't know why.
=> fix: use declare module 'vue' instead of @vue/runtime-core

packages/vant-area-data/package.json
目前 exports 没有声明 package.json，会导致构建工具无法读取这个包的 package.json
参考 1：https://github.com/vue-mini/create-vue-mini/issues/16
参考 2：https://github.com/nodejs/node/issues/33460
=> fix(vant-area-data): export package.json

packages/vant/src/calendar/README.md, packages/vant/src/calendar/README.zh-CN.md, packages/vant/src/calendar/index.less, packages/vant/src/calendar/types.ts
1. 优化 css var 声明顺序
2. 修复英文文档中出现的中文
3. 修复「确定」按钮文案
4. 补全 type 字段可选值
5. 优化 month-show 和 panel-change 文案
=> docs(Calendar): fix documentation errors

packages/vant/src/calendar/Calendar.tsx, packages/vant/src/calendar/test/prop.spec.ts
当 defaultDate 为 undefined 时，现有的 watch 会将其重置为 null，逻辑如下：
```js
watch(
() => props.defaultDate,
(value = null) => {
currentDate.value = value;
scrollToCurrentDate();
},
);
```
而在该日历组件中，undefined 表示「今天」，null 表示 「不选择」。如果业务层将 defaultDate 重置为 undefined，这时候日历组件将会表现为「不选择」，业务层必须手动调用一次 reset 方法才能实现日历上选中「今天」
所以该侦听器逻辑应该是：
```js
watch(
() => props.defaultDate,
(value) => {
if (value === undefined) {
value = getInitialDate();
}
currentDate.value = value;
scrollToCurrentDate();
},
);
```
简化一下：
```js
watch(
() => props.defaultDate,
(value) => {
reset(value);
},
);
```
=> fix(Calendar): fix watch 'defaultDate' error

packages/vant/src/toast/README.md, packages/vant/src/toast/README.zh-CN.md
#13109 
在使用[按需引入组件](https://vant.pro/vant/#/zh-CN/quickstart#fang-fa-er.-an-xu-yin-ru-zu-jian-yang-shi)方案集成 `vant` 时，使用 showToast 等函数无需进行显式导入，否则会造成样式异常。
```
// 以下方式是不需要的
import { showToast } from 'vant'
```
这是因为在显式导入 showToast 等函数时，` @vant/auto-import-resolver` 将不会自动导入 Toast 的样式资源，这将导致 Toast 组件
的样式缺失，从而导致样式异常问题。
解决方案有2种：
- 使用 `showToast` 时不进行显式导入；
- 如果必须显示导入 `showToast` ，则同时需要手动导入 `Toast` 组件的相关样式。
```
import { showToast } from 'vant'
import 'vant/lib/toast/style'
```
=> docs(components):  add FAQ for showToast on-demand loading

packages/vant/src/date-picker/DatePicker.tsx, packages/vant/src/date-picker/README.md, packages/vant/src/date-picker/README.zh-CN.md, packages/vant/src/date-picker/utils.ts, packages/vant/src/time-picker/TimePicker.tsx
Maintain consistency with the functionality of TimePicker(https://github.com/youzan/vant/pull/11916).
=> feat(DatePicker): filter support values param to help get current values

packages/vant/src/field/Field.tsx, packages/vant/src/field/test/index.spec.js
=> fix(Field): should not adjust value when the min or max props are not set

packages/vant/src/dialog/Dialog.tsx, packages/vant/src/dialog/README.md, packages/vant/src/dialog/README.zh-CN.md
https://github.com/youzan/vant/issues/13164
针对issue #13164 提到的部分手机场景的某些操作会自动执行enter的键盘事件，新增keyboardEnabled属性来控制是否选择使用键盘能力选项
=> feat(dialog): add new `keyboardEnabled` prop

packages/vant/src/config-provider/demo/index.vue
… switching causes the theme styles to stack up in the document.
解决https://github.com/youzan/vant/issues/13179 
这个bug存在于文档ConfigProvider全局配置的demo中，并且只有暗色主题存在这个问题，看了下源码，发现应该是在顶部切换主题的时候会默认执行增删van-theme-dark 和van-theme-light逻辑，而ConfigProvider全局配置内部引入了ConfigProvider在加载时会默认添加van-theme-light，应该算是文档的一个小bug，修复逻辑是暂时在ConfigProvider全局配置的示例文件中，如果同时存在这两种主题的话将van-theme-light属性删除，不会影响其他
=> docs(ConfigProvider): fix incorrect theme classnames

packages/vant/src/field/README.md, packages/vant/src/field/README.zh-CN.md
https://github.com/youzan/vant/pull/13208
=> docs(Field): add `inputmode` to document

packages/vant/src/popover/README.md, packages/vant/src/popover/README.zh-CN.md
fix the typo:
popover support placement not position
=> docs: fix placement typo

packages/vant/src/picker/Picker.tsx, packages/vant/src/picker/README.md, packages/vant/src/picker/README.zh-CN.md, packages/vant/src/picker/demo/index.vue, packages/vant/src/picker/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/picker/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/picker/test/index.spec.tsx
=> feat(Picker): add empty slot

packages/vant/src/composables/use-lazy-render.ts, packages/vant/src/form/README.md, packages/vant/src/form/README.zh-CN.md, packages/vant/src/form/demo/FieldTypeArea.vue, packages/vant/src/form/demo/FieldTypeDatePicker.vue, packages/vant/src/form/demo/FieldTypePicker.vue, packages/vant/src/picker/README.md, packages/vant/src/picker/README.zh-CN.md, packages/vant/src/picker/demo/WithPopup.vue, packages/vant/src/popup/Popup.tsx, packages/vant/src/popup/README.md, packages/vant/src/popup/README.zh-CN.md, packages/vant/src/popup/test/index.spec.jsx
close #13199 close #12796
The combination of the Picker and Popup components is very common. However, a long-standing issue has been that after scrolling to change the selected option in the Picker and then closing the Popup, reopening it causes the Picker to remain at the last scrolled position instead of resetting to the previously selected value. This behavior can be reproduced in the [demo](https://vant-ui.github.io/vant/#/en-US/picker#with-popup) examples in the documentation and has caused confusion for many users.
This PR introduces a new destroy-on-close prop and improves the related documentation to address this issue.
=> feat(Popup): add destroy-on-close prop

packages/vant-compat/package.json, packages/vant-compat/rslib.config.ts, pnpm-lock.yaml
This pull request includes several changes to the `vant-compat` package to update its build configuration and dependencies. The most important changes involve modifying the build scripts, updating dependencies, and adding a new configuration file for `rslib`.
=> chore(vant-compat): use Rslib to build

packages/vant/src/calendar/Calendar.tsx, packages/vant/src/calendar/README.md, packages/vant/src/calendar/README.zh-CN.md, packages/vant/src/calendar/test/index.spec.ts
=> feat(Calendar): add click-overlay event

packages/create-vant-cli-app/package.json, packages/vant-cli/package.json, pnpm-lock.yaml
Fix missing `@types/node` dependency:
=> chore: fix missing `@types/node` dependency

.github/workflows/deploy-v4-site.yml, .github/workflows/test.yml
See https://github.com/pnpm/pnpm/issues/9029 for background.
=> chore(ci): fix corepack key id mismatch

packages/vant/src/field/Field.tsx
在 type 为 number 或 digit 时，如果没有设置 min 或 max，onblur 时值 1.00 不会有变化，但当设置了 min 或 max 时，onblur  会触发非必要的格式化，导致值 1.00 变成 1。
=> fix(Field): should not modify the value if it's within the min/max

packages/vant/src/field/Field.tsx, packages/vant/src/field/test/index.spec.js
close #13282
Added @dgmpk to co-author info.
=> test(Field): should not modify the value if it's within the min/max

packages/vant/src/swipe-cell/SwipeCell.tsx, packages/vant/src/swipe-cell/test/index.spec.js, packages/vant/test/event.ts
=> fix(SwipeCell): unintended stopPropagation when canceling a swipe

packages/vant-auto-import-resolver/README.md, packages/vant-auto-import-resolver/README.zh-CN.md, packages/vant-auto-import-resolver/src/index.ts
添加 @vant/auto-import-resolver 支持 exclude，主要用于二次封装组件或者 api 的场景，不对其原组件或 api 自动引入，而是使用二次封装好的同名组件或者同名 api
=> feat(@vant/auto-import-resolver): Support exclude in components or apis

pnpm-lock.yaml
https://github.com/youzan/vant/security/dependabot/21
=> chore(deps): update cross-spawn to 7.0.6 to fix security alerts

packages/vant/src/button/index.less
在进行业务开始时，通常会事先配置一些全局的 CSS 样式，比如：
```css
*,
*::before,
*::after {
box-sizing: border-box;
}
```
而当上面这段 CSS 作用于 Vant Button 按钮的 ::before 伪元素时将导致该伪元素的宽高比 Button 按钮的宽高小 `border * 2`。Vant Button 的 border 宽度默认是 1px，那么默认就会小 1 * 2 = 2px。
这在一些特殊的样式下，比如业务上将 border 修改为 2px 时，两者差距就 2 * 2 = 4px，肉眼就非常明显了。
如下为 Vant 官网对比图：
该 PR 的解决办法就是强制对该伪元素使用 `box-sizing: content-box;`
=> fix(Button): fix button active style

packages/vant/src/overlay/README.md, packages/vant/src/overlay/README.zh-CN.md, packages/vant/src/overlay/demo/index.vue
使该示例正确表达：**点击嵌入内容不会关闭遮罩层，点击空白区域可以**
=> docs(Overlay): fix the misleading overlay example

packages/vant/src/floating-bubble/FloatingBubble.tsx, packages/vant/src/floating-bubble/README.md, packages/vant/src/floating-bubble/README.zh-CN.md, packages/vant/src/floating-bubble/test/index.spec.ts, packages/vant/src/floating-bubble/types.ts
期望如標題所述，這樣我就能貼近側邊設定離底部多高。
兼容 `number` 同時，新增 `{ x: number, y: number }` 類型，採用此類型而不是數組的原因是與 `v-model:offset` 同類型較統一。
close #13297
=> feat(FloatingBubble): allow gap xy to be set separately (#13297)

packages/vant/src/dropdown-item/DropdownItem.tsx, packages/vant/src/popup/Popup.tsx, packages/vant/src/popup/README.md, packages/vant/src/popup/README.zh-CN.md, packages/vant/src/popup/shared.ts
Add `overlay-props` prop to Popup and remove the `disable-overlay-transition` prop.
Related https://github.com/youzan/vant/pull/13436
=> feat(Popup): add overlay-props prop

packages/vant/src/picker/Picker.tsx, packages/vant/src/picker/test/index.spec.tsx
This is an improvement on https://github.com/youzan/vant/pull/13425, which automatically resets `selectedValues` ​​when Picker's `modelValue` prop is set to an empty array, which is more appropriate than waiting for an event to trigger.
=> fix(Picker): update selected values when modelValue is cleared

packages/vant/src/floating-panel/README.md, packages/vant/src/floating-panel/README.zh-CN.md
修复了 FloatingPanel 组件文档中的错误，将 `window.innerWidth * 0.6` 错误地用于计算面板高度改为正确的 `window.innerHeight * 0.6`。
修改了以下文件中的默认值描述：
- `packages/vant/src/floating-panel/README.md`（英文文档）
- `packages/vant/src/floating-panel/README.zh-CN.md`（中文文档）
- 仅修改了文档中的描述，不影响组件的实际功能
- 不影响已有的代码实现，因为实际代码中已经正确使用了 `window.innerHeight`
=> docs: correct window.innerWidth to window.innerHeight in FloatingPanel

packages/vant/src/watermark/Watermark.tsx
fix #13468
When using watermark with image, need to wait for image to mount before generating the watermark URL.
=> fix(Watermark): ensure watermark updates on imageBase64 change

packages/vant/src/uploader/README.md, packages/vant/src/uploader/README.zh-CN.md
根据源码中类型文件得知以下回调参数：
```ts
export type UploaderAfterRead = (
items: UploaderFileListItem | UploaderFileListItem[],
detail: {
name: Numeric;
index: number;
},
) => void;
```
所以将文档中相关的描述更改为：`UploaderFileListItem | UploaderFileListItem[]`
=> docs(Uploader): optimize parameter description

packages/vant/src/progress/Progress.tsx, packages/vant/src/progress/demo/index.vue
修复该 issue 提到的问题：https://github.com/youzan/vant/issues/13518
在组件内部格式化一下传入参数的范围即可，但 UI 上依旧渲染传入的数值：
=> fix(Progress): width overflow

src/sku/README.md, src/sku/Sku.js, src/sku/demo/data.ts, src/sku/demo/index.vue, src/sku/utils/sku-helper.js
Add support for `disable_status` field in SKU component to automatically filter disabled SKU options and improve user experience.
- **Auto filter disabled SKUs**: Hide SKU options with `disable_status: 1`
- **Smart cascading filter**: Filter out options that would result in all disabled combinations
- **Initialization check**: Validate `initialSku` to ensure valid selection on component init
1. Hide spec values if all related SKUs are disabled
2. Filter out spec values that create only disabled combinations when selected
3. Hide spec categories with no available values
4. Check `initialSku` validity during initialization
- Add `filterDisabledSkuTree` function for filtering logic
- Enhance `isSkuChoosable` to check non-disabled SKU stock
- Update `resetSelectedSku` with disabled status …
=> feat(Sku): support disable_status field to filter disabled SKU options

packages/vant/src/checkbox/Checker.tsx
This PR is to fix #13552 
The selected state color and indeterminate state color of a group of checkboxes could be better if kept consistent, as this would create a more unified style
Set 'checked-color' to 'red',comparison of effects:
Before modification
After modification
I didn't see any unit tests related to the color, so I didn't add the corresponding unit tests
=> fix(checkbox): apply 'checked-color' when 'checkbox' is indeterminate

packages/vant/src/popup/demo/index.vue
=> docs(Popup): align document and demo
