youzan/vant

src/count-down/test/index.spec.js, src/utils/with-install.ts
https://github.com/youzan/vant/issues/8302
=> types: add onClick event shim

docs/markdown/style-guide.zh-CN.md
https://github.com/youzan/vant/issues/8672
=> docs: update style guide

src/coupon-list/README.md, src/coupon-list/README.zh-CN.md, src/coupon-list/demo/index.vue, src/coupon/index.js
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
=> 优惠券组件有效时间支持毫秒及自定义

src/field/README.zh-CN.md
https://github.com/youzan/vant/issues/8702
=> docs(Field): improve input slot description

src/utils/functional.ts
https://github.com/youzan/vant/issues/8717
=> fix: functional components should inherit "key"

src/tabs/Tabs.tsx
给 `Tabs` 组件，添加 `scroll` 事件的时候，直接传入 `scroller.value`，会把事件添加在默认的 `window` 上
=> feat(Tabs): fix add scroll event target

src/button/index.tsx
https://github.com/youzan/vant/issues/8728
=> fix(Button): should not submit form when loading

src/popover/README.zh-CN.md
https://github.com/youzan/vant/issues/8727
=> docs(Popover): add fastclick faq

src/calendar/Calendar.tsx, src/calendar/README.md, src/calendar/README.zh-CN.md, src/calendar/test/prop.spec.ts
- show-range-prompt prop
- over-range event
=> feat(Calendar): add show-range-prompt prop

src/composables/use-tab-status.ts, src/list/List.tsx, src/list/test/index.spec.js, src/tab/Tab.tsx
https://github.com/youzan/vant/issues/8729
=> fix(List): skip check when inside an inactive tab

src/uploader/README.md, src/uploader/README.zh-CN.md, src/uploader/Uploader.tsx, src/uploader/demo/index.vue, src/uploader/test/index.spec.ts, src/uploader/utils.ts
https://github.com/youzan/vant/issues/8618
=> feat(Uploader): max-size prop can be a function

src/uploader/README.md, src/uploader/README.zh-CN.md
https://github.com/youzan/vant/issues/8422
=> docs(Uploader): add native attrs tip

src/form/README.md, src/form/README.zh-CN.md
https://github.com/youzan/vant/issues/8591
=> docs(Form): add with field tip

src/grid-item/GridItem.tsx, src/grid/README.md, src/grid/README.zh-CN.md, src/grid/test/index.spec.js
=> feat(GridItem): add icon-color prop

docs/site/entry.js, vant.config.js
https://github.com/youzan/vant-weapp/issues/4227
=> docs: hide some nav item in weapp

src/list/README.md, src/list/README.zh-CN.md, src/list/var.less
=> fix(List): remove unused Less var @list-icon-margin-right

packages/vant-touch-emulator/index.js
由于import是静态的，只能放最前面，在SSR时`window`会报错。
代码只是套了个IIFE.
=> fix(@vant/touch-emulator): add SSR support

src/cell-group/index.tsx
https://github.com/youzan/vant/issues/8768
=> fix(CellGroup): render error in loop

src/collapse-item/index.less
https://github.com/youzan/vant/issues/8608
=> fix(Collapse):  fix safari rendering issues

src/notice-bar/NoticeBar.tsx
https://github.com/youzan/vant/issues/8777
=> fix(NoticeBar): failed to play when inside a re-opened popup

src/coupon-list/README.md, src/coupon-list/README.zh-CN.md, src/coupon-list/demo/index.vue, src/coupon-list/index.js
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
=> feat(CouponList): add list-footer slot

docs/markdown/design.zh-CN.md, packages/vant-cli/site/desktop/components/Content.vue
https://github.com/youzan/vant/issues/8775
=> fix(cli): fix style polution

src/config-provider/ConfigProvider.tsx, src/config-provider/README.md, src/config-provider/README.zh-CN.md, src/config-provider/demo/index.vue, src/config-provider/index.ts, src/config-provider/test/__snapshots__/demo.spec.ts.snap, src/config-provider/test/demo.spec.ts, vant.config.js
https://github.com/youzan/vant/issues/8853
=> feat: add ConfigProvider component

src/number-keyboard/README.zh-CN.md
https://github.com/youzan/vant/issues/8875
=> docs(NumberKeyboard): add maxlength description

src/grid-item/GridItem.tsx, src/grid-item/index.less, src/grid/Grid.tsx, src/grid/README.md, src/grid/README.zh-CN.md, src/grid/test/index.spec.js
https://github.com/youzan/vant-weapp/issues/4272
=> feat(GridItem): add reverse prop

src/cell-group/CellGroup.tsx, src/cell-group/index.less, src/cell-group/var.less, src/cell/README.md, src/cell/README.zh-CN.md, src/cell/demo/index.vue, src/cell/test/__snapshots__/demo.spec.ts.snap
https://developer.apple.com/design/human-interface-guidelines/ios/views/tables/
=> feat(CellGroup): add inset prop

docs/markdown/theme.en-US.md, docs/markdown/theme.zh-CN.md
=> docs(theme): fix article link for configProvider

src/slider/Slider.tsx, src/slider/test/index.spec.ts, src/stepper/Stepper.tsx, src/utils/format/number.ts
https://github.com/youzan/vant/issues/8889
=> fix(Slider): format v-model with step correctly

packages/vant-cli/src/config/postcss.config.ts
https://github.com/youzan/vant/issues/8905
=> fix(cli): allow custom postcss autoprefixer

packages/vant-cli/src/compiler/compile-sfc.ts
修复了sfc编译错误, 替换 `export default {` 没有考虑 defineComponent 的情况 或者 工程函数的情况
=> fix(cli): #8890 sfc compile error

src/form/README.md, src/notice-bar/NoticeBar.tsx, src/notice-bar/README.md, src/notice-bar/README.zh-CN.md, src/notice-bar/test/index.spec.tsx
https://github.com/youzan/vant/issues/8906
=> feat(NoticeBar): add reset method

src/action-bar/README.zh-CN.md, src/checkbox/README.md, src/coupon-list/README.md, src/index-bar/README.md, src/notice-bar/README.md, src/notify/README.md, src/notify/README.zh-CN.md, src/tab/README.md, src/toast/README.zh-CN.md
[文档排版错误-https://youzan.github.io/vant/v3/#/zh-CN/toast](https://youzan.github.io/vant/v3/#/zh-CN/toast)
其它的也是类似
=> docs: fix format errors

packages/vant-cli/package.json, packages/vant-cli/yarn.lock
https://github.com/youzan/vant/pull/8919
=> fix(cli): downgrade prettier version

src/collapse-item/CollapseItem.tsx, src/collapse/README.md, src/collapse/README.zh-CN.md, src/collapse/test/__snapshots__/index.spec.tsx.snap, src/collapse/test/index.spec.tsx
https://github.com/youzan/vant/issues/8922
=> feat(CollapseItem): add label slot

src/stepper/index.js
https://github.com/youzan/vant/issues/8932
=> fix(Stepper): incorrect value after blurred when using async-change

packages/vant-cli/src/compiler/compile-sfc.ts
兼容 @vue/composition-api 中导出的 defineComponent
=> fix(cli): sfc missing render fn when using defineComponent

src/picker/Picker.tsx, src/picker/PickerColumn.tsx, src/picker/README.md, src/picker/README.zh-CN.md
https://github.com/youzan/vant/issues/8931
=> feat(Picker): allow option text to be number type

src/cascader/Cascader.tsx, src/cascader/README.md, src/cascader/README.zh-CN.md, src/cascader/index.less, src/cascader/var.less
https://github.com/youzan/vant/issues/8943
=> feat(Cascader): add disabled option

src/calendar/CalendarDay.tsx, src/calendar/test/__snapshots__/demo.spec.ts.snap, src/calendar/test/__snapshots__/index.spec.ts.snap
https://github.com/youzan/vant/issues/8948
=> perf(Calendar): simplify placeholder dom

src/toast/index.less
https://github.com/youzan/vant/issues/8959
=> style(Toast): adjust word break

src/calendar/Calendar.tsx, src/calendar/CalendarHeader.tsx, src/calendar/README.md, src/calendar/README.zh-CN.md, src/calendar/test/index.spec.ts
https://github.com/youzan/vant/issues/8978
=> feat(Calendar): add click-subtitle event

packages/vant-touch-emulator/index.js
=> feat(touch-emulator): 支持白名单排除

packages/vant-touch-emulator/README.md, packages/vant-touch-emulator/changelog.md, packages/vant-touch-emulator/package.json
https://github.com/youzan/vant/pull/8984
=> chore: release @vant/touch-emulator@1.3.1

src/slider/README.md, src/slider/README.zh-CN.md, src/slider/Slider.tsx, src/slider/test/__snapshots__/index.spec.ts.snap, src/slider/test/index.spec.ts
https://github.com/youzan/vant/issues/8979
=> feat(Slider): add left-button、right-button slot

packages/vant-touch-emulator/index.js
=> fix(touch-emulator): 添加 Element.prototype.matches 的 polyfill

src/pull-refresh/README.zh-CN.md
https://github.com/youzan/vant/issues/6955
=> docs(PullRefresh): add faq

src/step/index.less
https://github.com/youzan/vant/issues/8999
=> fix(Step): fix z-index issue

src/step/index.less
https://github.com/youzan/vant/issues/8999
=> fix(Step): z-index issue in 2.x

src/field/Field.tsx, src/field/README.md, src/field/README.zh-CN.md, src/field/index.less, src/field/test/__snapshots__/demo.spec.ts.snap, src/field/var.less
https://github.com/youzan/vant/issues/9020
=> fix(Field): required mark position

src/tab/README.md, src/tab/README.zh-CN.md, src/tab/test/index.legacy.js, src/tab/test/index.spec.tsx, src/tabs/Tabs.tsx
https://github.com/youzan/vant/issues/9034
=> feat(Tabs): add click-tab event

src/checkbox/README.md, src/checkbox/README.zh-CN.md
https://github.com/youzan/vant/issues/9054
=> docs(Checkbox): fix v-model name

src/uploader/README.zh-CN.md
=> fix: document error in uploader

packages/vant-use/src/useEventListener/index.ts
https://github.com/youzan/vant/issues/9089
=> fix(@vant/use): invalid watch source

.github/CONTRIBUTING.md, docs/markdown/contribution.zh-CN.md
https://github.com/youzan/vant/issues/9079
=> docs: fix bootstrap command

src/number-keyboard/NumberKeyboard.tsx
https://github.com/youzan/vant/issues/9102
=> fix(NumberKeyboard): should not emit close event when click away

src/config-provider/README.md, src/config-provider/README.zh-CN.md
https://github.com/youzan/vant/issues/9080
=> docs: update basic variables usage

src/tab/README.zh-CN.md
https://github.com/youzan/vant/issues/6895
=> docs(Tabs): add before-change swipeable tip

package.json, src/uploader/README.md, src/uploader/README.zh-CN.md, src/uploader/Uploader.tsx, src/uploader/index.less, src/uploader/test/__snapshots__/index.spec.ts.snap, src/uploader/test/index.spec.ts, yarn.lock
https://github.com/youzan/vant/pull/9005
=> feat(Uploader): add readonly prop

src/uploader/README.md, src/uploader/README.zh-CN.md, src/uploader/Uploader.tsx, src/uploader/test/index.spec.ts
close https://github.com/youzan/vant/pull/9005
=> feat(Uploader): add click-upload event

packages/vant-markdown-loader/src/extract-demo.js
=> fix: #9043 windows path format

src/notify/function-call.tsx
https://github.com/youzan/vant/issues/9135
=> fix(Notify): default option is overrided

src/composables/use-expose.ts, src/form/Form.tsx, src/form/README.md, src/form/README.zh-CN.md, src/form/index.ts
https://github.com/youzan/vant/issues/9130
=> types(Form): add FormInstance type

src/checkbox/Checkbox.tsx, src/checkbox/README.md, src/checkbox/README.zh-CN.md, src/checkbox/index.ts
https://github.com/youzan/vant/issues/9130
=> types(Checkbox): add CheckboxInstance type

src/checkbox-group/CheckboxGroup.tsx, src/checkbox-group/index.ts, src/checkbox/README.md, src/checkbox/README.zh-CN.md
https://github.com/youzan/vant/issues/9130
=> types(CheckboxGroup): add CheckboxGroupInstance type

src/address-edit/README.md, src/address-edit/README.zh-CN.md, src/checkbox-group/CheckboxGroup.tsx, src/checkbox-group/index.ts, src/checkbox-group/types.ts, src/checkbox/Checkbox.tsx, src/checkbox/index.ts, src/checkbox/types.ts, src/composables/use-link-field.ts, src/form/Form.tsx, src/form/index.ts, src/form/types.ts, src/swipe/README.md, src/swipe/README.zh-CN.md, src/swipe/Swipe.tsx, src/swipe/index.ts, src/swipe/types.ts
https://github.com/youzan/vant/issues/9130
=> types: add SwipeInstance type

src/tabs/index.less
=> fix(Tabs): remove invalid head padding for card type

src/rate/index.less
https://github.com/youzan/vant/issues/9189
=> fix(Rate): should enable flex wrap

src/toast/function-call.tsx, src/utils/mount-component.ts
https://github.com/youzan/vant/issues/9190
=> fix(Toast): failed to update message

src/badge/Badge.tsx, src/badge/test/index.spec.ts
https://github.com/youzan/vant/issues/9198
=> fix(Badge): minus x offset not work

packages/vant-use/src/index.ts, packages/vant-use/src/useCustomFieldValue/index.ts, src/field/types.ts
https://github.com/youzan/vant/issues/9123
=> feat(@vant/use): add useCustomFieldValue

docs/markdown/use-custom-field-value.en-US.md, docs/markdown/use-custom-field-value.zh-CN.md, src/form/README.zh-CN.md, vant.config.js
https://github.com/youzan/vant/issues/9123
=> docs: add useCustomFieldValue document

src/field/utils.ts
https://github.com/youzan/vant/issues/9178
=> fix(Field): textarea scroll to top after resizing

src/dialog/demo/index.vue
=> feat(Dialog): add a "title" in the title attribute

src/dialog/Dialog.tsx, src/popup/Popup.tsx
The method is  trigger twice when the dialog box is closed
=> perf: resolve beforeClose repeat trigger

README.md, README.zh-CN.md, docs/markdown/home.en-US.md, docs/markdown/home.zh-CN.md
https://github.com/youzan/vant/issues/9298
=> docs: add 3lang3/react-vant link

README.md, README.zh-CN.md, docs/markdown/home.en-US.md, docs/markdown/home.zh-CN.md
https://github.com/youzan/vant/issues/9298
=> docs: add react-vant link to v2 site

src/password-input/README.md, src/password-input/README.zh-CN.md, src/password-input/index.less, src/password-input/var.less
https://github.com/youzan/vant/issues/9212
=> feat(PasswordInput): add password-input-text-color css var

src/circle/Circle.tsx, src/circle/README.md, src/circle/README.zh-CN.md, src/circle/demo/index.vue, src/circle/index.ts, src/circle/test/__snapshots__/demo.spec.ts.snap, src/circle/test/index.spec.ts
https://github.com/youzan/vant/issues/9191
=> feat(Circle): add startPosition prop

src/config-provider/test/__snapshots__/demo.spec.ts.snap, src/form/test/__snapshots__/demo.spec.ts.snap, src/slider/README.md, src/slider/README.zh-CN.md, src/slider/Slider.tsx, src/slider/index.less, src/slider/test/__snapshots__/demo.spec.ts.snap, src/slider/test/__snapshots__/index.spec.ts.snap, src/slider/test/index.spec.ts
https://github.com/youzan/vant/issues/9191
=> feat(Slider): add reverse prop

src/field/Field.tsx, src/field/test/__snapshots__/demo.spec.ts.snap
https://github.com/youzan/vant/issues/9324
=> feat(Field): add van-field__error class when error

src/progress/Progress.tsx, src/progress/README.md, src/progress/README.zh-CN.md, src/progress/demo/index.vue, src/progress/index.less
- 修复了Progress组件使用v-show控制显隐时，无法正确获取宽度的问题。同时减少重排重绘次数。
-  增加过渡效果
=> refactor(Progress): fix render error when use v-show and add transition effect

src/address-edit/test/__snapshots__/demo.spec.ts.snap, src/address-edit/test/__snapshots__/index.spec.js.snap, src/cascader/test/__snapshots__/demo.spec.ts.snap, src/config-provider/test/__snapshots__/demo.spec.ts.snap, src/contact-edit/test/__snapshots__/demo.spec.ts.snap, src/field/Field.tsx, src/field/test/__snapshots__/demo.spec.ts.snap, src/field/test/__snapshots__/index.spec.js.snap, src/form/test/__snapshots__/demo.spec.ts.snap, src/number-keyboard/test/__snapshots__/demo.spec.ts.snap, src/picker/test/__snapshots__/demo.spec.ts.snap, src/popover/test/__snapshots__/demo.spec.ts.snap
https://github.com/youzan/vant/issues/9318
=> feat(Field): using <label> tag for label

src/field/test/index.spec.js, src/search/README.md, src/search/README.zh-CN.md, src/search/Search.tsx, src/search/test/__snapshots__/demo.spec.ts.snap, src/search/test/__snapshots__/index.spec.ts.snap, src/search/test/index.spec.ts
https://github.com/youzan/vant/issues/9318
=> feat(Search): add id prop

docs/markdown/use-rect.zh-CN.md
https://github.com/youzan/vant/issues/9366
=> docs: fix useRect param

packages/vant/src/field/README.md, packages/vant/src/field/README.zh-CN.md, packages/vant/src/field/index.less, packages/vant/src/field/var.less
https://github.com/youzan/vant/issues/9392
=> fix(FIeld): field-error-message-font-size var name

packages/vant/src/submit-bar/README.md, packages/vant/src/submit-bar/README.zh-CN.md, packages/vant/src/submit-bar/index.less
https://github.com/youzan/vant/pull/9411/checks?check_run_id=3541277729
=> fix(SubmitBar): remove duplicate "--van-submit-bar-price-font-size"

packages/vant/src/slider/Slider.tsx
=> fix(slider): empty range value

packages/vant/src/swipe/Swipe.tsx
https://github.com/youzan/vant/issues/9436
=> fix(Popup): failed to autoplay when activated

packages/vant/src/uploader/index.less
https://github.com/youzan/vant/issues/9449
=> fix(Uploader): uploader-delete-icon-size should affect icon size

packages/vant/src/button/index.less
https://github.com/youzan/vant/issues/9401
=> feat(Button): support CSS vars gradient background color

packages/vant-cli/site/desktop/router.js
https://github.com/youzan/vant/issues/9464
=> fix(@vant/cli): shoud scroll to top after routing

packages/vant/src/collapse/README.zh-CN.md
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
=> docs(collapse): fix typo

README.md, README.zh-CN.md, packages/vant/docs/markdown/home.en-US.md, packages/vant/docs/markdown/home.zh-CN.md
https://github.com/youzan/vant/discussions/9403
=> docs: add vant-theme link

packages/vant/src/checkbox/Checker.tsx
https://github.com/youzan/vant/issues/9462
=> fix(Radio): icon ref may be undefined

packages/vant/src/dialog/README.zh-CN.md, packages/vant/src/image-preview/README.zh-CN.md, packages/vant/src/notify/README.zh-CN.md
https://github.com/youzan/vant/issues/9510
=> docs: add usage of function component in script setup

packages/vant/src/uploader/README.zh-CN.md
https://github.com/youzan/vant/issues/9484
=> docs(Uploader): add faq

packages/vant/src/number-keyboard/README.md, packages/vant/src/number-keyboard/README.zh-CN.md
https://github.com/youzan/vant/issues/9549
=> docs(NumberKeyboard): fix multiple extraKey doc

packages/vant/src/field/Field.tsx, packages/vant/src/search/README.md, packages/vant/src/search/README.zh-CN.md, packages/vant/src/search/test/index.spec.ts
https://github.com/youzan/vant/issues/9546
=> feat(Search): add autocomplete prop

packages/vant/src/popover/Popover.tsx
`PopoverAction`类型允许添加额外的属性，用于判断选中的选项等。
=> types(Popover): PopoverAction type allow extra properties

packages/vant/src/field/Field.tsx, packages/vant/src/field/README.md, packages/vant/src/search/README.md, packages/vant/src/search/README.zh-CN.md, packages/vant/src/search/test/index.spec.ts
https://github.com/youzan/vant/issues/9560
=> feat(Search): add name prop

packages/vant-cli/package.json, packages/vant/src/image-preview/test/__snapshots__/index.spec.ts.snap, packages/vant/src/image-preview/test/function-call.spec.ts, packages/vant/src/image-preview/test/index.spec.ts, packages/vant/src/image-preview/test/shared.ts, packages/vant/src/overlay/Overlay.tsx, packages/vant/src/utils/mount-component.ts, yarn.lock
https://github.com/youzan/vant/issues/9583
=> fix(Toast): failed to sync clear toast

packages/vant-lazyload/src/util.js, packages/vant-use/src/useEventListener/index.ts, packages/vant/src/composables/use-lock-scroll.ts
=> perf: remove passive event polyfill

packages/vant/src/cascader/Cascader.tsx, packages/vant/src/cascader/README.md, packages/vant/src/cascader/README.zh-CN.md, packages/vant/src/cascader/demo/index.vue, packages/vant/src/cascader/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/cascader/test/__snapshots__/index.spec.ts.snap, packages/vant/src/cascader/test/index.spec.ts, packages/vant/src/utils/create.ts
https://github.com/youzan/vant/pull/9732
=> chore(Cascader): fix some issues

src/progress/index.js
https://github.com/youzan/vant/issues/9755
=> fix(Progress): should resize when window size changed

README.md, README.zh-CN.md, packages/vant/docs/markdown/home.en-US.md, packages/vant/docs/markdown/home.zh-CN.md
https://github.com/youzan/vant/discussions/9792
=> docs: add @antmjs/vantui to ecosystem

packages/vant/src/tabs/Tabs.tsx
https://github.com/youzan/vant/issues/9803
=> fix(Tabs): should emit click-tab after before-change

packages/vant/src/nav-bar/NavBar.tsx, packages/vant/src/nav-bar/README.md, packages/vant/src/nav-bar/README.zh-CN.md, packages/vant/src/nav-bar/index.ts
https://github.com/youzan/vant/issues/9816
=> types(NavBar): fix NavBarProps spelling

packages/vant/src/submit-bar/index.ts
https://github.com/youzan/vant/issues/9816
=> types(Submit): fix missing SubmitBarProps export

packages/vant/src/password-input/PasswordInput.tsx, packages/vant/src/password-input/README.md, packages/vant/src/password-input/README.zh-CN.md, packages/vant/src/password-input/index.ts
https://github.com/youzan/vant/issues/9816
=> types(PasswordInput): add PasswordInputProps type

src/switch/index.less
https://github.com/youzan/vant/issues/9839
=> fix(Switch): switch node inherit font-size

src/dialog/README.md, src/dialog/README.zh-CN.md
https://github.com/youzan/vant/issues/9847
=> docs(Dialog): add beforeRouteLeave faq

src/tabbar-item/index.js, src/tabbar/index.js
https://github.com/youzan/vant/issues/9833
=> fix(Tabbar): before-change not work in route mode

src/picker/PickerColumn.js
https://github.com/youzan/vant/issues/9873
=> fix(Picker): SSR broken

packages/vant/src/coupon-list/CouponList.tsx, packages/vant/src/coupon-list/index.less, packages/vant/src/coupon-list/test/__snapshots__/index.spec.ts.snap
https://github.com/youzan/vant/issues/9777
=> fix(CouponList): incorrect list height

packages/vant-use/src/useClickAway/index.ts
https://github.com/youzan/vant/issues/9897
=> fix(@vant/use): useClickAway failed in SSR

packages/vant/src/address-edit/AddressEdit.tsx
https://github.com/youzan/vant/commit/1b6bae671dad6ecd34548a97905ab14afcc08428
=> fix(AddressEdit): should not emit save event when validation failed

src/tabbar-item/index.js
feat(Tabbar): #9173 support highlighted with child route
=> feat(Tabbar): #9173 support highlighted with child route

packages/vant/src/calendar/Calendar.tsx, packages/vant/src/calendar/test/prop.spec.ts
https://github.com/youzan/vant/issues/9937
=> fix(Calendar): auto selected to max range when show-confirm is false

packages/vant/src/calendar/Calendar.tsx, packages/vant/src/calendar/CalendarMonth.tsx, packages/vant/src/calendar/types.ts
https://github.com/youzan/vant/issues/9894
=> fix(Calendar): should scroll to current date instead of current month

packages/vant-cli/src/config/webpack.package.ts, yarn.lock
https://github.com/youzan/vant/issues/9954
=> fix(@vant/cli): incorrect global object for async chunk

src/uploader/index.js
fix(Uploader): preview is slow when sum of images size be bigger(#7307)
=> fix(Uploader): preview is slow when sum of images size be bigger(#7307)

packages/vant/src/locale/README.md, packages/vant/src/locale/lang/pt-BR.ts
- Translation file added for Brazilian Portuguese.
- Entry added to Locale README.
=> feat(Locale): add pt-BR locale

packages/vant/src/uploader/Uploader.tsx
fix(Uploader): preview is slow when sum of images size be bigger(#7307) (#9953)
=> fix(Uploader): preview is slow when sum of images size be bigger

packages/vant-cli/src/compiler/compile-bundles.ts, packages/vant/package.json
https://github.com/youzan/vant/issues/9860
=> feat: generate mjs entry file for nuxt3

packages/vant/src/form/README.md, packages/vant/src/form/README.zh-CN.md, packages/vant/src/form/demo/FieldTypeArea.vue
https://github.com/youzan/vant/issues/9962
=> docs(Form): fix area values

packages/vant/package.json
https://github.com/youzan/vant/issues/9973
=> fix: exports field break SSR

packages/vant/docs/markdown/use-rect.zh-CN.md
- docs: fix useRect docs 。useRect() should be used in onMounted function
=> docs(@vant/use): useRect should be used inside onMounted

packages/vant-cli/docs/config.md
https://github.com/youzan/vant/issues/9990
=> docs(@vant/cli): add base css document

packages/vant-cli/src/compiler/compile-bundles.ts
https://github.com/youzan/vant/issues/9998
=> fix(@vant/cli): fix ssr.js require path

packages/vant-cli/package.json, packages/vant/src/pagination/Pagination.tsx, packages/vant/src/pagination/test/index.spec.ts, pnpm-lock.yaml
https://github.com/youzan/vant/issues/10017
=> fix(Pagination): change event not work

src/form/README.md, src/form/README.zh-CN.md
https://github.com/youzan/vant/issues/10023
=> docs(Form): improve required description

packages/vant/docs/markdown/quickstart.en-US.md, packages/vant/docs/markdown/quickstart.zh-CN.md
https://github.com/youzan/vant/issues/9957
=> docs: lock vite-plugin-style-import version

src/datetime-picker/index.js, src/datetime-picker/shared.js
https://github.com/youzan/vant/issues/10013
=> fix(DatetimePicker): should update value after calling picker methods

packages/vant/src/field/Field.tsx, packages/vant/src/field/test/__snapshots__/index.spec.js.snap, packages/vant/src/field/test/index.spec.js, packages/vant/src/field/utils.ts
https://github.com/youzan/vant/issues/10032
=> fix(Field): fix the length of emoji

packages/vant/package.json
https://github.com/youzan/vant/issues/10031
=> fix: tree shaking is broken

packages/vant/src/field/README.md, packages/vant/src/field/README.zh-CN.md, packages/vant/src/field/types.ts
https://github.com/youzan/vant/issues/10039
=> types(Field): type prop allow all native types

packages/vant/src/step/Step.tsx, packages/vant/src/steps/test/__snapshots__/index.spec.tsx.snap
` !getStatus() ` is always ` false `, this branch will never be tested
=> fix(Step): fix inactive title style

packages/vant/docs/markdown/vant-use-intro.en-US.md, packages/vant/docs/markdown/vant-use-intro.zh-CN.md
https://github.com/youzan/vant/issues/10057
=> docs: add vant use install guide

packages/vant/src/composables/use-touch.ts, packages/vant/src/swipe/Swipe.tsx
在 miui 系统的微信内缓慢下滑时，会触发浏览器自带的回弹动画。
=> fix(PullRefresh): may trigger browser bounce in some cases

packages/vant/src/cascader/test/__snapshots__/index.spec.ts.snap, packages/vant/src/coupon-list/test/__snapshots__/index.spec.ts.snap, packages/vant/src/empty/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/icon/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/index-bar/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/list/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/pull-refresh/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/tab/README.md, packages/vant/src/tab/README.zh-CN.md, packages/vant/src/tab/demo/Shrink.vue, packages/vant/src/tab/demo/index.vue, packages/vant/src/tab/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/tab/test/__snapshots__/index.spec.tsx.snap, packages/vant/src/tab/test/__snapshots__/insert.spec.tsx.snap, packages/vant/src/tabs/Tabs.tsx, packages/vant/src/tabs/TabsTitle.tsx, packages/vant/src/tabs/index.less
https://github.com/youzan/vant/issues/10124
=> feat(Tabs): add shrink prop

packages/vant/docs/markdown/home.en-US.md, packages/vant/docs/markdown/home.zh-CN.md
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
=> docs: update project description about rc-ui-lib

packages/vant/src/popup/Popup.tsx, packages/vant/src/popup/test/index.spec.js
https://github.com/youzan/vant/issues/10100
=> fix(Popup): close event emiited twice

packages/vant/src/search/Search.tsx
https://github.com/youzan/vant/issues/10114
=> types(Search): fix missing event typing

packages/vant/src/popover/index.less, packages/vant/src/popover/var.less
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
=> fix(Popover): fix gap under the triangle

packages/vant/docs/markdown/quickstart.en-US.md, packages/vant/docs/markdown/quickstart.zh-CN.md
see: https://github.com/vbenjs/vite-plugin-style-import#usage
=> docs: update document for “import on demand in vite projects”

packages/vant/src/area/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/picker/Picker.tsx
https://github.com/youzan/vant/issues/10160
=> fix(Area): missing picker mask

packages/vant/src/skeleton/Skeleton.tsx
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
=> fix(Skeleton): row为字符串数字时不能创建多行

src/tabbar/index.js
https://github.com/youzan/vant/issues/10131
=> fix(Tabbar): get correct height in mobile safari

src/nav-bar/index.js
https://github.com/youzan/vant/issues/10131
=> fix(NavBar): get correct height in mobile safari

packages/vant/src/image/Image.tsx
https://github.com/youzan/vant/issues/10046
=> fix(Image): failed to hide loading when using lazy-load

packages/vant/src/calendar/Calendar.tsx
=> fix(Calendar):  incorrectly selected when a date is disabled

src/cascader/README.md, src/cascader/README.zh-CN.md, src/cascader/index.js
close https://github.com/youzan/vant/issues/10200
=> feat(Cascader): add show-header prop

packages/vant-cli/src/compiler/gen-vetur-config.ts, packages/vant-markdown-vetur/src/vetur.ts, packages/vant/src/action-bar/README.md, packages/vant/src/button/README.md, packages/vant/src/swipe/README.md
https://github.com/youzan/vant/issues/10105
=> feat: provide english version of web-types

src/icon/index.less
https://github.com/youzan/vant/pull/10220
=> fix(Icon):  remove white space under image when using image URL

packages/vant/src/tree-select/TreeSelect.tsx, packages/vant/src/tree-select/test/index.spec.tsx
fix https://github.com/youzan/vant/issues/10222
=> fix(TreeSelect): click-nav event not work when clicking active item

packages/vant/src/locale/README.md, packages/vant/src/locale/README.zh-CN.md, packages/vant/src/locale/lang/ko-KR.ts
=> feat(Locale): add Korean translations

packages/vant/src/locale/README.md, packages/vant/src/locale/README.zh-CN.md, packages/vant/src/locale/lang/hi-IN.ts
=> feat(Locale): add Hindi translation

packages/vant-eslint-config/jest.config.js, packages/vant-eslint-config/jest.resolver.js, packages/vant-eslint-config/package.json, packages/vant-eslint-config/test/index.spec.js, packages/vant-eslint-config/test/vue/index.vue, packages/vant/src/area/Area.tsx, packages/vant/src/collapse-item/CollapseItem.tsx, packages/vant/src/field/utils.ts, packages/vant/src/form/test/props.spec.tsx, packages/vant/src/index-bar/IndexBar.tsx, packages/vant/src/uploader/test/index.spec.ts, pnpm-lock.yaml
更新所有eslint plugin 对等依赖, 更新@vant/eslint-config test cases 更新代码
风格
=> chore(eslint-config): update dependencies test cases

packages/vant-cli/site/desktop/components/Content.vue
=> feat: copy code to clipboard (#9692)

packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md, packages/vant/src/collapse-item/CollapseItem.tsx, packages/vant/src/collapse/README.md, packages/vant/src/collapse/README.zh-CN.md
close https://github.com/youzan/vant/issues/10256
=> feat(CollapseItem): add lazy-render prop

packages/vant/src/dialog/Dialog.tsx, packages/vant/src/dialog/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/dialog/test/__snapshots__/index.spec.js.snap, packages/vant/src/popup/Popup.tsx
=> feat(Dialog): support enter/esc keyboard event (#10261)

packages/vant/src/locale/README.md, packages/vant/src/locale/README.zh-CN.md, packages/vant/src/locale/lang/vi-VN.ts
=> feat(Locale): add Vietnamese translation

src/utils/test/index.spec.js, src/utils/validate/email.ts
- https://github.com/youzan/vant/issues/8211
- RegExp from: https://stackoverflow.com/a/719543/6219457
=> fix(utils):  isEmail ReDoS

packages/vant/docs/markdown/quickstart.en-US.md, packages/vant/docs/markdown/quickstart.zh-CN.md
close https://github.com/youzan/vant/issues/10300
=> docs: update vite-plugin-style-import version

README.zh-CN.md, packages/vant/docs/markdown/home.zh-CN.md
[vant-react](https://github.com/mxdi9i7/vant-react) has been stopped for a long time 👶
=> docs: update react-vant address

packages/vant/src/toast/Toast.tsx
close https://github.com/youzan/vant/issues/10310
=> fix(Toast): failed to render message after changing type

README.md, README.zh-CN.md, docs/markdown/home.en-US.md, docs/markdown/home.zh-CN.md
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
=> docs: add @formily/vant to README.md and home.md

packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md
=> docs(changelog): fix link mistake

packages/vant-cli/template/changelog-commit.hbs, packages/vant-cli/template/changelog-header.hbs
修复 [10320](https://github.com/youzan/vant/issues/10320)
=> fix: 🐛 修复官网更新日志的版本链接及 issue 链接异常的问题

packages/vant-cli/site/common/index.js, packages/vant-cli/src/common/index.ts
Fix ReDoS issue reported in huntr https://www.huntr.dev/bounties/70b0986f-6c3a-46ab-9588-61bbc11389c3/, Can you please validate this issue using `Mark as Valid` and also `Confirm the fix`. Thanks.
You can check this commit in decamelize project to improve the performance https://github.com/sindresorhus/decamelize/commit/696d5305b852bc34712f3aad215a1e1cf304ca90
=> fix(vant-cli): decamelize ReDoS

packages/vant/src/popup/Popup.tsx, packages/vant/src/popup/README.md, packages/vant/src/popup/README.zh-CN.md, packages/vant/src/popup/test/index.spec.jsx
https://github.com/youzan/vant/issues/10250
=> feat(Popup): add safe-area-inset-top prop

packages/vant/src/calendar/Calendar.tsx, packages/vant/src/calendar/README.md, packages/vant/src/calendar/README.zh-CN.md
close https://github.com/youzan/vant/issues/10250
=> feat(Calendar): add safe-area-inset-top prop

src/dialog/Dialog.js, src/dialog/test/__snapshots__/demo.spec.js.snap, src/dialog/test/__snapshots__/index.spec.js.snap
=> feat(Dialog): support keyboard events

packages/vant-use/src/usePageVisibility/index.ts
https://github.com/youzan/vant/issues/10362
=> types: fix missing VisibilityState after typescript 4.6.0

packages/vant/src/dialog/index.less
fix(Dialog): Fix dialog title and message color in dark mode
=> fix(Dialog): Fix dialog title and message color in dark mode

packages/vant/src/field/README.zh-CN.md
close https://github.com/youzan/vant/issues/10377
=> docs(Field): add v-model type guide

packages/vant/src/skeleton/Skeleton.tsx
close https://github.com/youzan/vant/issues/10378
=> fix(Skeleton): fix non-props attributes warning

packages/vant/src/calendar/README.zh-CN.md
https://github.com/youzan/vant/issues/10380
=> docs(Calendar): add formatter async usage

packages/vant/src/config-provider/ConfigProvider.tsx
close https://github.com/youzan/vant/issues/10409
=> fix(ConfigProvider): dark mode not work as default value

packages/vant/src/date-picker/DatePicker.tsx
https://github.com/youzan/vant/issues/10364
=> fix(DatePicker): failed to update model value

packages/vant/src/date-picker/README.md, packages/vant/src/date-picker/README.zh-CN.md
https://github.com/youzan/vant/issues/10364
=> docs(DatePicker): fix formatter usage

packages/vant/src/picker/README.md, packages/vant/src/picker/README.zh-CN.md, packages/vant/src/picker/demo/data.ts, packages/vant/src/picker/demo/index.vue, packages/vant/src/picker/test/__snapshots__/demo.spec.ts.snap
https://github.com/youzan/vant/issues/10364
=> docs(Picker): add v-model usage

packages/vant/src/swipe-cell/README.md, packages/vant/src/swipe-cell/README.zh-CN.md
https://github.com/youzan/vant/discussions/10427
=> remove v3 swipe-cell css variables document

packages/vant/src/grid/README.md, packages/vant/src/grid/README.zh-CN.md
https://github.com/youzan/vant/issues/10435
=> docs(Grid): fix reverse prop

src/tabbar-item/index.js, src/tabbar/index.js, src/tabbar/test/__snapshots__/index.spec.js.snap
=> fix(TabBar): route matching in special cases

packages/vant/src/datetime-picker/DatePicker.tsx
=> fix(datetime-picker): modeValue is inconsistent with the selected data.

packages/create-vant-cli-app/package.json, packages/vant-cli/README.md, packages/vant-cli/changelog.md, packages/vant-cli/docs/commands.md, packages/vant-cli/docs/config.md, packages/vant-cli/docs/directory.md, packages/vant-eslint-config/README.md, packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md, packages/vant/docs/markdown/quickstart.en-US.md, packages/vant/docs/markdown/quickstart.zh-CN.md, packages/vant/docs/markdown/theme.zh-CN.md, packages/vant/src/image-preview/README.md, packages/vant/src/share-sheet/README.md, packages/vant/src/share-sheet/demo/index.vue
Using https://github.com/antfu/case-police to make the case correct.
=> chore: make the case correct

packages/vant/src/contact-card/README.zh-CN.md
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
=> docs: fix ContactCard return error

src/locale/README.md, src/locale/README.zh-CN.md, src/locale/lang/vi-VN.ts
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
=> feat: update locale（add vi-VN）

packages/vant/src/field/Field.tsx, packages/vant/src/field/README.md, packages/vant/src/field/README.zh-CN.md, packages/vant/src/field/test/index.spec.js
https://github.com/youzan/vant/issues/10467
=> feat(Field): add enterkeyhint prop

packages/vant/src/badge/README.zh-CN.md
https://github.com/youzan/vant/issues/10501
=> docs(Badge): add show-zero tip

packages/vant-cli/README.md, packages/vant-cli/README.zh-CN.md
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
=> docs(vant-cli): translate README to en

packages/vant-cli/docs/commands.md, packages/vant-cli/docs/commands.zh-CN.md, packages/vant-cli/docs/config.zh-CN.md, packages/vant-cli/docs/directory.md, packages/vant-cli/docs/directory.zh-CN.md
docs: vant-cli `docs` 目录下的文档翻译为英文
=> docs(vant-cli): translate vant-cli docs to en

packages/vant-area-data/package.json
close https://github.com/youzan/vant/issues/10525
=> fix(@vant/area-data): only publish dist folder to npm

packages/vant/src/search/index.less
=> fix(search): style error in dark mode

packages/vant/src/field/Field.tsx, packages/vant/src/field/types.ts, packages/vant/src/form/Form.tsx, packages/vant/src/form/README.md, packages/vant/src/form/README.zh-CN.md, packages/vant/src/form/test/props.spec.tsx, packages/vant/src/uploader/Uploader.tsx, packages/vant/src/uploader/utils.ts, packages/vant/src/utils/basic.ts
close https://github.com/youzan/vant/issues/10520
=> feat(Form): support setting multile validate-trigger

packages/vant/docs/markdown/vant-use-intro.en-US.md, packages/vant/docs/markdown/vant-use-intro.zh-CN.md
Hi @chenjiahan , I will translate the rest of the composable docs in this week.
=> docs: update the composables content

packages/vant-cli/src/config/webpack.base.ts
=> feat(cli:babel-loader): cli2.x add pnpm support

src/dialog/Dialog.js, src/dialog/test/__snapshots__/demo.spec.js.snap, src/dialog/test/__snapshots__/index.spec.js.snap
close https://github.com/youzan/vant/issues/10552
=> fix(Dialog): should not submit form after clicking button

packages/vant/src/stepper/README.md, packages/vant/src/stepper/README.zh-CN.md
https://github.com/youzan/vant/issues/10567
=> docs(Stepper): improve the description of allow-empty prop

packages/vant/src/locale/README.md, packages/vant/src/locale/lang/he-IL.ts
**Summary**
- Added Hebrew translate Locale
- Added he-IL to locales README
=> Added he-IL support.

packages/vant-cli/src/compiler/compile-sfc.ts
=> fix(@vant-cli): compile error when using setup syntactic sugar

packages/vant/src/field/Field.tsx
=> fix(field): dynamic data causes the input to be emptied

src/popover/README.md, src/popover/README.zh-CN.md
=> docs(popover): can't close when use get-container

packages/vant/src/field/Field.tsx, packages/vant/src/field/README.md, packages/vant/src/field/README.zh-CN.md, packages/vant/src/field/index.ts, packages/vant/src/field/types.ts, packages/vant/src/form/Form.tsx, packages/vant/src/form/README.md, packages/vant/src/form/README.zh-CN.md, packages/vant/src/form/test/methods.spec.tsx, packages/vant/src/form/types.ts
close https://github.com/youzan/vant/issues/10619
=> feat(Form): add getValidationStatus method

packages/vant/package.json, packages/vant/vant.config.mjs
https://github.com/youzan/vant/issues/10533
https://github.com/youzan/vant/pull/10348
=> feat: using mjs extension for esmodule

packages/vant/src/cell/README.md
cell英文文档 center 参数 默认值错误修改
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
=> docs(cell): center parameter default value edit

packages/vant/src/locale/README.md, packages/vant/src/locale/lang/fa-IR.ts
- Translation files added for Farsi.
- Entries added to Locale README and table reordered to be alphabetical
- Chinese Local README file will need to be updated by someone with knowledge of Chinese ;)
=> feat(Locale): Add Farsi translations

.github/workflows/deploy-v3-site.yml, .github/workflows/test.yml, package.json, packages/vant-cli/package.json, packages/vant-cli/src/module.d.ts, packages/vant/package.json, pnpm-lock.yaml
https://github.com/youzan/vant/issues/10636
=> chore: compatible with pnpm v7

docs/markdown/quickstart.en-US.md, docs/markdown/quickstart.zh-CN.md, packages/vant-cli/site/desktop/index.html, packages/vant-cli/src/config/webpack.site.dev.ts, packages/vant-touch-emulator/README.md
https://github.com/youzan/vant/issues/10631
=> chore: fix cdn link

packages/vant-cli/src/common/constant.ts, packages/vant-cli/src/compiler/compile-script.ts, packages/vant-cli/src/compiler/gen-style-deps-map.ts, packages/vant-cli/src/compiler/get-deps.ts, packages/vant/package.json
https://github.com/youzan/vant/issues/10589
=> feat(@vant/cli): auto complete mjs path

packages/vant-area-data/package.json, packages/vant-popperjs/package.json, packages/vant-use/package.json
https://github.com/youzan/vant/issues/10589
=> feat: add exports fields to sub packages

packages/vant/src/area/test/__snapshots__/index.spec.js.snap, packages/vant/src/picker/Picker.tsx, packages/vant/src/picker/PickerColumn.tsx
close https://github.com/youzan/vant/issues/10634
=> fix(Area): failed to render picker mask after reopened

packages/vant/src/uploader/Uploader.tsx
close https://github.com/youzan/vant/issues/10674
=> types(Uploader): preview-options images should be optional

packages/vant/src/toast/function-call.tsx, packages/vant/src/toast/types.ts
close https://github.com/youzan/vant/issues/10684
=> types(Toast): fix Toast.clear typing

packages/vant/src/pull-refresh/PullRefresh.tsx, packages/vant/src/pull-refresh/README.md, packages/vant/src/pull-refresh/README.zh-CN.md, packages/vant/src/pull-refresh/test/index.spec.ts
close https://github.com/youzan/vant/issues/10687
=> feat(PullRefresh): add change event

packages/vant/src/popup/Popup.tsx
https://github.com/youzan/vant/issues/10692
=> fix(Popup): should not auto close on deactivated if not using teleport

packages/vant/src/calendar/Calendar.tsx
https://github.com/youzan/vant/pull/10668
=> fix(Calendar): failed to render months when not poppable

packages/vant/src/switch/README.md, packages/vant/src/switch/README.zh-CN.md
close https://github.com/youzan/vant/issues/10717
=> docs(Switch): fix custom node demo

packages/vant/src/action-bar/ActionBar.tsx, packages/vant/src/action-bar/README.md, packages/vant/src/action-bar/README.zh-CN.md, packages/vant/src/action-bar/test/__snapshots__/index.spec.ts.snap, packages/vant/src/action-bar/test/index.spec.ts, pnpm-lock.yaml
https://github.com/youzan/vant/issues/10715
=> feat(ActionBar): add placeholder prop

packages/vant-cli/package.json, packages/vant/src/submit-bar/README.md, packages/vant/src/submit-bar/README.zh-CN.md, packages/vant/src/submit-bar/SubmitBar.tsx, packages/vant/src/submit-bar/test/__snapshots__/index.spec.ts.snap, packages/vant/src/submit-bar/test/index.spec.ts, pnpm-lock.yaml
close https://github.com/youzan/vant/issues/10715
=> feat(SubmitBar): add placeholder prop

packages/vant/src/field/Field.tsx, packages/vant/src/field/README.md, packages/vant/src/field/README.zh-CN.md, packages/vant/src/form/test/events.spec.tsx
close https://github.com/youzan/vant/issues/10669
=> feat(Field): add start-validate and end-validate event

packages/vant/docs/markdown/quickstart.en-US.md, packages/vant/docs/markdown/quickstart.zh-CN.md
https://github.com/youzan/vant/issues/10709
=> docs: add guide of function component style

src/step/index.js, src/steps/README.md, src/steps/README.zh-CN.md, src/steps/index.js
close https://github.com/youzan/vant/issues/10575
=> feat(Steps): add align-center prop

packages/vant/docs/markdown/migrate-from-v3.zh-CN.md, packages/vant/src/icon/demo/index.vue, packages/vant/src/notify/README.md, packages/vant/src/notify/README.zh-CN.md, packages/vant/src/notify/demo/index.vue, packages/vant/src/notify/function-call.tsx, packages/vant/src/notify/index.ts, packages/vant/src/notify/test/index.spec.ts, packages/vant/src/notify/types.ts
same as https://github.com/youzan/vant/pull/10781
=> refactor(Notify): redesign function-call API

packages/vant/docs/markdown/migrate-from-v3.zh-CN.md, packages/vant/src/dialog/README.zh-CN.md, packages/vant/src/image-preview/README.md, packages/vant/src/image-preview/README.zh-CN.md, packages/vant/src/image-preview/demo/index.vue, packages/vant/src/image-preview/function-call.tsx, packages/vant/src/image-preview/index.ts, packages/vant/src/image-preview/test/function-call.spec.ts, packages/vant/src/uploader/Uploader.tsx
same as https://github.com/youzan/vant/pull/10781
=> refactor(ImagePreview): redesign function-call API

packages/vant-compat/LICENSE, packages/vant-compat/README.md, packages/vant-compat/build.js, packages/vant-compat/package.json, packages/vant-compat/src/dialog.ts, packages/vant-compat/src/image-preview.ts, packages/vant-compat/src/index.ts, packages/vant-compat/src/notify.ts, packages/vant-compat/src/toast.ts, packages/vant-compat/tsconfig.json, packages/vant-use/build.js, packages/vant/docs/markdown/migrate-from-v3.zh-CN.md, pnpm-lock.yaml
Add `@vant/compat` to help users migrate from Vant 3 to Vant 4.
=> feat: add @vant/compat package

src/uploader/README.md, src/uploader/README.zh-CN.md
close https://github.com/youzan/vant/issues/10813
=> docs(Uploader): fix isOverSize param

package.json, pnpm-lock.yaml
Signed-off-by: Sepush <sepush@outlook.com>
fix error cause by pnpm strict-peer-dependencies strategy
=> chore: peer dependencies

packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md
https://github.com/youzan/vant/issues/10792
=> docs(changelog): 4.0.0-beta.0

packages/vant/src/composables/use-height.ts, packages/vant/src/composables/use-placeholder.tsx
close https://github.com/youzan/vant/issues/10815
=> fix: failed to get correct height of safe area element

packages/create-vant-cli-app/generators/vue3/src/demo-button/demo/index.vue
close https://github.com/youzan/vant/issues/10829
=> fix(create-vant-cli-app): missing demo registration

packages/vant/src/popover/Popover.tsx, packages/vant/src/popover/demo/index.vue
close https://github.com/youzan/vant/issues/10833
=> fix(Popover): allow to dynamically set offset prop

packages/vant/src/checkbox/README.md, packages/vant/src/checkbox/README.zh-CN.md, packages/vant/src/form/README.md, packages/vant/src/form/README.zh-CN.md, packages/vant/src/radio/README.md, packages/vant/src/radio/README.zh-CN.md, packages/vant/src/stepper/README.md, packages/vant/src/stepper/README.zh-CN.md, packages/vant/src/swipe-cell/README.md, packages/vant/src/swipe-cell/README.zh-CN.md, packages/vant/src/uploader/README.md, packages/vant/src/uploader/README.zh-CN.md
- https://github.com/youzan/vant/pull/10821
- https://github.com/youzan/vant/issues/10481
=> docs: improve description of name and required props

packages/vant/src/button/README.md, packages/vant/src/button/README.zh-CN.md
Fixed several inconsistencies in documentation and examples.
=> fix(docs): fix button example type in documentation

packages/vant/src/icon/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/picker/Picker.tsx, packages/vant/src/picker/PickerColumn.tsx, packages/vant/src/picker/README.md, packages/vant/src/picker/README.zh-CN.md, packages/vant/src/picker/test/index.spec.tsx
close https://github.com/vant-ui/vant/issues/10853
=> feat(Picker): add clickOption event

packages/vant/src/space/README.md, packages/vant/src/space/README.zh-CN.md, packages/vant/src/space/Space.tsx, packages/vant/src/space/demo/index.vue, packages/vant/src/space/index.less, packages/vant/src/space/index.ts, packages/vant/src/space/test/index.spec.tsx, packages/vant/vant.config.mjs
1. Read the [contributing guide](https://github.com/vant-ui/vant/blob/dev/.github/CONTRIBUTING.md).
feat(Space): add new component space for issues https://github.com/vant-ui/vant/issues/7982
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
=> feat(Space): add new component space

packages/vant/src/calendar/Calendar.tsx
close https://github.com/vant-ui/vant/issues/10893
=> fix(Calendar): fix reading getFullYear error

packages/vant/src/calendar/Calendar.tsx
https://github.com/vant-ui/vant/pull/10908
=> fix(Calendar): reading getFullYear error in some cases

packages/vant/src/search/index.less
close https://github.com/vant-ui/vant/issues/10905
=> fix(Search): --van-search-input-height var not work

packages/vant/src/field/Field.tsx, packages/vant/src/field/types.ts, packages/vant/src/field/utils.ts, packages/vant/src/form/README.md, packages/vant/src/form/README.zh-CN.md, packages/vant/src/form/test/props.spec.tsx
close https://github.com/vant-ui/vant/issues/10896
=> feat(Form): add validateEmpty option of rule

packages/vant/src/search/README.zh-CN.md
1. Read the [contributing guide](https://github.com/vant-ui/vant/blob/dev/.github/CONTRIBUTING.md).
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
=> docs(Search): fix action-text type

packages/vant/src/pull-refresh/PullRefresh.tsx
close https://github.com/vant-ui/vant/issues/10920
ref: https://github.com/vuejs/core/issues/3786
=> fix(PullRefresh): remove passive event warning

packages/vant/src/config-provider/ConfigProvider.tsx, packages/vant/src/config-provider/README.md, packages/vant/src/config-provider/README.zh-CN.md, packages/vant/src/config-provider/test/index.spec.tsx
close https://github.com/vant-ui/vant/issues/10925
=> feat(ConfigProvider): add theme-vars-dark and theme-vars-light props

packages/vant/src/dialog/README.zh-CN.md, packages/vant/src/image-preview/README.zh-CN.md, packages/vant/src/notify/README.zh-CN.md, packages/vant/src/toast/README.zh-CN.md
close https://github.com/vant-ui/vant/issues/10940
=> docs: add faq of remove babel-plugin-import

README.md, README.zh-CN.md, packages/vant/docs/markdown/quickstart.en-US.md, packages/vant/docs/markdown/quickstart.zh-CN.md
close https://github.com/vant-ui/vant/issues/10897
=> docs: improve quickstart document

packages/vant/package.json, packages/vant/src/composables/use-lock-scroll.ts, packages/vant/src/popover/Popover.tsx, pnpm-lock.yaml
close https://github.com/vant-ui/vant/issues/10694
=> fix(Popover): can not scroll inside popup

packages/vant/src/image-preview/ImagePreviewItem.tsx, packages/vant/src/index-bar/IndexBar.tsx, packages/vant/src/number-keyboard/NumberKeyboard.tsx, packages/vant/src/number-keyboard/NumberKeyboardKey.tsx, packages/vant/src/password-input/PasswordInput.tsx, packages/vant/src/picker/PickerColumn.tsx, packages/vant/src/pull-refresh/PullRefresh.tsx, packages/vant/src/rate/Rate.tsx, packages/vant/src/slider/Slider.tsx, packages/vant/src/stepper/Stepper.tsx, packages/vant/src/swipe-cell/SwipeCell.tsx, packages/vant/src/swipe/Swipe.tsx, packages/vant/src/vue-tsx-shim.d.ts
https://github.com/vant-ui/vant/issues/10920
=> fix: reduce passive event warning of touchstart event

packages/vant/src/tabs/Tabs.tsx, packages/vant/src/tabs/TabsContent.tsx
close https://github.com/vant-ui/vant/issues/10960
=> fix(Tabs): resize not work for swipeable tabs

packages/vant/src/field/Field.tsx, packages/vant/src/field/demo/CustomType.vue, packages/vant/src/field/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/image-preview/ImagePreviewItem.tsx, packages/vant/src/index-bar/IndexBar.tsx, packages/vant/src/overlay/Overlay.tsx, packages/vant/src/picker/Picker.tsx, packages/vant/src/picker/PickerColumn.tsx, packages/vant/src/rate/Rate.tsx, packages/vant/src/slider/Slider.tsx, packages/vant/src/swipe-cell/SwipeCell.tsx, packages/vant/src/swipe/Swipe.tsx
https://github.com/vant-ui/vant/issues/10920
=> fix: reduce passive event warning of touchmove event

packages/vant/docs/markdown/quickstart.en-US.md, packages/vant/docs/markdown/quickstart.zh-CN.md
https://github.com/vant-ui/vant/issues/10877
=> docs: add nuxt 3 guide

packages/vant/src/swipe/Swipe.tsx
close https://github.com/vant-ui/vant/issues/10963
=> fix(Swipe): should not prevent touch move when reach edge

packages/vant/src/index-bar/IndexBar.tsx
=> fix(indexBar): index-bar not positioned correctly

packages/vant-cli/src/compiler/compile-sfc.ts
https://github.com/vant-ui/vant/issues/10987
=> fix(@vant/cli): failed to build types of sfc

packages/vant/src/toast/Toast.tsx, packages/vant/src/toast/test/__snapshots__/index.spec.ts.snap, packages/vant/src/toast/test/index.spec.ts
https://github.com/vant-ui/vant/issues/10659
=> feat(Toast): add message slot

packages/vant/src/toast/README.md, packages/vant/src/toast/README.zh-CN.md, packages/vant/src/toast/demo/index.vue, packages/vant/src/toast/test/__snapshots__/demo.spec.ts.snap
https://github.com/vant-ui/vant/issues/10659
=> docs(Toast): add component usage guide

src/uploader/index.js
I don't think the image that fails to upload does not need to be converted again. I hope the big guy will adopt it.
=> fix(Uploader): optimize image preview

types/image-preview.d.ts
close https://github.com/youzan/vant/issues/11046
=> types(ImagePreview): fix missing onScale type

packages/vant/src/coupon-list/test/__snapshots__/index.spec.ts.snap, packages/vant/src/tabs/Tabs.tsx
close https://github.com/youzan/vant/issues/11056
=> fix(Tabs): incorrect scroll position when inited

packages/vant-use/changelog.md, packages/vant-use/package.json, packages/vant/package.json, pnpm-lock.yaml
close https://github.com/youzan/vant/issues/11073
=> release: vant@1.4.3

packages/vant/src/field/Field.tsx, packages/vant/src/field/README.md, packages/vant/src/field/README.zh-CN.md
https://github.com/youzan/vant/issues/11070
=> feat(Field): add message param to 'end-validate' method

packages/vant/src/cascader/test/__snapshots__/index.spec.ts.snap, packages/vant/src/tab/Tab.tsx, packages/vant/src/tab/test/__snapshots__/index.spec.tsx.snap
close https://github.com/youzan/vant/issues/11050
=> fix(Tabs): incorrect scroll position in some cases

packages/vant/src/loading/Loading.tsx, packages/vant/src/loading/README.md, packages/vant/src/loading/README.zh-CN.md, packages/vant/src/loading/demo/index.vue, packages/vant/src/loading/test/__snapshots__/demo.spec.ts.snap
https://github.com/youzan/vant/issues/11063
=> feat(Loading): add icon slot

packages/vant/src/field/README.md, packages/vant/src/field/README.zh-CN.md, packages/vant/src/field/index.less, packages/vant/src/field/types.ts, packages/vant/src/form/README.md, packages/vant/src/form/README.zh-CN.md
label-position: top 对于文字较长的field label 能够比较友好的显示
=> feat: add label-position:top for field and form

packages/vant/src/field/Field.tsx, packages/vant/src/field/index.less, packages/vant/src/field/test/__snapshots__/index.spec.js.snap, packages/vant/src/field/test/index.spec.js
https://github.com/youzan/vant/pull/11102
=> fix(Field): icon position when label align is top

packages/vant/docs/markdown/faq.zh-CN.md
https://github.com/youzan/vant/issues/11113
=> docs: add faq of uni-app

packages/vant/src/tree-select/README.md, packages/vant/src/tree-select/README.zh-CN.md, packages/vant/src/tree-select/demo/data-en.ts, packages/vant/src/tree-select/demo/data-zh.ts, packages/vant/src/tree-select/test/__snapshots__/demo.spec.ts.snap
close https://github.com/youzan/vant/issues/11127
=> docs(TreeSelect): make document consistent with demo

docs/markdown/changelog.en-US.md, docs/markdown/changelog.zh-CN.md
https://github.com/youzan/vant/pull/11140
=> docs(changelog): vant@2.12.51

packages/vant/src/toast/README.md, packages/vant/src/toast/README.zh-CN.md, packages/vant/src/toast/Toast.tsx, packages/vant/src/toast/index.less, packages/vant/src/toast/types.ts
https://github.com/youzan/vant/issues/11145
=> feat(toast): add wordBreak prop

packages/vant/src/field/README.md, packages/vant/src/field/README.zh-CN.md
https://github.com/youzan/vant/issues/11151
=> docs(Field): fix field docs typo

packages/vant/src/coupon-list/index.less, packages/vant/src/coupon/index.less
Fix the selector name in Coupon component.
=> fix(Coupon): incorrect field style

package.json, packages/vant/src/swipe/Swipe.tsx, pnpm-lock.yaml
close https://github.com/youzan/vant/issues/11143
=> fix(Swipe): failed to render when inside popup

packages/vant/src/calendar/Calendar.tsx, packages/vant/src/calendar/CalendarHeader.tsx, packages/vant/src/calendar/README.md, packages/vant/src/calendar/README.zh-CN.md, packages/vant/src/calendar/test/__snapshots__/index.spec.ts.snap, packages/vant/src/calendar/test/index.spec.ts
https://github.com/youzan/vant/issues/11135
=> feat(Calendar): add params for subtitle slot

packages/vant/src/form/README.md, packages/vant/src/form/README.zh-CN.md
docs(ui/form): fix form docs code
fix code error in form docs
=> docs(ui/form): fix form docs code

packages/vant/src/uploader/Uploader.tsx, packages/vant/src/uploader/test/index.spec.ts
https://github.com/youzan/vant/issues/11217
=> fix(Uploader): chooseFile is invalid when show-upload = false

src/action-sheet/index.less
2.x修复：https://github.com/youzan/vant/issues/11211
=> fix(ActionSheet): fix that close is invalid without title

packages/vant-cli/src/common/index.ts, packages/vant-cli/src/compiler/compile-site.ts
https://github.com/youzan/vant/issues/11199
=> feat(cli): allow to custom server.port

packages/vant-cli/docs/config.md, packages/vant-cli/docs/config.zh-CN.md, packages/vant-cli/src/common/index.ts, packages/vant-cli/src/compiler/compile-bundles.ts, packages/vant-cli/src/compiler/compile-site.ts
close https://github.com/youzan/vant/issues/10492
=> feat(cli): support vite.config.ts

packages/vant/src/composables/use-sync-prop-ref.ts, packages/vant/src/popover/Popover.tsx, packages/vant/src/popover/README.md, packages/vant/src/popover/README.zh-CN.md, packages/vant/src/popover/demo/index.vue, packages/vant/src/popover/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/popover/test/index.spec.tsx
close https://github.com/youzan/vant/issues/11209
=> feat(Popover): support uncontrolled mode

packages/vant/test/demo.ts
https://github.com/youzan/vant/pull/11236
=> test: attach demo to body

packages/vant/src/image-preview/ImagePreview.tsx, packages/vant/src/image-preview/ImagePreviewItem.tsx, packages/vant/src/image-preview/README.md, packages/vant/src/image-preview/README.zh-CN.md, packages/vant/src/image-preview/test/index.spec.ts, packages/vant/src/stepper/Stepper.tsx, packages/vant/src/stepper/test/index.spec.ts, packages/vant/src/utils/constant.ts
close https://github.com/youzan/vant/issues/11238
=> feat(ImagePreview): add long-press event

docs/markdown/changelog.en-US.md, docs/markdown/changelog.zh-CN.md
https://github.com/youzan/vant/pull/11261
=> docs(changelog): vant@2.12.53

packages/vant/src/back-top/BackTop.tsx, packages/vant/src/back-top/README.md, packages/vant/src/back-top/README.zh-CN.md, packages/vant/src/back-top/demo/index.vue, packages/vant/src/back-top/index.less, packages/vant/src/back-top/index.ts, packages/vant/src/back-top/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/back-top/test/demo.spec.ts, packages/vant/src/back-top/test/index.spec.ts, packages/vant/src/back-top/types.ts, packages/vant/vant.config.mjs
新增 BackTop 组件
但是 demo test 有问题...我在这方面不熟悉，因此我没排查出来...
能否请大佬有空时给看下
=> feat(BackTop): new component

packages/vant/src/list/List.tsx
close https://github.com/youzan/vant/issues/11266
=> fix(List): incorrect initial loading value

packages/vant/src/cell/Cell.tsx
=> fix(Cell): arrow-direction assignment right is invalid

packages/vant/src/dialog/README.md
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
=> fix(Dialog): fix dialog docs typo

packages/vant/src/list/List.tsx, packages/vant/src/list/README.md, packages/vant/src/list/README.zh-CN.md, packages/vant/src/list/test/index.spec.jsx
close https://github.com/youzan/vant/issues/11271
=> feat(List): add disabled prop

packages/vant/src/field/Field.tsx
close https://github.com/youzan/vant/issues/11289
=> fix(Field): keep selection position after updating value

packages/vant/src/back-top/BackTop.tsx
improve the production bundle size
=> chore(BackTop): only print error msg in development

packages/vant/src/uploader/README.md, packages/vant/src/uploader/README.zh-CN.md
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
=> docs: remove unnecessary code example

packages/vant/src/field/Field.tsx
close https://github.com/youzan/vant/issues/11331
=> fix(Field): set selection range only when focused

packages/vant/src/utils/mount-component.ts
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
=> chore: adjust extend method import path

packages/vant/src/field/Field.tsx
https://github.com/youzan/vant/issues/11331
=> fix(Field): incorrect cursor position when using formatter

packages/vant/src/icon/demo/index.vue
fix https://github.com/youzan/vant/issues/11349 in vant 4
=> fix: fix copying errors of  icon demo

packages/vant/src/composables/use-height.ts
close https://github.com/youzan/vant/issues/11325
=> fix(NavBar): update placeholder height when window resized

packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md
close https://github.com/youzan/vant/issues/11335
=> docs(changelog): vant@4.0.2

README.md, README.zh-CN.md, preview.yml
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
=> docs: add Cloud IDE preview online

packages/vant/src/cell/Cell.tsx, packages/vant/src/field/Field.tsx, packages/vant/src/field/test/__snapshots__/index.spec.js.snap, packages/vant/src/field/test/index.spec.js
close https://github.com/youzan/vant/issues/11368
=> fix(Field): failed to dynamically set empty label

packages/vant/src/image/Image.tsx
fix: https://github.com/youzan/vant/issues/11375
=> fix(ImagePreview): fix loading when previewing images

packages/vant/src/field/Field.tsx
=> fix(Field): incorrect cursor position when value length exceeds maxlength or when formatter is used

packages/vant/src/picker-group/README.md, packages/vant/src/picker-group/README.zh-CN.md
针对官方文档中pockerGroup组件给出的案例代码中的一些小问题的修复
=> docs(PickerGroup): readme document errors fix

packages/vant/src/picker/README.md, packages/vant/src/picker/README.zh-CN.md
=> docs: fix typo in picker

packages/vant/src/image/Image.tsx, packages/vant/src/image/README.md, packages/vant/src/image/README.zh-CN.md
https://github.com/youzan/vant/issues/11395
=> fix(Image): load event missing params

packages/vant/docs/markdown/contribution.zh-CN.md
=> docs: update contribution guide

packages/vant/src/badge/Badge.tsx
fix: https://github.com/youzan/vant/issues/11394
对于`offset`的理解好像跟原来不太一样，我理解的是以不同的位置为基准点进行偏移，参考了高德地图中`marker`的`offset`。大佬看下目前这样的是否合理。
=> fix(Badge): fix badge offset of different position

packages/vant-cli/src/config/vite.package.ts
https://github.com/youzan/vant/issues/11422
=> fix(cli): should not empty out dir

packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md
https://github.com/youzan/vant/issues/11422
=> docs(changelog): vant@4.0.6

packages/vant/src/swipe/Swipe.tsx
close https://github.com/youzan/vant/issues/11204
=> fix(Swipe): failed to render inside keep-alive

packages/vant-use/src/useRelation/useChildren.ts, packages/vant/src/tab/test/__snapshots__/insert.spec.tsx.snap, packages/vant/src/tab/test/insert.spec.tsx
close https://github.com/youzan/vant/issues/11457
=> fix(Tabs): incorrect insert position in some cases

packages/vant-use/changelog.md, packages/vant/package.json, pnpm-lock.yaml
https://github.com/youzan/vant/issues/11457
=> docs(changelog): @vant/use@1.4.4

packages/vant/src/picker-group/PickerGroup.tsx, packages/vant/src/picker-group/README.md, packages/vant/src/picker-group/README.zh-CN.md, packages/vant/src/picker-group/demo/NextStepButton.vue, packages/vant/src/picker-group/demo/index.vue, packages/vant/src/picker-group/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/picker-group/test/index.spec.tsx
close https://github.com/youzan/vant/issues/11471
=> feat(PickerGroup): add next-step-text prop

packages/vant/src/image-preview/ImagePreview.tsx, packages/vant/src/image-preview/ImagePreviewItem.tsx
https://github.com/youzan/vant/issues/11411
=> fix(ImagePreview): should disable zoom when swiping

packages/vant/src/image-preview/ImagePreviewItem.tsx, packages/vant/vant.config.mjs
close https://github.com/youzan/vant/issues/4487
=> feat(ImagePreview): add swipe when image is moved to edge

packages/vant/src/slider/Slider.tsx
=> fix(slider): fix the problem that the slider button does not work properly in two-thumb mode

packages/vant/src/slider/Slider.tsx
Fix wrong behavior when user drags the slider bar.
=> fix(Slider): wrong behavior in two-thumb mode

packages/vant-use/src/useEventListener/index.ts, packages/vant/docs/markdown/use-event-listener.en-US.md, packages/vant/docs/markdown/use-event-listener.zh-CN.md
close https://github.com/youzan/vant/issues/11525
=> feat(@vant/use): support cleanup useEventListener

packages/vant/src/form/README.md, packages/vant/src/form/README.zh-CN.md
colse: https://github.com/youzan/vant/issues/11559
=> docs(Form): fix error variable of the form

packages/vant/src/form/demo/FieldTypeArea.vue
=> fix(Form): fix FieldTypeArea demo of form

packages/vant/src/picker-group/PickerGroup.tsx
=> fix(PickerGroup): Invalid slot

packages/vant/src/picker-group/PickerGroup.tsx, packages/vant/src/picker-group/test/index.spec.tsx
close https://github.com/youzan/vant/issues/11563
=> fix(PickerGroup): confirm event missing params

packages/vant/src/tabs/Tabs.tsx
close: https://github.com/youzan/vant/issues/11542
=> fix(PickerGroup): fix style of tab-line caused by v-show

packages/vant/src/popover/Popover.tsx
=> fix(popover): location update

README.md, README.zh-CN.md, packages/vant/docs/markdown/home.en-US.md, packages/vant/docs/markdown/home.zh-CN.md, packages/vant/docs/markdown/quickstart.en-US.md, packages/vant/docs/markdown/quickstart.zh-CN.md
=> docs: add an introduction to van-nuxt

packages/vant/src/back-top/BackTop.tsx, packages/vant/src/back-top/README.md, packages/vant/src/back-top/README.zh-CN.md, packages/vant/src/back-top/index.less, packages/vant/src/back-top/test/index.spec.ts, packages/vant/src/back-top/types.ts
see: https://github.com/youzan/vant/issues/11579
=> feat(BackTop): support css variable and prop of z-index

packages/vant/src/date-picker/README.md, packages/vant/src/date-picker/README.zh-CN.md, packages/vant/src/picker/PickerColumn.tsx, packages/vant/src/picker/README.md, packages/vant/src/picker/README.zh-CN.md, packages/vant/src/picker/test/__snapshots__/slots.spec.ts.snap, packages/vant/src/picker/test/slots.spec.ts, packages/vant/src/time-picker/README.md, packages/vant/src/time-picker/README.zh-CN.md
close https://github.com/youzan/vant/issues/11572
=> feat(Picker): expose option index to option slot

packages/vant/src/field/index.less
close: https://github.com/youzan/vant/issues/11607
=> fix(Field): fix label-align top not work when set label-width

packages/vant/src/cell/README.md, packages/vant/src/cell/README.zh-CN.md
https://github.com/youzan/vant/pull/11603
=> docs(Cell): remove value only document

packages/vant-cli/src/compiler/web-types/formatter.ts
https://github.com/youzan/vant/issues/11575
=> fix(cli): failed to match arguments in some cases

README.md, README.zh-CN.md, packages/vant/docs/markdown/home.en-US.md, packages/vant/docs/markdown/home.zh-CN.md
Thanks @landluck and @wjw-gavin for your contribution to Vant and Vant Weapp, you deserve to be added to the core team list.
Let's build Vant / Vant Weapp better together .^_^
=> docs: add @landluck and @wjw-gavin to core team

packages/vant/src/uploader/utils.ts
feat(Uploader):support avif image format
=> feat(Uploader):support avif image format

packages/vant-use/package.json
https://github.com/youzan/vant/issues/11659
=> fix(@vant/use): add vue as peer dependencies

packages/vant-use/changelog.md, packages/vant/package.json, pnpm-lock.yaml
close https://github.com/youzan/vant/issues/11659
=> docs(changelog): @vant/use 1.5.1

packages/vant-cli/package.json, packages/vant-compat/package.json, packages/vant-use/package.json, packages/vant/package.json, pnpm-lock.yaml
https://github.com/youzan/vant/issues/11627
=> chore: bump vue to latest version

packages/vant/src/text-ellipsis/index.less
close: https://github.com/youzan/vant/issues/11661
=> fix(TextEllipsis): fix that numbers and letters cannot display ellipses

packages/vant/src/locale/README.md, packages/vant/src/locale/lang/km-KH.ts
=> feat(Locale): Added Khmer Translaions.

packages/vant-cli/src/cli.ts, packages/vant-cli/src/commands/jest.ts, packages/vant/package.json, packages/vant/src/field/Field.tsx, packages/vant/src/field/demo/LabelAlign.vue, packages/vant/src/field/index.less, packages/vant/src/field/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/form/test/__snapshots__/props.spec.tsx.snap, packages/vant/src/form/test/props.spec.tsx
=> fix(Field): label-align top works well with label-width

packages/vant/src/share-sheet/ShareSheet.tsx, packages/vant/src/share-sheet/demo/index.vue, packages/vant/src/share-sheet/test/index.spec.ts
=> fix(share-sheet): allow custom icon

packages/vant/src/config-provider/demo/index.vue, packages/vant/src/config-provider/test/__snapshots__/demo.spec.ts.snap
close https://github.com/youzan/vant/issues/11718
=> docs(ConfigProvider): optimize theme demo

packages/vant/src/circle/README.md, packages/vant/src/circle/README.zh-CN.md
https://github.com/youzan/vant/issues/11712
=> docs(Circle): add stroke-width description

packages/vant/src/datetime-picker/README.md, packages/vant/src/datetime-picker/README.zh-CN.md
close: https://github.com/youzan/vant/issues/11749
=> docs(DatetimePicker): fix docs code

packages/vant/src/picker/Picker.tsx, packages/vant/src/picker/PickerColumn.tsx, packages/vant/src/picker/README.md, packages/vant/src/picker/README.zh-CN.md, packages/vant/src/picker/test/index.spec.tsx
https://github.com/youzan/vant/issues/11754
=> feat(Picker): add scroll-into event

packages/vant/src/pagination/Pagination.tsx, packages/vant/src/pagination/README.md, packages/vant/src/pagination/README.zh-CN.md, packages/vant/src/pagination/test/index.spec.ts, packages/vant/src/sticky/Sticky.tsx
close https://github.com/youzan/vant/issues/11767
=> feat(Pagination): add show-prev-button, show-next-button props

packages/vant/src/time-picker/README.md, packages/vant/src/time-picker/README.zh-CN.md
=> docs(TimePicker): fix docs error

packages/vant/src/date-picker/utils.ts, packages/vant/src/time-picker/test/index.spec.tsx
=> fix(TimePicker): should update modelValue correctly

packages/vant/src/image/Image.tsx
close https://github.com/youzan/vant/issues/11557
=> fix(Image): failed to display loading when using lazy-load

packages/vant/package.json, pnpm-lock.yaml
https://github.com/youzan/vant/issues/11812
=> fix: release-it can not handle workspace protocol

packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md
https://github.com/youzan/vant/issues/11812
=> docs(changelog): vant@4.3.1

packages/vant/src/image-preview/ImagePreviewItem.tsx
=> feat(ImagePreview): use the touched point as the center of zooming

src/icon/demo/index.vue
https://github.com/youzan/vant-weapp/issues/5197
=> docs(icon): icon demo params adaptive vant weapp

packages/vant/src/date-picker/DatePicker.tsx, packages/vant/src/date-picker/test/index.spec.ts
=> fix(DatePicker): should display correctly when modelValue is updated from external

packages/vant/src/coupon-list/README.md, packages/vant/src/coupon-list/README.zh-CN.md
=> docs(Coupon): fix docs type

packages/vant/src/contact-edit/README.md, packages/vant/src/contact-edit/README.zh-CN.md
=> docs(ContactEdit): fix docs type and emit

packages/vant/src/contact-list/README.md, packages/vant/src/contact-list/README.zh-CN.md
=> docs(ContactList): fix type

packages/vant/src/area/README.md, packages/vant/src/area/README.zh-CN.md
=> docs(Area): fix docs events

packages/vant/src/address-edit/AddressEdit.tsx, packages/vant/src/address-edit/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/address-edit/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/address-edit/test/__snapshots__/index.spec.ts.snap
=> fix(AddressEdit): hide border of the last cell

packages/vant/src/address-edit/README.md, packages/vant/src/address-edit/README.zh-CN.md, packages/vant/src/address-list/README.md, packages/vant/src/address-list/README.zh-CN.md
=> docs(Address): fix props and methods

packages/vant-cli/site/desktop/components/Content.vue, packages/vant-cli/site/mobile/components/DemoBlock.vue
Sync mobile position on anchor clicks for better DX.
=> docs: sync mobile position on anchor click

packages/vant/src/uploader/README.md, packages/vant/src/uploader/README.zh-CN.md, packages/vant/src/uploader/Uploader.tsx, packages/vant/src/uploader/UploaderPreviewItem.tsx, packages/vant/src/uploader/demo/index.vue, packages/vant/src/uploader/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/uploader/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/uploader/test/index.spec.ts, packages/vant/src/uploader/types.ts
close #11587 
https://vant-git-patch-uploader-zhousg.vercel.app/#/zh-CN/uploader#kai-qi-fu-gai-shang-chuan
=> feat(Uploader): add reupload

packages/vant/src/image-preview/ImagePreviewItem.tsx
=> feat(ImagePreview): optimize the preview effect of long images

packages/vant/src/uploader/README.md, packages/vant/src/uploader/demo/index.vue
=> docs(Uploader): Optimized translation

packages/vant/src/divider/Divider.tsx, packages/vant/src/divider/README.md, packages/vant/src/divider/README.zh-CN.md, packages/vant/src/divider/demo/index.vue, packages/vant/src/divider/index.less, packages/vant/src/divider/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/divider/test/__snapshots__/demo.spec.ts.snap
=> feat(Divider): add vertical prop

packages/vant/src/tree-select/README.md, packages/vant/src/tree-select/README.zh-CN.md
=> docs(TreeSelect): props add v-model

packages/vant/src/tab/Tab.tsx
close #11763  过度一下? @chenjiahan
=> fix(Tab): Maximum recursive updates exceeded in component <van-tabs>

packages/vant/package.json, packages/vant/src/tab/Tab.tsx, packages/vant/src/tab/test/index.spec.tsx, pnpm-lock.yaml
- https://github.com/youzan/vant/pull/11898
- https://github.com/youzan/vant/issues/11763
=> chore(Tab): using Vue built-in stringifyStyle

packages/vant/src/popup/Popup.tsx
=> fix(Popup): duration 0s and enable lazyRender opened is executed twice

packages/vant/src/index-bar/README.md, packages/vant/src/index-bar/README.zh-CN.md
=> docs(IndexBar): update props type

packages/vant/src/date-picker/utils.ts, packages/vant/src/time-picker/README.md, packages/vant/src/time-picker/README.zh-CN.md, packages/vant/src/time-picker/TimePicker.tsx, packages/vant/src/time-picker/demo/index.vue, packages/vant/src/time-picker/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/time-picker/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/time-picker/test/index.spec.tsx, packages/vant/src/utils/basic.ts
It allows for more flexible filtering of available time ranges.
=> feat(TimePicker): filter support values param to help get current values

packages/vant-cli/site/mobile/App.vue, packages/vant/src/back-top/BackTop.tsx
The `floating-bubble` component is mentioned here because I found this bug when reviewing this component.
After the https://github.com/youzan/vant/pull/11880 is merged in the future, no additional changes are required.
---
before:
https://github.com/youzan/vant/assets/15389209/10ded93c-3ad3-4f25-ba9e-f56d41c0cef9
after:
https://github.com/youzan/vant/assets/15389209/31ed949c-131f-4a5e-a97b-8b99371fdc22
=> fix(BackTop): should hide when deactivated

packages/vant/src/address-list/AddressList.tsx, packages/vant/src/address-list/AddressListItem.tsx, packages/vant/src/address-list/README.md, packages/vant/src/address-list/README.zh-CN.md
=> feat(AddressList): add new right-icon props

packages/vant/src/dropdown-menu/index.ts
=> fix(DropdownMenu): fix missing exported type

packages/vant/src/rolling-text/README.md, packages/vant/src/rolling-text/README.zh-CN.md
=> docs(RollingText): update docs

packages/create-vant-cli-app/generators/vue3/package.json.tpl
=> chore(CLI): upgrade vue

packages/vant/src/config-provider/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/config-provider/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/field/Field.tsx, packages/vant/src/field/test/index.spec.js, packages/vant/src/form/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/form/test/__snapshots__/demo.spec.ts.snap
=> fix(Field): should not set `for` attr to label when using input slot

packages/vant/src/image-preview/ImagePreviewItem.tsx, packages/vant/src/rate/README.md, packages/vant/src/rate/README.zh-CN.md, packages/vant/src/rate/Rate.tsx, packages/vant/src/rate/demo/index.vue, packages/vant/src/rate/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/rate/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/rate/test/index.spec.ts, packages/vant/src/utils/constant.ts
=> feat(Rate): add clearable prop

packages/vant/src/picker/PickerColumn.tsx, packages/vant/src/picker/test/index.spec.tsx
=> fix(Picker): optimize the animation effect of sliding multiple columns simultaneously

packages/vant/src/composables/use-touch.ts, packages/vant/src/rate/Rate.tsx
onlyTap 逻辑移至 use-touch，供其余组件复用
=> refactor(use-touch): move onlyTap logic to use-touch

packages/vant/src/floating-panel/FloatingPanel.tsx
=> fix(FloatingPanel): Reuse closest function

packages/vant/src/floating-bubble/README.md, packages/vant/src/floating-bubble/README.zh-CN.md, packages/vant/src/floating-bubble/index.less
=> fix(FloatingBubble): optimized css var

README.md, README.zh-CN.md, packages/vant/docs/markdown/home.en-US.md, packages/vant/docs/markdown/home.zh-CN.md
Thanks @inottn and @zhousg for your contribution to Vant!
I am delighted to invite you to join the vant core team and enjoy the open source ^_^
Contributions of inottn:
- https://github.com/youzan/vant/commits?author=inottn
- https://github.com/youzan/vant/issues?q=commenter:inottn
Contributions of zhousg:
- https://github.com/youzan/vant/commits?author=zhousg
- https://github.com/youzan/vant/issues?q=commenter:zhousg
I have referred to the [Node.js Project Governance](https://github.com/nodejs/node/blob/main/GOVERNANCE.md), and in the future, we can create a Vant Project Governance to clarify the standards for the vant core team.
=> docs: add @inottn and @zhousg to core team

packages/vant/src/button/demo/index.vue, packages/vant/src/rolling-text/demo/index.vue
To avoid affecting the global styles.
=> docs: improve style

packages/vant/src/floating-bubble/types.ts
floatingBubbleBackground type is optional
=> fix(FloatingBubble): floatingBubbleBackground type is optional

packages/vant/src/style/mixins/ellipsis.less
=> feat(ellipsis): improve break lines of Chinese, Japanese, or Korean text

packages/vant/src/action-bar/README.zh-CN.md, packages/vant/src/button/README.zh-CN.md, packages/vant/src/cell/README.zh-CN.md, packages/vant/src/grid/README.zh-CN.md, packages/vant/src/sidebar/README.zh-CN.md, packages/vant/src/tab/README.zh-CN.md, packages/vant/src/tabbar/README.zh-CN.md
For more information, please refer to [Navigate to a different location](https://router.vuejs.org/guide/essentials/navigation.html#navigate-to-a-different-location).
=> docs(Tabbar): update the link related to vue-router

packages/vant/src/action-bar/README.md, packages/vant/src/action-bar/README.zh-CN.md, packages/vant/src/button/README.md, packages/vant/src/button/README.zh-CN.md, packages/vant/src/cell/README.md, packages/vant/src/cell/README.zh-CN.md, packages/vant/src/grid/README.md, packages/vant/src/grid/README.zh-CN.md, packages/vant/src/sidebar/README.md, packages/vant/src/sidebar/README.zh-CN.md, packages/vant/src/tab/README.md, packages/vant/src/tab/README.zh-CN.md, packages/vant/src/tabbar/README.md, packages/vant/src/tabbar/README.zh-CN.md
Consistent with Chinese documentation
=> docs: add Vue Router links to english document

packages/vant-eslint-config/index.js, packages/vant-eslint-config/package.json, packages/vant/src/lazyload/demo/index.vue, pnpm-lock.yaml
ref: https://github.com/import-js/eslint-plugin-import/pull/2447
=> refactor(eslint-config): remove eslint-plugin-import

.npmrc, package.json, packages/vant-eslint-config/package.json, pnpm-lock.yaml
ref: https://github.com/pnpm/pnpm/issues/6463
=> chore: using pnpm highest resolution mode

packages/vant/src/pagination/index.less
=> fix(Pagination): display the border correctly

packages/vant/src/floating-bubble/FloatingBubble.tsx
=> fix(FloatingBubble): fix wrong value of boundary

packages/vant/src/text-ellipsis/README.md, packages/vant/src/text-ellipsis/README.zh-CN.md, packages/vant/src/text-ellipsis/TextEllipsis.tsx, packages/vant/src/text-ellipsis/demo/index.vue, packages/vant/src/text-ellipsis/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/text-ellipsis/test/__snapshots__/demo.spec.ts.snap
relate： https://github.com/youzan/vant/pull/11942,   https://github.com/youzan/vant/issues/11935
**ps:** 整体功能代码为 [cxybd](https://github.com/cxybd) 贡献，再次感谢！考虑其 pr 存在部分文件不兼容：test、pnpm-lock.yaml 等，我这在整理后重新提交，辛苦作者在 review 并 merge 后，标注由 [cxybd](https://github.com/cxybd) 贡献，多谢！
重新 review 了一下代码，发现问题：按钮折行。
**修改后：**
=> feat(TextEllipsis): add position prop

packages/vant/src/address-list/AddressList.tsx, packages/vant/src/address-list/README.md, packages/vant/src/address-list/README.zh-CN.md
close: https://github.com/youzan/vant/issues/12087
=> feat(AddressList): add show-add-button prop

packages/vant/src/circle/README.md, packages/vant/src/circle/README.zh-CN.md
- docs(Circle): using demo is wrong(:text="左侧")
=> docs(Circle): usage error

packages/vant/src/floating-bubble/index.ts
=> fix(FloatingBubble): fix global component type

packages/vant/src/tab/Tab.tsx
=> fix(Tab): adjust import path

packages/vant/src/config-provider/README.md, packages/vant/src/config-provider/README.zh-CN.md
=> docs(ConfigProvider): fix css demo error

packages/vant/src/uploader/Uploader.tsx, packages/vant/src/uploader/UploaderPreviewItem.tsx, packages/vant/src/uploader/types.ts
Example：
Allowed Types:
- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
=> fix(Uploader): render objectUrl to avoid perf issue

packages/vant/src/text-ellipsis/TextEllipsis.tsx, packages/vant/src/text-ellipsis/test/__snapshots__/demo.spec.ts.snap
=> fix(TextEllipsis): dots repeated

packages/vant/src/text-ellipsis/TextEllipsis.tsx
=> fix(TextEllipsis): fix the logic of calculating the position of ellipsis

packages/vant/src/locale/lang/sr-SR.ts
add Serbian language to internationalization
=> feat(Locale): add Serbian language to internationalization

packages/vant/src/image-preview/ImagePreview.tsx, packages/vant/src/image-preview/ImagePreviewItem.tsx, packages/vant/src/image-preview/README.md, packages/vant/src/image-preview/README.zh-CN.md, packages/vant/src/image-preview/function-call.tsx, packages/vant/src/image-preview/test/index.spec.ts, packages/vant/src/image-preview/types.ts
close https://github.com/youzan/vant/issues/12108
=> feat(ImagePreview): add closeOnClickOverlay option

packages/vant/src/list/List.tsx, packages/vant/src/list/README.md, packages/vant/src/list/README.zh-CN.md
close https://github.com/youzan/vant/issues/12074
=> feat(List): add scroller prop

packages/vant/src/floating-panel/FloatingPanel.tsx, packages/vant/src/floating-panel/README.md, packages/vant/src/floating-panel/README.zh-CN.md
=> feat(FloatingPanel): add lock-scroll prop

packages/vant/src/floating-panel/FloatingPanel.tsx, packages/vant/src/floating-panel/README.md, packages/vant/src/floating-panel/README.zh-CN.md
=> chore(FloatingPanel): change the default value of lock-scroll to false

packages/vant/src/floating-panel/FloatingPanel.tsx
close https://github.com/youzan/vant/issues/12146
=> fix(floatingPanel): Lag caused by scrollbar and panel movement #12146

packages/vant/src/dropdown-menu/DropdownMenu.tsx, packages/vant/src/dropdown-menu/README.md, packages/vant/src/dropdown-menu/README.zh-CN.md, packages/vant/src/dropdown-menu/demo/index.vue, packages/vant/src/dropdown-menu/index.less, packages/vant/src/dropdown-menu/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/dropdown-menu/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/dropdown-menu/test/index.spec.tsx
=> feat(DropdownMenu): add swipe-threshold prop

README.md, README.zh-CN.md, packages/create-vant-cli-app/generators/vue2/docs/quickstart.md, packages/create-vant-cli-app/generators/vue3/docs/quickstart.md, packages/vant-area-data/README.md, packages/vant-cli/README.md, packages/vant-cli/README.zh-CN.md, packages/vant-cli/docs/config.md, packages/vant-cli/docs/config.zh-CN.md, packages/vant-compat/README.md, packages/vant-eslint-config/README.md, packages/vant-icons/README.md, packages/vant-popperjs/README.md, packages/vant-touch-emulator/README.md, packages/vant-use/README.md, packages/vant/docs/markdown/migrate-from-v3.en-US.md, packages/vant/docs/markdown/migrate-from-v3.zh-CN.md, packages/vant/docs/markdown/quickstart.en-US.md, packages/vant/docs/markdown/quickstart.zh-CN.md, packages/vant/docs/markdown/vant-use-intro.en-US.md, packages/vant/docs/markdown/vant-use-intro.zh-CN.md, packages/vant/src/area/README.md, packages/vant/src/area/README.zh-CN.md, packages/vant/src/cascader/README.zh-CN.md
=> docs: add instructions for bun package manager

packages/vant/src/floating-bubble/FloatingBubble.tsx
=> fix(FloatingBubble): does not update state while hidden

packages/vant/src/dropdown-item/DropdownItem.tsx, packages/vant/src/dropdown-item/types.ts, packages/vant/src/dropdown-menu/README.md, packages/vant/src/dropdown-menu/README.zh-CN.md
DropdownItemOption supports boolean value
close #12164
=> feat(DropdownItem): supports boolean Value

packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md
`2023-08-20`
- feat(DropdownItem): supports boolean value in options by [@baboon-king](https://github.com/baboon-king) in [#12208](https://github.com/youzan/vant/pull/12208)
- fix(FloatingBubble): drag should not trigger click on child elements by [@zhousg](https://github.com/zhousg) in [#12201](https://github.com/youzan/vant/pull/12201)
- fix(FloatingBubble): does not update state while hidden by [@zhousg](https://github.com/zhousg) in [#12207](https://github.com/youzan/vant/pull/12207)
- chore(CI): update issue comment messages by [@chenjiahan](https://github.com/chenjiahan) in [#12204](https://github.com/youzan/vant/pull/12204)
- refactor(cli): remove execa dependency by [@chenjiahan](https://github.com/chenjiahan) in [#12205](https://github.com/youzan/vant/pull/12205)
=> docs(changelog): vant@4.6.6

packages/vant/src/checkbox/Checkbox.tsx, packages/vant/src/checkbox/Checker.tsx, packages/vant/src/checkbox/README.md, packages/vant/src/checkbox/README.zh-CN.md, packages/vant/src/checkbox/demo/index.vue, packages/vant/src/checkbox/index.less, packages/vant/src/checkbox/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/checkbox/test/__snapshots__/demo.spec.ts.snap
close: https://github.com/youzan/vant/issues/12215
=> feat(Checkbox): add indeterminate status

packages/vant/src/config-provider/ConfigProvider.tsx, packages/vant/src/config-provider/README.md, packages/vant/src/config-provider/README.zh-CN.md, packages/vant/src/config-provider/index.ts, packages/vant/src/config-provider/test/index.spec.tsx
add theme-vars-scope props enable root affects
close #12235
=> feat(ConfigProvider): add theme-vars-scope props enable root affects

packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md
* feat(vant-use): add useRaf by @Simon-He95 in https://github.com/youzan/vant/pull/12211
* feat(Checkbox): add indeterminate status by @wjw-gavin in https://github.com/youzan/vant/pull/12216
* feat(auto-import-resolver): add auto-import-resolver package by @wChenonly in https://github.com/youzan/vant/pull/12227
* feat(ConfigProvider): add theme-vars-scope props enable root affects by @zhousg in https://github.com/youzan/vant/pull/12240
* fix(auto-import-resolver): type mismatch in TS projects by @chenjiahan in https://github.com/youzan/vant/pull/12243
* fix(eslint): eslint 不再支持.eslintignore文件, 需要在.eslintrc配置ignorePatterns …
=> docs(changelog): vant@4.6.7

packages/vant/src/config-provider/types.ts
- ConfigProviderThemeVars `fontSizeXs` hump
- fontSizeXs 驼峰修正
=> fix(ConfigProvider): ConfigProviderThemeVars `fontSizeXs` hump

packages/vant/src/nav-bar/NavBar.tsx, packages/vant/src/nav-bar/README.md, packages/vant/src/nav-bar/README.zh-CN.md, packages/vant/src/nav-bar/index.less
NavBar add leftDisabled and rightDisabled prop.
=> feat(NavBar): add leftDisabled and rightDisabled prop

.github/workflows/codeql-analysis.yml, .github/workflows/deploy-v4-site.yml, .github/workflows/pr-label.yaml, .github/workflows/release-tag.yml, .github/workflows/sync-gitee.yml, .github/workflows/test.yml
=> chore(CI): bump actions version

packages/vant/src/picker/README.md, packages/vant/src/picker/README.zh-CN.md
=> docs(Picker): 补充 picker 组件的文档

packages/vant/src/uploader/README.md, packages/vant/src/uploader/README.zh-CN.md, packages/vant/src/uploader/index.less
- feat(Uploader): add `--van-uploader-border-radius` css variables.
- 给 `Uploader` 组件添加 `--van-uploader-border-radius` css 变量。
=> feat(Uploader): add `--van-uploader-border-radius` css variables

packages/vant/src/uploader/README.md, packages/vant/src/uploader/README.zh-CN.md
https://github.com/youzan/vant/issues/12218
=> docs(Uploader): add FAQ about camera permission

packages/vant/src/picker/PickerColumn.tsx, packages/vant/src/picker/demo/index.vue
The pop-up window prompts the content error, the Chinese version does not show the index, and the English version shows the error, as follows:
[https://i.ibb.co/C87ZPzb/demo-4x.png](https://i.ibb.co/C87ZPzb/demo-4x.png)
[https://i.ibb.co/VMVCLwx/demo-4x-cn.png](https://i.ibb.co/VMVCLwx/demo-4x-cn.png)
<br/>
Fixed to stay consistent
[https://i.ibb.co/WnB86nL/demo-4x-fix.png](https://i.ibb.co/WnB86nL/demo-4x-fix.png)
=> fix(Picker): fix  bug the content of the popup window is not consistent with the Chinese version under the English version

packages/vant/src/address-edit/AddressEdit.tsx, packages/vant/src/address-edit/README.md, packages/vant/src/address-edit/README.zh-CN.md, packages/vant/src/address-edit/test/index.spec.ts
=> feat(AddressEdit): add change event for name and tel input

packages/vant/src/floating-panel/FloatingPanel.tsx, packages/vant/src/floating-panel/README.md, packages/vant/src/floating-panel/README.zh-CN.md
=> fix(FloatingPanel): dragging down causes the page to move

packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md, packages/vant/src/address-edit/README.md, packages/vant/src/address-edit/README.zh-CN.md, packages/vant/src/calendar/README.md, packages/vant/src/calendar/README.zh-CN.md
* feat(Calendar): add click-disabled-date event by @LadyChatterleyLover in https://github.com/youzan/vant/pull/12274
* feat(Uploader): add `--van-uploader-border-radius` css variables by @xieyezi in https://github.com/youzan/vant/pull/12280
* feat(Icon): add 11 new icons by @chenjiahan in https://github.com/youzan/vant/pull/12291
* feat(SwipeCell): Fix triggered close by clickAway when in running beforeClose by @nined9 in https://github.com/youzan/vant/pull/12309
* feat(AddressEdit): add change event for name and tel input by @zhousg in https://github.com/youzan/vant/pull/12310
* types(Dialog): improve showDialog return …
=> docs(changelog): vant 4.7.0

packages/vant/src/composables/use-scope-id.ts, packages/vant/src/popup/Popup.tsx
- close https://github.com/youzan/vant/issues/12326
- https://github.com/vuejs/core/issues/2669
=> fix(Popup): fix failed to inherit scopedId

packages/vant/src/cell-group/CellGroup.tsx
https://github.com/youzan/vant/issues/12326
=> fix(CellGroup): failed to inherit scopeId with title

packages/vant/src/form/README.md, packages/vant/src/tree-select/README.md, packages/vant/src/tree-select/demo/data-en.ts, packages/vant/src/tree-select/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/tree-select/test/__snapshots__/demo.spec.ts.snap
Fixed mistypo Geor**q**ia to Geor**g**ia in docs and readme
=> fix(docs): mistypo Georqia to Georgia

packages/vant/src/swipe/Swipe.tsx
=> chore(Swipe): limit the decimal length of transform

README.md, README.zh-CN.md, packages/vant/docs/markdown/home.en-US.md, packages/vant/docs/markdown/home.zh-CN.md
https://github.com/youzan/vant/issues/12325
=> docs: add more ecosystem projects

packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md
* feat(FloatingPanel): optimize bounce animate by @zhousg in https://github.com/youzan/vant/pull/12317
* feat(cli): using rslog by @chenjiahan in https://github.com/youzan/vant/pull/12334
* style(Swipe): declare transition-property by @chenjiahan in https://github.com/youzan/vant/pull/12336
* feat(Notify): add jsdoc for utility functions by @chenjiahan in https://github.com/youzan/vant/pull/12342
* feat(Dialog): add JSDoc for utility functions by @chenjiahan in https://github.com/youzan/vant/pull/12343
* feat(Toast): add JSDoc for utility functions by @chenjiahan in https://github.com/youzan/vant/pull/12344
* fix(Popup): …
=> docs(changelog): vant@4.7.1

packages/vant-icons/src/common.less
icon的font-family增加css变量
场景：页面通过设置--icon-font-family变量控制icon展示
=> feat(Icon): add font-family css var

package.json, yarn.lock
功能：icon font-family支持变量--van-icon-font-family
=> feat(Icon):  bump vant icons 3.0.1 to support icon font-family

packages/vant/src/signature/Signature.tsx, packages/vant/src/signature/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/signature/test/__snapshots__/ssr.spec.ts.snap
=> refactor(Signature): avoid setting the canvas width and height in the next tick

packages/vant/src/signature/Signature.tsx
=> refactor(Signature): use scale method to enhance clarity

packages/vant/src/image-preview/ImagePreview.tsx, packages/vant/src/image-preview/ImagePreviewItem.tsx, packages/vant/src/image-preview/README.md, packages/vant/src/image-preview/README.zh-CN.md, packages/vant/src/image-preview/function-call.tsx, packages/vant/src/image-preview/test/index.spec.ts, packages/vant/src/image-preview/types.ts
enableDoubleScale -> doubleScale
make the prop name shorter.
=> chore(ImagePreview): rename doubleScale and add test case

packages/vant/src/config-provider/types.ts
=> fix(ConfigProvider): export missing theme vars

packages/vant/src/cell/Cell.tsx, packages/vant/src/contact-edit/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/contact-edit/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/field/Field.tsx, packages/vant/src/field/README.md, packages/vant/src/field/README.zh-CN.md, packages/vant/src/field/demo/Required.vue, packages/vant/src/field/demo/index.vue, packages/vant/src/field/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/field/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/field/test/index.spec.js, packages/vant/src/field/types.ts, packages/vant/src/form/Form.tsx, packages/vant/src/form/README.md, packages/vant/src/form/README.zh-CN.md, packages/vant/src/form/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/form/test/__snapshots__/demo.spec.ts.snap
ref: https://github.com/youzan/vant/pull/12376
=> feat(Form): add required prop and support auto display

packages/vant-auto-import-resolver/README.md, packages/vant-auto-import-resolver/README.zh-CN.md, packages/vant-auto-import-resolver/src/index.ts, packages/vant/docs/markdown/quickstart.zh-CN.md
https://github.com/youzan/vant/issues/12369
=> feat(auto-import-resolver): add module option

packages/vant/src/image-preview/test/function-call.spec.ts
https://github.com/vuejs/ecosystem-ci/actions/runs/6608899447/job/17948287815
=> test(ImagePreview): fix incorrect onClose test case

packages/vant/src/field/index.less, packages/vant/src/text-ellipsis/index.less
related: https://github.com/youzan/vant/issues/12390
=> style: replace word-break with overflow-wrap

packages/vant/src/address-edit/AddressEdit.tsx
=> fix(AddressEdit): area field validate error when showArea is false

README.md, README.zh-CN.md
=> chore: add vscode-common-intellisense to the Community Ecosystem

packages/vant/src/back-top/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/empty/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/floating-panel/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/icon/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/index-bar/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/list/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/picker-group/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/pull-refresh/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/tab/README.md, packages/vant/src/tab/README.zh-CN.md, packages/vant/src/tab/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/tab/test/index.spec.tsx, packages/vant/src/tabs/Tabs.tsx
close https://github.com/youzan/vant/issues/12389
=> feat(Tab):  add showTitle prop for Tab

packages/vant/src/back-top/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/empty/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/floating-panel/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/icon/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/index-bar/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/list/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/picker-group/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/pull-refresh/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/tab/README.md, packages/vant/src/tab/README.zh-CN.md, packages/vant/src/tab/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/tab/test/index.spec.tsx, packages/vant/src/tabs/Tabs.tsx
- add show-header prop to document
- rename `show-title` to `show-header`
=> docs(Tabs): add show-header prop

packages/vant/src/picker-group/PickerGroup.tsx, packages/vant/src/picker-group/demo/SelectDateTime.vue
resolve #12400 
是否要考虑，`div>picker` 这种情况呢~
=> fix(PickerGroup): only filter Comment vnode 

packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md
* feat(locale): Add Arabic Locale by @mo9a7i in https://github.com/youzan/vant/pull/12381
* feat(Form): add required prop and support auto display by @chenjiahan in https://github.com/youzan/vant/pull/12380
* feat(auto-import-resolver): add module option by @chenjiahan in https://github.com/youzan/vant/pull/12383
* style: replace word-break with overflow-wrap by @wjw-gavin in https://github.com/youzan/vant/pull/12396
* feat(Tab):  add show-header prop by @yoyo837 in https://github.com/youzan/vant/pull/12394
* style(Search): use consistent padding when display error msg by @chenjiahan in …
=> docs(changelog): vant v4.7.3

packages/vant-cli/package.json, pnpm-lock.yaml
- resolve https://github.com/youzan/vant/security/dependabot/12
- resolve https://github.com/youzan/vant/security/dependabot/13
=> chore(deps): fix security alerts of babel and postcss

packages/vant/src/image-preview/ImagePreview.tsx, packages/vant/src/image-preview/ImagePreviewItem.tsx, packages/vant/src/image-preview/README.md, packages/vant/src/image-preview/README.zh-CN.md, packages/vant/src/image-preview/test/index.spec.ts, packages/vant/src/image-preview/types.ts
=> feat(ImagePreview): expose resetScale method

packages/vant/src/field/README.md, packages/vant/src/field/README.zh-CN.md
=> docs(field): update props size

packages/vant/src/cell/README.md, packages/vant/src/cell/README.zh-CN.md
=> docs(cell): update props size

packages/vant/src/config-provider/types.ts, packages/vant/src/highlight/Highlight.tsx, packages/vant/src/highlight/README.md, packages/vant/src/highlight/README.zh-CN.md, packages/vant/src/highlight/demo/index.vue, packages/vant/src/highlight/index.less, packages/vant/src/highlight/index.ts, packages/vant/src/highlight/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/highlight/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/highlight/test/demo-ssr.spec.ts, packages/vant/src/highlight/test/demo.spec.ts, packages/vant/src/highlight/test/index.spec.ts, packages/vant/src/highlight/types.ts, packages/vant/vant.config.mjs
=> feat(Highlight): add highlight component

packages/vant/src/overlay/README.md, packages/vant/src/overlay/README.zh-CN.md, packages/vant/src/overlay/demo/index.vue, packages/vant/src/overlay/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/overlay/test/__snapshots__/demo.spec.ts.snap
https://github.com/youzan/vant/issues/12453
=> docs(Overlay): add set z-index demo

packages/vant/docs/markdown/quickstart.en-US.md, packages/vant/docs/markdown/quickstart.zh-CN.md
https://github.com/web-infra-dev/rsbuild
=> docs: add Rsbuild to quickstart

packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md
* feat(ImagePreview): expose resetScale method by @inottn in https://github.com/youzan/vant/pull/12426
* feat(Highlight): add highlight component by @wjw-gavin in https://github.com/youzan/vant/pull/12434
* feat(Checker): add checked and disabled params to the default slot by @inottn in https://github.com/youzan/vant/pull/12436
* feat(Row): gutter support vertical space by @cc-hearts in https://github.com/youzan/vant/pull/12439
* fix(canendar): subtitle supports reactive by @cc-hearts in https://github.com/youzan/vant/pull/12425
* docs(changelog): vant v4.7.3 by @chenjiahan in https://github.com/youzan/vant/pull/12413
* …
=> docs(changelog): vant@4.8.0

packages/vant/src/collapse/README.md, packages/vant/src/collapse/demo/index.vue, packages/vant/src/collapse/test/__snapshots__/demo-ssr.spec.ts.snap, packages/vant/src/collapse/test/__snapshots__/demo.spec.ts.snap
=> docs(collapse): fix translation Error

package.json, pnpm-lock.yaml
https://github.com/youzan/vant/issues/12495
https://github.com/web-infra-dev/rspack/pull/4830
=> chore: bump Rspack 0.4.2 to fix Chinese path

packages/vant/src/image-preview/README.md, packages/vant/src/image-preview/README.zh-CN.md
=> docs(image-preview): usage of Supplementing `className`

packages/vant/docs/markdown/quickstart.en-US.md, packages/vant/docs/markdown/quickstart.zh-CN.md
unplugin-vue-components usage updated
=> docs(Quickstart): unplugin-vue-components usage updated (#12499)

packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md
- perf(TextEllipsis): reuse windowWidth to avoid repeat calculations by [@inottn](https://github.com/inottn) in [#12471](https://github.com/youzan/vant/pull/12471)
- feat(TextEllipsis): add the toggle instance method by [@wjw-gavin](https://github.com/wjw-gavin) in [#12472](https://github.com/youzan/vant/pull/12472)
- feat(cli): bump Rsbuild v0.2.2 by [@chenjiahan](https://github.com/chenjiahan) in [#12502](https://github.com/youzan/vant/pull/12502)
- perf(cli): disable source map to make compilation faster by [@chenjiahan](https://github.com/chenjiahan) in [#12484](https://github.com/youzan/vant/pull/12484)
- fix(cli): remove unused script in template by [@chenjiahan](https://github.com/chenjiahan) in [#12482](https://github.com/youzan/vant/pull/12482)
- fix(TextEllipsis): fix missing …
=> docs(changelog): vant@4.8.1

package.json, packages/create-vant-cli-app/generators/vue2/src/demo-button/index.vue, packages/create-vant-cli-app/generators/vue3/src/demo-button/index.vue
=> fix(ci): eslint on windows (#12492)

packages/vant-area-data/package.json, packages/vant-cli/package.json, packages/vant-compat/package.json, packages/vant-popperjs/package.json, packages/vant-use/package.json, pnpm-lock.yaml
bump esbuild v0.19
https://github.com/evanw/esbuild/releases/tag/v0.19.0
=> chore(deps): bump esbuild v0.19

package.json, pnpm-lock.yaml
https://github.com/web-infra-dev/rspack/issues/5107
=> chore: lock Rspack v0.4.3 to fix CSS issue

packages/vant/src/index-bar/test/__snapshots__/demo.spec.ts.snap, packages/vant/vitest.config.ts
=> chore: update vitest config

packages/vant/src/image-preview/ImagePreviewItem.tsx
=> chore(ImagePreview): reuse isTap ref

packages/vant/src/toast/test/function.spec.ts
Reduce the running time of the test by approximately 3 seconds.
=> test(Toast): reduce test run time

packages/vant-cli/cjs/md-loader.cjs, packages/vant-cli/src/compiler/compile-site.ts
improve markdown compile performance, start up time: 3.5s -> 2.5s
=> perf(CLI): improve markdown compile performance

packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md
- feat: support link css from shadow dom by [@yoyo837](https://github.com/yoyo837) in [#12526](https://github.com/youzan/vant/pull/12526)
- feat(DropdownMenu): add auto-locate prop by [@inottn](https://github.com/inottn) in [#12251](https://github.com/youzan/vant/pull/12251)
- perf(CLI): improve markdown compile performance by [@chenjiahan](https://github.com/chenjiahan) in [#12541](https://github.com/youzan/vant/pull/12541)
- fix(ci): eslint on windows by [@Jungzl](https://github.com/Jungzl) in [#12516](https://github.com/youzan/vant/pull/12516)
- fix(ImagePreview): double-scale and close-on-click-overlay may not work in certain scenarios by [@inottn](https://github.com/inottn) in [#12521](https://github.com/youzan/vant/pull/12521)
- chore(deps): bump Rsbuild v0.2.8 by …
=> docs(changelog): vant v4.8.2

packages/vant/package.json, packages/vant/src/image/Image.tsx, packages/vant/src/image/index.ts, packages/vant/src/image/types.ts, packages/vant/tsconfig.json, pnpm-lock.yaml
1. export `ImagePosition` type.
2. make `ImageFit` & `ImagePosition` align with native css properties
=> fix(Image): ImagePosition type is not exported before

packages/vant-cli/package.json, packages/vant-compat/package.json, packages/vant-use/package.json, packages/vant/package.json, pnpm-lock.yaml
=> chore(deps): bump vue to v3.4.13

packages/vant/docs/markdown/home.en-US.md
https://vant-ui.github.io/vant/#/en-US#scaffold
=> docs(home): update heading level

packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md
* feat(Notify): add teleport prop by @inottn in https://github.com/youzan/vant/pull/12556
* feat(TextEllipsis): add `action` slot by @nemo-shen in https://github.com/youzan/vant/pull/12560
* feat(ImagePreview): add close-on-click-image prop by @inottn in https://github.com/youzan/vant/pull/12566
* feat(icons): add icon `arrow-double-left` and `arrow-double-right` by @nemo-shen in https://github.com/youzan/vant/pull/12579
* feat(Toast): add z-index prop by @inottn in https://github.com/youzan/vant/pull/12587
* fix(Tab): tab(with sticky prop) loss 'fixed' classname after switch tab by @nemo-shen in …
=> docs(changelog): vant@4.8.3

packages/vant/src/picker/PickerToolbar.tsx, packages/vant/src/picker/README.md, packages/vant/src/picker/README.zh-CN.md, packages/vant/src/picker/test/index.spec.tsx
close https://github.com/youzan/vant/issues/12562
=> feat(Picker): allow to hidden to toolbar buttons

packages/vant/src/dropdown-menu/DropdownMenu.tsx, packages/vant/src/dropdown-menu/test/index.spec.tsx
=> fix(DropdownMenu): fix recursive update when passing object literal to title-class

packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md
`2024-02-03`
- feat(Picker): allow to hidden to toolbar buttons by [@chenjiahan](https://github.com/chenjiahan) in [#12599](https://github.com/youzan/vant/pull/12599)
- fix(Sticky): initial sticky position by [@nemo-shen](https://github.com/nemo-shen) in [#12601](https://github.com/youzan/vant/pull/12601)
- fix(DropdownMenu): fix recursive update when passing object literal to title-class by [@inottn](https://github.com/inottn) in [#12614](https://github.com/youzan/vant/pull/12614)
- docs: improve quickstart tips by [@inottn](https://github.com/inottn) in [#12606](https://github.com/youzan/vant/pull/12606)
- chore(deps): bump Rsbuild 0.3.9 and enable clean dist by [@chenjiahan](https://github.com/chenjiahan) in [#12600](https://github.com/youzan/vant/pull/12600)
- chore: avoid workflow …
=> docs(changelog): vant@4.8.4

packages/vant/src/date-picker/README.md, packages/vant/src/date-picker/README.zh-CN.md, packages/vant/src/time-picker/README.md, packages/vant/src/time-picker/README.zh-CN.md, packages/vant/src/time-picker/test/index.spec.tsx
=> docs: update docs for params related to Picker events

packages/vant/src/date-picker/README.md
=> docs(DatePicker): fix en-docs error

.github/renovate.json5
setup renovate config: https://github.com/renovatebot/renovate
=> chore(workflow): setup renovate config

packages/vant/docs/markdown/advanced-usage.en-US.md, packages/vant/docs/markdown/advanced-usage.zh-CN.md
close https://github.com/youzan/vant/issues/12604
=> docs: add full registration guide

packages/vant/src/image-preview/README.md, packages/vant/src/image-preview/README.zh-CN.md, packages/vant/src/image-preview/function-call.tsx
https://github.com/youzan/vant/pull/12660
=> docs(ImagePreview): add vertical prop

.github/renovate.json5
Disable dependency dashboard to reduce issues number.
- https://docs.renovatebot.com/key-concepts/dashboard/
- https://github.com/youzan/vant/issues/12683
=> chore(workflow): disable dependency dashboard

packages/vant/src/tab/README.md, packages/vant/src/tab/README.zh-CN.md, packages/vant/src/tab/demo/index.vue
change tab's 'Before Change' into a real async function(by using setTimeout)
=> docs: change tab's 'Before Change' into a real async function

packages/vant/src/action-sheet/index.less
https://github.com/youzan/vant/pull/12671
=> fix(ActionSheet): icon class name

packages/vant-auto-import-resolver/package.json
Update `@vant/auto-import-resolver` homepage
=> chore: Update homepage

packages/vant/src/button/README.zh-CN.md
=> docs(button): Keep Chinese and English documents consistent

packages/vant/src/cell/README.md, packages/vant/src/cell/README.zh-CN.md
=> docs(cell): correct the type of label

packages/vant/src/floating-bubble/FloatingBubble.tsx
=> fix(floating-bubble): update offset when the value changed

packages/vant/src/image-preview/README.md, packages/vant/src/image-preview/README.zh-CN.md
https://github.com/youzan/vant/pull/12740
=> docs(ImagePreview): add image slot scale guide

.github/renovate.json5
=> chore(workflow): let renovate group patch updates

packages/vant/src/date-picker/DatePicker.tsx, packages/vant/src/date-picker/README.md, packages/vant/src/date-picker/README.zh-CN.md, packages/vant/src/time-picker/README.md, packages/vant/src/time-picker/README.zh-CN.md, packages/vant/src/time-picker/TimePicker.tsx
Correct return type of getSelectedTime, remove undefined.
=> chore: correct return type of getSelectedTime

packages/vant/src/dropdown-item/DropdownItem.tsx, packages/vant/src/dropdown-item/index.less, packages/vant/src/dropdown-item/types.ts, packages/vant/src/dropdown-menu/README.md, packages/vant/src/dropdown-menu/README.zh-CN.md, packages/vant/src/dropdown-menu/index.less, packages/vant/src/dropdown-menu/test/index.spec.tsx, packages/vant/src/dropdown-menu/types.ts
=> feat(DropdownMenu): add disabled for option

packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md
`2024-04-14`
- feat(DropdownMenu): add disabled for option by [@inottn](https://github.com/inottn) in [#12785](https://github.com/youzan/vant/pull/12785)
- fix: warning `is not a valid value for v-model` in JetBrains IDE by [@anyesu](https://github.com/anyesu) in [#12787](https://github.com/youzan/vant/pull/12787)
- fix(Cli): remove site tsconfig by [@chenjiahan](https://github.com/chenjiahan) in [#12792](https://github.com/youzan/vant/pull/12792)
- docs(list): update Error loading module code by [@wangjue666](https://github.com/wangjue666) in [#12778](https://github.com/youzan/vant/pull/12778)
- chore(deps): update dependency eslint-plugin-vue to ^9.24.1 by [@renovate](https://github.com/renovate) in [#12774](https://github.com/youzan/vant/pull/12774)
- chore(deps): bump Rsbuild v0.6 by …
=> docs(changelog): vant v4.8.11

package.json, pnpm-lock.yaml
https://github.com/pnpm/pnpm/releases/tag/v9.0.4
=> chore(workflow): upgrade to pnpm v9

packages/vant-cli/docs/config.md, packages/vant-cli/docs/config.zh-CN.md, packages/vant-cli/src/compiler/compile-site.ts
https://github.com/youzan/vant/issues/12804
=> feat(CLI): support for configuring Rsbuild

.github/workflows/deploy-v4-site.yml
try to fix the deploy issue
https://github.com/youzan/vant/actions/runs/8679842369/job/23799444183
=> chore: bump github-pages-deploy-action@v4.6.0

packages/vant/src/image-preview/ImagePreviewItem.tsx
=> fix(ImagePreview): swipeItem may be undefined

packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md, packages/vant/src/calendar/README.md, packages/vant/src/calendar/README.zh-CN.md
* feat(Calendar): add switch-mode prop by @inottn in https://github.com/youzan/vant/pull/12836
* feat(PickerGroup): add new prop showToolbar by @ReinoFu in https://github.com/youzan/vant/pull/12839
* feat(CLI): support for configuring Rsbuild by @chenjiahan in https://github.com/youzan/vant/pull/12809
* fix(cli): Vue SFC style binding failure by @zoy-l in https://github.com/youzan/vant/pull/12799
* fix(ImagePreview): swipeItem may be undefined by @inottn in https://github.com/youzan/vant/pull/12818
* fix(Highlight): render correctly when keywords is empty by @Jungzl in https://github.com/youzan/vant/pull/12829
* …
=> docs(changelog): vant@4.9.0

packages/vant/src/floating-panel/FloatingPanel.tsx, packages/vant/src/floating-panel/README.md, packages/vant/src/floating-panel/README.zh-CN.md, packages/vant/src/floating-panel/test/__snapshots__/index.spec.tsx.snap, packages/vant/src/floating-panel/test/index.spec.tsx
=> feat(floating-panel): support header slot

packages/vant/src/address-list/AddressList.tsx, packages/vant/src/address-list/AddressListItem.tsx, packages/vant/src/address-list/README.md, packages/vant/src/address-list/README.zh-CN.md, packages/vant/src/address-list/test/index.spec.ts
issues #12816
AddressList组件支持多选，并增加了测试用例
=> feat(AddressList): support multiple selection

packages/vant/docs/markdown/changelog.en-US.md, packages/vant/docs/markdown/changelog.zh-CN.md
`2024-06-02`
- feat(FloatingPanel): support header slot by [@chouchouji](https://github.com/chouchouji) in [#12897](https://github.com/youzan/vant/pull/12897)
- feat(AddressList): support multiple selection by [@jj56313751](https://github.com/jj56313751) in [#12887](https://github.com/youzan/vant/pull/12887)
- feat(cli): bump Rsbuild v0.7 by [@chenjiahan](https://github.com/chenjiahan) in [#12903](https://github.com/youzan/vant/pull/12903)
- feat: supports `imports` option for auto-import by [@zhaojjiang](https://github.com/zhaojjiang) in [#12861](https://github.com/youzan/vant/pull/12861)
- fix(cli): CSS preprocessor for scoped by [@zoy-l](https://github.com/zoy-l) in [#12860](https://github.com/youzan/vant/pull/12860)
- fix(area): columns-placeholder prop rendering error by …
=> docs(changelog): vant@4.9.1

packages/vant/src/notify/types.ts
补充 NotifyOptions 缺失的 zIndex 类型
=> fix(Notify): add zIndex type

packages/vant/src/notify/README.md, packages/vant/src/notify/README.zh-CN.md
=> docs(Notify): fix z-index option case

packages/vant-cli/package.json, packages/vant-compat/package.json, packages/vant-use/package.json, packages/vant/package.json, packages/vant/src/form/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/form/test/demo.skip.ts, packages/vant/src/form/test/demo.spec.ts, packages/vant/src/stepper/test/__snapshots__/demo.spec.ts.snap, packages/vant/src/stepper/test/__snapshots__/index.spec.ts.snap, packages/vant/src/stepper/test/demo.skip.ts, packages/vant/src/stepper/test/demo.spec.ts, packages/vant/src/stepper/test/index.spec.ts, pnpm-lock.yaml
=> chore: update vue to v3.4.29 and enable skipped cases

packages/vant/src/tab/README.md, packages/vant/src/tab/README.zh-CN.md
关联的 issue: https://github.com/youzan/vant/issues/12424
关联的 discussion: https://github.com/youzan/vant/discussions/12877
没有解决该 issue 涉及的问题，但是可以先给文档加上对应提示
=> docs(Tab): add FQA for "swipeable" and "animated"

packages/vant/src/uploader/README.md, packages/vant/src/uploader/README.zh-CN.md, packages/vant/src/uploader/index.ts
close https://github.com/youzan/vant/issues/12960
=> types(Uploader): export afterRead function type

packages/vant/src/button/README.md, packages/vant/src/button/README.zh-CN.md
=> docs: fix missing `plain` prop #12962

packages/vant/src/notify/types.ts
=> types(Notify): add missing teleport type

packages/vant/src/calendar/CalendarHeader.tsx, packages/vant/src/calendar/test/switch-mode.spec.ts, packages/vant/src/calendar/utils.ts
fix #13007 
Need to merge #13006 first.
=> fix(Calendar): correctly change the panelDate when the selected date is the last day of each month

.husky/commit-msg, .husky/pre-commit, packages/create-vant-cli-app/generators/vue3/.husky/commit-msg, packages/create-vant-cli-app/generators/vue3/.husky/pre-commit, packages/vant-cli/README.md, packages/vant-cli/README.zh-CN.md, packages/vant-cli/docs/commands.md, packages/vant-cli/docs/commands.zh-CN.md
https://github.com/typicode/husky/releases/tag/v9.0.1
https://remarkablemark.org/blog/2024/02/04/how-to-migrate-from-husky-8-to-9/
=> chore: update husky config for v9

.github/workflows/issue-labeled.yml
=> chore(CI): update issue comment messages

packages/vant/src/calendar/README.md, packages/vant/src/calendar/README.zh-CN.md
1. 增加文案 
```
或者，你应该采用一种在各个系统和浏览器上兼容性更好的写法：`new Date(2020, 0, 1)`，但是需要注意的是，月份是从 0 开始的。
```
2. 增加英文 FAQ
=> docs(Calendar): improve FQA

packages/vant/src/time-picker/demo/index.vue
=> docs(TimePicker): delete useless space

packages/vant/src/overlay/Overlay.tsx, packages/vant/src/overlay/README.md, packages/vant/src/overlay/README.zh-CN.md, packages/vant/src/overlay/test/index.spec.tsx
=> feat(Overlay): add teleport prop

packages/vant/src/number-keyboard/NumberKeyboard.tsx, packages/vant/src/number-keyboard/test/__snapshots__/index.spec.ts.snap, packages/vant/src/number-keyboard/test/index.spec.ts
=> fix(NumberKeyboard): lose the number 0 key in some configs

packages/vant-auto-import-resolver/build.js, packages/vant-auto-import-resolver/package.json, packages/vant-auto-import-resolver/rslib.config.ts, packages/vant-compat/build.js, packages/vant-compat/package.json, pnpm-lock.yaml
https://github.com/web-infra-dev/rslib
=> chore(auto-import): use Rslib to build

packages/vant-area-data/build.js, packages/vant-area-data/package.json, packages/vant-area-data/rslib.config.ts, pnpm-lock.yaml
https://github.com/web-infra-dev/rslib
=> chore(area-data): use Rslib to build

packages/vant/src/locale/README.md, packages/vant/src/locale/lang/pl-PL.ts
- Translation files added for polish language.
- Entry added to Locale README
- Chinese Local README file will need to be updated by someone with knowledge of Chinese ;)
=> feat(Locale): Added polish translations

packages/vant/src/picker-group/README.md, packages/vant/src/picker-group/README.zh-CN.md
=> docs(PickerGroup): add constraints to the end date

packages/vant/src/address-edit/AddressEdit.tsx, packages/vant/src/address-edit/types.ts
=> refactor(AddressEdit): remove unused country field

README.md, README.zh-CN.md, packages/vant/docs/markdown/home.en-US.md, packages/vant/docs/markdown/home.zh-CN.md
https://github.com/youzan/vant/discussions/13361
=> docs: add a community project named MobVue

packages/vant/src/rolling-text/README.zh-CN.md
=> docs: update rolling-text component title

packages/vant/src/dialog/Dialog.tsx, packages/vant/src/dialog/README.md, packages/vant/src/dialog/README.zh-CN.md, packages/vant/src/dialog/function-call.tsx
=> feat(Dialog): add destroyOnClose prop to control content destruction on close

packages/vant/src/form/README.md, packages/vant/src/form/README.zh-CN.md
=> docs(Form): fix form basic usage document errors

packages/vant/src/signature/README.md, packages/vant/src/signature/README.zh-CN.md, packages/vant/src/signature/Signature.tsx
I want to custom `tips` content style, so I add slot to meet my need.
=> feat(signature): support tips slot

.github/renovate.json5
Enable dependency dashboard to manage dependencies.
=> chore(renovate): enable dependency dashboard

packages/vant/src/picker/utils.ts, packages/vant/src/tabbar-item/TabbarItem.tsx, packages/vant/src/tabs/Tabs.tsx
This pull request includes changes to improve code readability by replacing the `find` method with more appropriate alternatives.
=> refactor: replace find method for improved readability

packages/vant/src/index-bar/test/__snapshots__/demo.spec.ts.snap, packages/vant/vitest.config.ts
Fix Vitest segmentation fault on CI: https://github.com/youzan/vant/actions/runs/14014379814/job/39238165273
Ref: https://vitest.dev/guide/common-errors.html#segfaults-and-native-code-errors
=> test: fix Vitest segmentation fault

packages/vant/src/stepper/test/index.spec.ts
=> test(Stepper): reduce test run time

README.md, README.zh-CN.md, packages/vant/docs/markdown/home.en-US.md, packages/vant/docs/markdown/home.zh-CN.md
文档-社区生态中补充 [press-ui](https://github.com/novlan1/press-ui)，基于uni-app的组件库，参考vant
=> docs: add press-ui in docs

packages/vant/src/image/README.md, packages/vant/src/image/README.zh-CN.md
https://github.com/youzan/vant/pull/13487
=> docs(Image): add decoding prop

README.md, README.zh-CN.md, packages/vant/docs/markdown/home.en-US.md, packages/vant/docs/markdown/home.zh-CN.md
Update vue3-vant-mobile and nuxt-vant-mobile links 😆
=> docs: update vue-zone project links in ecosystem
